LIB=			einfo
SHLIB_MAJOR=		1
SRCS=			libeinfo.c
INCS=			einfo.h
VERSION_MAP=		einfo.map

LOCAL_CPPFLAGS+=		-I../includes

MK=			../../mk
include ${MK}/lib.mk
include ${MK}/cc.mk
include ${MK}/termcap.mk
