.TH EDD_ID 8 "November 2005" "" "Linux Administrator's Manual"
.SH NAME
edd_id \- udev callout to identify BIOS disk drives via EDD
.SH SYNOPSIS
.BI edd_id
[\fI--export\fP] \fIblockdevice\fP
.SH "DESCRIPTION"
.B edd_id
is normally called from a udev rule, to provide udev with the edd id for
a BIOS disk drive. Udev can use this information to create symlinks in
/dev/disk/by-id and /dev/disk/by-label to the real device node.
.SH USAGE
.B edd_id
opens the blockdevice node specified at the commandline and prints the
information chosen by the options.
.SH OPTIONS
The following commandline switches are supported to specify what edd_id
should print:
.TP
.BI --export
print all values (instead of only the id)
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by John Hull <john_hull@dell.com> and Kay Sievers <kay.sievers@vrfy.org>.

