.TH CDROM_ID 8 "January 2009" "" "Linux Administrator's Manual"
.SH NAME
cdrom_id \- udev callout to determine the capabilities of optical drives and media
.SH SYNOPSIS
.B cdrom_id
[\fB--export\fP] [\fB--debug\fP] \fIdevice\fP
.br
.B cdrom_id
\fB--help\fP
.SH "DESCRIPTION"
.B cdrom_id
is normally called from a udev rule, to provide udev with the list of
capabilities of a optical drive.
.SH USAGE
.B cdrom_id
opens the device node specified at the commandline and prints the
discovered capabilities.
.SH OPTIONS
The following commandline switches are supported to specify what cdrom_id
should print:
.TP
.B -x, --export
Print all values as environment keys. This is the default at present, so this
option is currently redundant.
.TP
.B -d, --debug
Print a debug trace.
.TP
.B -h, --help
Print usage help.
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Kay Sievers <kay.sievers@vrfy.org>.

