.TH CDROM_ID 8 "April 2008" "" "Linux Administrator's Manual"
.SH NAME
cdrom_id \- udev callout to determine the capabilities of optical drives and media
.SH SYNOPSIS
.BI cdrom_id
[\fI--export\fP] \fIdevice\fP
.SH "DESCRIPTION"
.B cdrom_id
is normally called from a udev rule, to provide udev with the list of
capabilities of a optical drive.
.SH USAGE
.B cdrom_id
opens the device node specified at the commandline and prints the
discovered capabilities.
.SH OPTIONS
The following commandline switches are supported to specify what cdrom_id
should print:
.TP
.BI --export
print all values (default)
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Kay Sievers <kay.sievers@vrfy.org>.

