#!/bin/bash

RULES=label_test.rules
CONFIG=label_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
BUS="scsi", SYSFS{vendor}="IBM-ESXS", SYSFS{model}="ST336605LW   !#", NAME="boot_diskX%n"
BUS="scsi", SYSFS{vendor}="IBM-ESXS", SYSFS{model}="ST336605LW    !#", NAME="a/nice/place/to/put/a/boot_disk%n"
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udevdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

mkdir udev

export ACTION=add
export DEVPATH=block/sda

../udev block
ls -l udev

export ACTION=remove
export DEVPATH=block/sda

../udev block
ls -l udev


rm $RULES
rm $CONFIG
rm -rf udev
