#!/bin/bash

RULES=ignore_test.rules
CONFIG=ignore_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
KERNEL="ttyUSB0", NAME=""
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udev.tdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

mkdir udev

export DEVPATH=class/tty/ttyUSB0
export ACTION=add

../udev tty
ls -l udev

export ACTION=remove
../udev tty
ls -l udev

rm $RULES
rm $CONFIG
rm -rf udev
