#!/bin/bash

RULES=label_test.rules
CONFIG=label_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
LABEL, BUS="scsi", SYSFS_vendor="IBM-ESXS", SYSFS_model="ST336605LW   !#", NAME="boot_diskX%n"
LABEL, BUS="scsi", SYSFS_vendor="IBM-ESXS", SYSFS_model="ST336605LW    !#", NAME="boot_disk%n"
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udev.tdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

mkdir udev

export ACTION=add
export DEVPATH=block/sda

../udev block
ls -l udev

export DEVPATH=block/sda/sda3

../udev block
ls -l udev

export ACTION=remove
export DEVPATH=block/sda

../udev block
ls -l udev

export DEVPATH=block/sda/sda3

../udev block
ls -l udev


rm $RULES
rm $CONFIG
rm -rf udev
