#!/bin/bash

RULES=label_test.rules
CONFIG=label_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
LABEL, BUS="scsi", vendor="IBM-ESXS", NAME="boot_disk%n"
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udev.tdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

export ACTION=add
export DEVPATH=block/sda

../udev block
ls udev

export DEVPATH=block/sda/sda3

../udev block
ls udev

export ACTION=remove
export DEVPATH=block/sda

../udev block
ls udev

export DEVPATH=block/sda/sda3

../udev block
ls udev


rm $RULES
rm $CONFIG
