#!/bin/bash

export UDEV_TEST=yes
export UDEV_SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_DIR=$PWD/
export UDEV_ROOT=$PWD/udev/
export UDEV_DB=udev.tdb
export UDEV_CONFIG_FILE=label_test.config
export UDEV_PERMISSION_FILE=udev.permissions

export DEVPATH=block/sda
export ACTION=add

../udev block
