# Try to guess the build directory:
# we look for subdirectories of ../.. that look like ninja build dirs.

ifeq ($(BUILD_DIR),)
        dirs = $(dir $(wildcard ../../*/.ninja_log))
        ifeq ($(dirs),)
                $(error Cannot guess build dir, set BUILD_DIR)
        endif
        ifneq ($(firstword $(dirs)),$(dirs))
                $(warning Candidates: $(dirs))
                $(error Too many build dirs to pick from, set BUILD_DIR)
        endif
        BUILD_DIR=$(dirs)
endif
