#!/bin/bash

RULES=modifier_test.rules
CONFIG=modifier_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
TOPOLOGY, BUS="scsi", place="0:0:0:0", NAME="Major:%M:minor:%m:kernelnumber:%n:bus:%b"
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udev.tdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

export ACTION=add
export DEVPATH=block/sda

../udev block
ls udev

export DEVPATH=block/sda/sda3

../udev block
ls udev

export ACTION=remove
export DEVPATH=block/sda

../udev block
ls udev

export DEVPATH=block/sda/sda3

../udev block
ls udev

rm $RULES
rm $CONFIG
