#!/bin/bash

RULES=label_test.rules
CONFIG=label_test.conf

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_FILE=$PWD/$CONFIG

cat > $RULES << EOF
SYSFS{address}="00:e0:00:8d:9f:25", NAME="wireless"
EOF

cat > $CONFIG << EOF
udev_root="$PWD/udev/"
udev_db="$PWD/udev/.udev.tdb"
udev_rules="$PWD/$RULES"
udev_permissions="$PWD/udev.permissions"
EOF

mkdir udev

export ACTION=add
export DEVPATH=class/net/eth1

../udevtest class/net/eth1 net
ls -l udev

export ACTION=remove
export DEVPATH=class/net/eth1

../udevtest net
ls -l udev

rm $RULES
rm $CONFIG
rm -rf udev
