#!/bin/bash

export UDEV_TEST=yes
export SYSFS_PATH=$PWD/sys/
export UDEV_CONFIG_DIR=$PWD/
export UDEV_ROOT=$PWD/udev/
export UDEV_DB=udev.tdb
export UDEV_CONFIG_FILE=replace_test.config
export UDEV_PERMISSION_FILE=udev.permissions

export DEVPATH=class/tty/ttyUSB0
export ACTION=add

../udev tty
ls udev

export ACTION=remove
../udev tty
ls udev


