.TH PATH_ID 8 "April 2007" "" "Linux Administrator's Manual"
.SH NAME
path_id \- udev callout to create a device path based unique name
for a device to implement the Linux Persistent Device Naming scheme
.SH SYNOPSIS
path_id <devpath>
.SH "DESCRIPTION"
.B path_id
is normally called from a udev rule, to create a unique name, based on
the device properties along the chain of parent devices. Udev uses this
information to create a persistent symlink to the real device node.
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Hannes Reinecke <hare@suse.de>.
