# syntax - https://github.com/redhat-plumbers-in-action/devel-freezer#policy
---

policy:
  # tags like v253-rc1, v253-rc2, etc.
  - tags: ['^\S*-rc\d+$']
    labels:
      allow: ['needs-stable-backport', 'dependencies', 'l10n ðŸŒ']
    feedback:
      frozen-state: |
        > [!IMPORTANT]
        > An -rc1 tag has been created and a release is being prepared, so please note that PRs introducing new features and APIs will be held back until the new version has been released.
      unfreeze-state: |
        > [!NOTE]
        > We had successfully released a new major release. We are no longer in a development freeze phase.
        > We will try our best to get back to your PR as soon as possible. Thank you for your patience.
