# SPDX-License-Identifier: LGPL-2.1-or-later

msrv = "1.85"
check-private-items = true

[[disallowed-methods]]
path = "systemd_shared_sys::abort"
reason = "panic!() instead, the panic handler logs where and why before aborting"
