---
# SPDX-License-Identifier: LGPL-2.1-or-later
# Docs: https://packit.dev/docs/

specfile_path: .packit_rpm/systemd.spec
files_to_sync:
  - .packit.yml
  - src: .packit_rpm/systemd.spec
    dest: systemd.spec
# `git describe` returns in systemd's case 'v245-xxx' which breaks RPM version
# detection (that expects 245-xxxx'). Let's tweak the version string accordingly
upstream_tag_template: "v{version}"
srpm_build_deps: []

actions:
  get-current-version:
    - cat meson.version

  post-upstream-clone:
    # Use the Fedora f41 specfile
    - git clone -b f41 https://src.fedoraproject.org/rpms/systemd .packit_rpm --depth=1
    - bash -c 'echo "%bcond upstream 1" > .packit_rpm/systemd.spec.new'
    - bash -c 'echo "%define meson_extra_configure_options --werror" >> .packit_rpm/systemd.spec.new'
    - bash -c 'cat .packit_rpm/systemd.spec >> .packit_rpm/systemd.spec.new'
    - mv .packit_rpm/systemd.spec.new .packit_rpm/systemd.spec

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-f41-aarch64
  - fedora-f41-i386
  - fedora-f41-ppc64le
  - fedora-f41-s390x
  - fedora-f41-x86_64

- job: tests
  trigger: pull_request
  fmf_url: https://src.fedoraproject.org/tests/systemd
  fmf_ref: legacy-ci
  tmt_plan: ci
  targets:
  - fedora-f41-x86_64
