---
# SPDX-License-Identifier: LGPL-2.1-or-later
# Docs: https://packit.dev/docs/

specfile_path: .packit_rpm/systemd.spec
files_to_sync:
  - .packit.yml
  - src: .packit_rpm/systemd.spec
    dest: systemd.spec
# `git describe` returns in systemd's case 'v245-xxx' which breaks RPM version
# detection (that expects 245-xxxx'). Let's tweak the version string accordingly
upstream_tag_template: "v{version}"
srpm_build_deps: []

actions:
  get-current-version:
    - "cat meson.version"

  post-upstream-clone:
    # Use the Fedora Rawhide specfile
    - git clone https://src.fedoraproject.org/rpms/systemd .packit_rpm --depth=1
    - bash -c 'echo "%bcond upstream 1" > .packit_rpm/systemd.spec.new'
    - bash -c 'echo "%define meson_extra_configure_options --werror" >> .packit_rpm/systemd.spec.new'
    - bash -c 'cat systemd.template >> .packit_rpm/systemd.spec.new'
    - mv .packit_rpm/systemd.spec.new .packit_rpm/systemd.spec

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-rawhide-aarch64
  - fedora-rawhide-i386
  - fedora-rawhide-ppc64le
  - fedora-rawhide-s390x
  - fedora-rawhide-x86_64

- job: tests
  trigger: pull_request
  fmf_path: test/fmf
  tmt_plan: ci
  targets:
  - fedora-rawhide-x86_64
