.\"     Title: udevmonitor
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: August 2005
.\"    Manual: udevmonitor
.\"    Source: udev
.\"
.TH "UDEVMONITOR" "8" "August 2005" "udev" "udevmonitor"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevmonitor \- print the kernel and udev event sequence to the console
.SH "SYNOPSIS"
.HP 12
\fBudevmonitor\fR [\fB\-\-environment\fR] [\fB\-\-kernel\fR] [\fB\-\-udev\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
udevmonitor listens to the kernel uevents and events sent out by a udev rule and prints the devpath of the event to the console. It can be used to analyze the event timing, by comparing the timestamps of the kernel uevent and the udev event.
.SH "OPTIONS"
.PP
\fB\-\-environment\fR
.RS 4
Print the complete environment for all events. Can be used to compare the kernel supplied and the udev added environment values.
.RE
.PP
\fB\-\-kernel\fR
.RS 4
Print the kernel uevents.
.RE
.PP
\fB\-\-udev\fR
.RS 4
Print the udev event after the rule processing.
.RE
.PP
\fB\-\-help\fR
.RS 4
Print usage.
.RE
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay.sievers@vrfy.org>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
