.\"     Title: udev
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: August 2005
.\"    Manual: udev
.\"    Source: udev
.\"
.TH "UDEV" "7" "August 2005" "udev" "udev"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udev \- dynamic device management
.SH "DESCRIPTION"
.PP
udev provides a dynamic device directory containing only the files for actually present devices. It creates or removes device node files in the
\fI/dev\fR
directory, or it renames network interfaces.
.PP
Usually udev runs as
\fBudevd\fR(8)
and receives uevents directly from the kernel if a device is added or removed from the system.
.PP
If udev receives a device event, it matches its configured rules against the available device attributes provided in sysfs to identify the device. Rules that match may provide additional device information or specify a device node name and multiple symlink names and instruct udev to run additional programs as part of the device event handling.
.SH "CONFIGURATION"
.PP
All udev configuration files are placed in
\fI/etc/udev/*\fR. Every file consists of a set of lines of text. All empty lines or lines beginning with '#' will be ignored.
.SS "Configuration file"
.PP
udev expects its main configuration file at
\fI/etc/udev/udev.conf\fR. It consists of a set of variables allowing the user to override default udev values. The following variables can be set:
.PP
\fBudev_root\fR
.RS 4
Specifies where to place the device nodes in the filesystem. The default value is
\fI/dev\fR.
.RE
.PP
\fBudev_rules\fR
.RS 4
The name of the udev rules file or directory to look for files with the suffix
\fI.rules\fR. Multiple rule files are read in lexical order. The default value is
\fI/etc/udev/rules.d\fR.
.RE
.PP
\fBudev_log\fR
.RS 4
The logging priority. Valid values are the numerical syslog priorities or their textual representations:
\fBerr\fR,
\fBinfo\fR
and
\fBdebug\fR.
.RE
.SS "Rules files"
.PP
The udev rules are read from the files located in the
\fI/etc/udev/rules.d\fR
directory or at the location specified value in the configuration file. Every line in the rules file contains at least one key value pair. There are two kind of keys, match and assignment keys. If all match keys are matching against its value, the rule gets applied and the assign keys get the specified value assigned.
.PP
A matching rule may specify the name of the device node, add a symlink pointing to the node, or run a specified program as part of the event handling. If no matching rule is found, the default device node name is used.
.PP
A rule may consist of a list of one or more key value pairs separated by a comma. Each key has a distinct operation, depending on the used operator. Valid operators are:
.PP
\fB==\fR
.RS 4
Compare for equality.
.RE
.PP
\fB!=\fR
.RS 4
Compare for non\-equality.
.RE
.PP
\fB=\fR
.RS 4
Assign a value to a key. Keys that represent a list, are reset and only this single value is assigned.
.RE
.PP
\fB+=\fR
.RS 4
Add the value to a key that holds a list of entries.
.RE
.PP
\fB:=\fR
.RS 4
Assign a value to a key finally; disallow any later changes, which may be used to prevent changes by any later rules.
.RE
.PP
The following key names can be used to match against device properties. Some of the keys also match against properties of the parent devices in sysfs, not only the device that has generated the event. If multiple keys that match a parent device are specified in a single rule, all these keys must match at one and the same parent device.
.PP
\fBACTION\fR
.RS 4
Match the name of the event action.
.RE
.PP
\fBDEVPATH\fR
.RS 4
Match the devpath of the event device.
.RE
.PP
\fBKERNEL\fR
.RS 4
Match the name of the event device.
.RE
.PP
\fBSUBSYSTEM\fR
.RS 4
Match the subsystem of the event device.
.RE
.PP
\fBDRIVER\fR
.RS 4
Match the driver name of the event device. Only set for devices which are bound to a driver at the time the event is generated.
.RE
.PP
\fBATTR{\fR\fB\fIfilename\fR\fR\fB}\fR
.RS 4
Match sysfs attribute values of the event device. Up to five
\fBATTR\fR
keys can be specified per rule. Trailing whitespace in the attribute values is ignored, if the specified match value does not contain trailing whitespace itself. Depending on the type of operator, this key is also used to set the value of a sysfs attribute.
.RE
.PP
\fBKERNELS\fR
.RS 4
Search the devpath upwards for a matching device name.
.RE
.PP
\fBSUBSYSTEMS\fR
.RS 4
Search the devpath upwards for a matching device subsystem name.
.RE
.PP
\fBDRIVERS\fR
.RS 4
Search the devpath upwards for a matching device driver name.
.RE
.PP
\fBATTRS{\fR\fB\fIfilename\fR\fR\fB}\fR
.RS 4
Search the devpath upwards for a device with matching sysfs attribute values. Up to five
\fBATTRS\fR
keys can be specified per rule, but all of them must match on the same device. Trailing whitespace in the attribute values is ignored, if the specified match value does not contain trailing whitespace itself.
.RE
.PP
\fBENV{\fR\fB\fIkey\fR\fR\fB}\fR
.RS 4
Match against the value of an environment variable. Up to five
\fBENV\fR
keys can be specified per rule. Depending on the type of operator, this key is also used to export a variable to the environment.
.RE
.PP
\fBTEST{\fR\fB\fIoctal mode mask\fR\fR\fB}\fR
.RS 4
Test the existence of a file. An octal mode mask can be specified if needed.
.RE
.PP
\fBPROGRAM\fR
.RS 4
Execute external program. The key is true, if the program returns with exit code zero. The whole event environment is available to the executed program. The program's output printed to stdout, is available in the RESULT key.
.RE
.PP
\fBRESULT\fR
.RS 4
Match the returned string of the last PROGRAM call. This key can be used in the same or in any later rule after a PROGRAM call.
.RE
.PP
Most of the fields support a shell style pattern matching. The following pattern characters are supported:
.PP
\fB*\fR
.RS 4
Matches zero, or any number of characters.
.RE
.PP
\fB?\fR
.RS 4
Matches any single character.
.RE
.PP
\fB[]\fR
.RS 4
Matches any single character specified within the brackets. For example, the pattern string 'tty[SR]' would match either 'ttyS' or 'ttyR'. Ranges are also supported within this match with the '\-' character. For example, to match on the range of all digits, the pattern [0\-9] would be used. If the first character following the '[' is a '!', any characters not enclosed are matched.
.RE
.PP
The following keys can get values assigned:
.PP
\fBNAME\fR
.RS 4
The name of the node to be created, or the name the network interface should be renamed to. Only one rule can set the node name, all later rules with a NAME key will be ignored.
.RE
.PP
\fBSYMLINK\fR
.RS 4
The name of a symlink targeting the node. Every matching rule can add this value to the list of symlinks to be created along with the device node. Multiple symlinks may be specified by separating the names by the space character.
.RE
.PP
\fBOWNER, GROUP, MODE\fR
.RS 4
The permissions for the device node. Every specified value overwrites the compiled\-in default value.
.RE
.PP
\fBATTR{\fR\fB\fIkey\fR\fR\fB}\fR
.RS 4
The value that should be written to a sysfs attribute of the event device. Depending on the type of operator, this key is also used to match against the value of a sysfs attribute.
.RE
.PP
\fBENV{\fR\fB\fIkey\fR\fR\fB}\fR
.RS 4
Export a variable to the environment. Depending on the type of operator, this key is also to match against an environment variable.
.RE
.PP
\fBRUN\fR
.RS 4
Add a program to the list of programs to be executed for a specific device. This can only be used for very short running tasks. Running an event process for a long period of time may block all further events for this or a dependent device. Long running tasks need to be immediately detached from the event process itself.
.RE
.PP
\fBLABEL\fR
.RS 4
Named label where a GOTO can jump to.
.RE
.PP
\fBGOTO\fR
.RS 4
Jumps to the next LABEL with a matching name
.RE
.PP
\fBIMPORT{\fR\fB\fItype\fR\fR\fB}\fR
.RS 4
Import a set of variables into the event environment, depending on
\fItype\fR:
.RS 4
.PP
\fBprogram\fR
.RS 4
Execute an external program specified as the assigned value and import its output, which must be in environment key format.
.RE
.PP
\fBfile\fR
.RS 4
Import a text file specified as the assigned value, which must be in environment key format.
.RE
.PP
\fBparent\fR
.RS 4
Import the stored keys from the parent device by reading the database entry of the parent device. The value assigned to
\fBIMPORT{parent}\fR
is used as a filter of key names to import (with the same shell\-style pattern matching used for comparisons).
.RE
.RE
.IP "" 4
If no option is given, udev will choose between
\fBprogram\fR
and
\fBfile\fR
based on the executable bit of the file permissions.
.RE
.PP
\fBWAIT_FOR_SYSFS\fR
.RS 4
Wait for the specified sysfs file of the device to be created. Can be used to fight against kernel sysfs timing issues.
.RE
.PP
\fBOPTIONS\fR
.RS 4
Rule and device options:
.RS 4
.PP
\fBlast_rule\fR
.RS 4
Stops further rules application. No later rules will have any effect.
.RE
.PP
\fBignore_device\fR
.RS 4
Ignore this event completely.
.RE
.PP
\fBignore_remove\fR
.RS 4
Ignore any later remove event for this device. This may be useful as a workaround for broken device drivers.
.RE
.PP
\fBlink_priority=\fR\fB\fIvalue\fR\fR
.RS 4
Specify the priority of the created symlinks. Devices with higher priorities overwrite existing symlinks of other devices.
.RE
.PP
\fBall_partitions\fR
.RS 4
Create the device nodes for all available partitions of a block device. This may be useful for removable media devices where media changes are not detected.
.RE
.PP
\fBstring_escape=\fR\fB\fInone|replace\fR\fR
.RS 4
Usually control and other possibly unsafe characters are replaced in strings used for device naming. The mode of replacement can be specified with this option.
.RE
.RE
.RE
.PP
The
\fBNAME\fR,
\fBSYMLINK\fR,
\fBPROGRAM\fR,
\fBOWNER\fR,
\fBGROUP\fR
and
\fBRUN\fR
fields support simple printf\-like string substitutions. The
\fBRUN\fR
format chars gets applied after all rules have been processed, right before the program is executed. It allows the use of the complete environment set by earlier matching rules. For all other fields, substitutions are applied while the individual rule is being processed. The available substitutions are:
.PP
\fB$kernel\fR, \fB%k\fR
.RS 4
The kernel name for this device.
.RE
.PP
\fB$number\fR, \fB%n\fR
.RS 4
The kernel number for this device. For example, 'sda3' has kernel number of '3'
.RE
.PP
\fB$devpath\fR, \fB%p\fR
.RS 4
The devpath of the device.
.RE
.PP
\fB$id\fR, \fB%b\fR
.RS 4
The name of the device matched while searching the devpath upwards for
\fBSUBSYSTEMS\fR,
\fBKERNELS\fR,
\fBDRIVERS\fR
and
\fBATTRS\fR.
.RE
.PP
\fB$attr{\fR\fB\fIfile\fR\fR\fB}\fR, \fB%s{\fR\fB\fIfile\fR\fR\fB}\fR
.RS 4
The value of a sysfs attribute found at the device, where all keys of the rule have matched. If the matching device does not have such an attribute, all devices along the chain of parents are searched for a matching attribute. If the attribute is a symlink, the last element of the symlink target is returned as the value.
.RE
.PP
\fB$env{\fR\fB\fIkey\fR\fR\fB}\fR, \fB%E{\fR\fB\fIkey\fR\fR\fB}\fR
.RS 4
The value of an environment variable.
.RE
.PP
\fB$major\fR, \fB%M\fR
.RS 4
The kernel major number for the device.
.RE
.PP
\fB$minor\fR, \fB%m\fR
.RS 4
The kernel minor number for the device.
.RE
.PP
\fB$result\fR, \fB%c\fR
.RS 4
The string returned by the external program requested with PROGRAM. A single part of the string, separated by a space character may be selected by specifying the part number as an attribute:
\fB%c{N}\fR. If the number is followed by the '+' char this part plus all remaining parts of the result string are substituted:
\fB%c{N+}\fR
.RE
.PP
\fB$parent\fR, \fB%P\fR
.RS 4
The node name of the parent device.
.RE
.PP
\fB$root\fR, \fB%r\fR
.RS 4
The udev_root value.
.RE
.PP
\fB$sys\fR, \fB%S\fR
.RS 4
The sysfs mount point.
.RE
.PP
\fB$tempnode\fR, \fB%N\fR
.RS 4
The name of a created temporary device node to provide access to the device from a external program before the real node is created.
.RE
.PP
\fB%%\fR
.RS 4
The '%' character itself.
.RE
.PP
\fB$$\fR
.RS 4
The '$' character itself.
.RE
.PP
The count of characters to be substituted may be limited by specifying the format length value. For example, '%3s{file}' will only insert the first three characters of the sysfs attribute
.SH "AUTHOR"
.PP
Written by Greg Kroah\-Hartman
<greg@kroah.com>
and Kay Sievers
<kay.sievers@vrfy.org>. With much help from Dan Stekloff
<dsteklof@us.ibm.com>
and many others.
.SH "SEE ALSO"
.PP
\fBudevd\fR(8),
\fBudevinfo\fR(8),
\fBudevmonitor\fR(8)
