.\"     Title: udevtrigger
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: March 2006
.\"    Manual: udevtrigger
.\"    Source: udev
.\"
.TH "UDEVTRIGGER" "8" "March 2006" "udev" "udevtrigger"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevtrigger \- request kernel devices events for coldplug
.SH "SYNOPSIS"
.HP 12
\fBudevtrigger\fR [\fB\-\-verbose\fR] [\fB\-\-dry\-run\fR] [\fB\-\-retry\-failed\fR] [\fB\-\-help\fR] [\fB\-\-subsystem\-match=\fR\fB\fIsubsystem\fR\fR] [\fB\-\-subsystem\-nomatch=\fR\fB\fIsubsystem\fR\fR] [\fB\-\-attr\-match=\fR\fB\fIattribute=value\fR\fR] [\fB\-\-attr\-nomatch=\fR\fB\fIattribute=value\fR\fR]
.SH "DESCRIPTION"
.PP
Trigger kernel device uevents to replay missing events at system coldplug.
.SH "OPTIONS"
.PP
\fB\-\-verbose\fR
.RS 4
Print the list of devices which will be triggered.
.RE
.PP
\fB\-\-dry\-run\fR
.RS 4
Do not actually trigger the event.
.RE
.PP
\fB\-\-retry\-failed\fR
.RS 4
Trigger only the events which are failed during a previous run.
.RE
.PP
\fB\-\-subsystem\-match=\fR\fB\fIsubsystem\fR\fR
.RS 4
Trigger events for devices which belong to a matching subsystem. This option can be specified multiple times and supports shell style pattern matching.
.RE
.PP
\fB\-\-subsystem\-nomatch=\fR\fB\fIsubsystem\fR\fR
.RS 4
Do not trigger events for devices which belong to a matching subsystem. This option can be specified multiple times and supports shell style pattern matching.
.RE
.PP
\fB\-\-attr\-match=\fR\fB\fIattribute=value\fR\fR
.RS 4
Trigger events for devices with a matching sysfs attribute. If a value is specified along with the attribute name, the content of the attribute is matched against the given value using shell style pattern matching. If no value is specified, the existence of the sysfs attribute is checked. This option can be specified multiple times.
.RE
.PP
\fB\-\-attr\-nomatch\fR\fB\fIattribute=value\fR\fR
.RS 4
Do not trigger events for devices with a matching sysfs attribute. If a value is specified along with the attribute name, the content of the attribute is matched against the given value using shell style pattern matching. If no value is specified, the existence of the sysfs attribute is checked. This option can be specified multiple times.
.RE
.SH "ENVIRONMENT"
.PP
\fBUDEV_LOG\fR
.RS 4
Overrides the syslog priority specified in the config file.
.RE
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay.sievers@vrfy.org>
and Hannes Reinecke
<hare@suse.de>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
