.\"     Title: udevd
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: August 2005
.\"    Manual: udevd
.\"    Source: udev
.\"
.TH "UDEVD" "8" "August 2005" "udev" "udevd"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevd - event managing daemon
.SH "SYNOPSIS"
.HP 6
\fBudevd\fR [\fB\-\-daemon\fR] [\fB\-\-debug\-trace\fR] [\fB\-\-verbose\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.SH "DESCRIPTION"
.PP
udevd listens to kernel uevents and passes the incoming events to udev\. It ensures the correct event order and takes care, that events for child devices are delayed until the parent event has finished the device handling\. The behavior of the running daemon can be changed with
\fBudevadm control\fR\.
.SH "OPTIONS"
.PP
\fB\-\-daemon\fR
.RS 4
Detach and run in the background\.
.RE
.PP
\fB\-\-debug\-trace\fR
.RS 4
Run all events completely serialized\. This may be useful if udev triggers actions or loads kernel modules which cause problems and a slow but continuous operation is needed, where no events are processed in parallel\.
.RE
.PP
\fB\-\-verbose\fR
.RS 4
Print log messages to stdout\.
.RE
.PP
\fB\-\-version\fR
.RS 4
Print version number\.
.RE
.PP
\fBhelp\fR
.RS 4
Print help text\.
.RE
.SH "ENVIRONMENT"
.PP
\fBUDEV_LOG\fR
.RS 4
Overrides the syslog priority specified in the config file\.
.RE
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay\.sievers@vrfy\.org>\.
.SH "SEE ALSO"
.PP
\fBudev\fR(8),
\fBudevadm\fR(8)
