.TH UDEVINFO 8 "January 2004" "" "Linux Administrator's Manual"
.SH NAME
udevinfo \- retrieve information from udev
.SH SYNOPSIS
.B udevinfo
.RI "[\-q " query_type " \-p " sysfs_path "] [\-drVh]"
.SH "DESCRIPTION"
.B udevinfo
allows users to query the udev database for information on any device
currently present on the system.  It also provides a way to query any device
in the sysfs tree to help creating
.B udev
rules.
.SH "OPTIONS"
.TP
.B \-V
Print the version information.
.TP
.B \-r
Print the
.B udev_root
directory. When used in conjunction with a query for the node name, the
.B udev_root
will be prepended.
.TP
.BI \-q " query_type"
Query the database for specified value of a created device node or network
interface.
.RB Needs " \-p " or " \-n " specified.
.br
Valid types are:
.BR name ", " symlink ", " mode " ," owner " , " group " , " path " or " all.
.TP
.BI \-p " sysfs_path"
Specify the sysfs path of the device to query.
.TP
.BI \-n " name"
Specify the name of the node, the symlink or the network interface for the
device to query. Partition names generated with the NAME{all_partitons} option
can not be queried, the main device must be used instead.
.TP
.B \-a
Print all
.BI SYSFS{ filename }
attributes along the device chain. Useful for finding
unique attributes to compose a rule.
.RB Needs " \-p " specified.
.TP
.B \-d
Dump the whole database.
.TP
.B \-h
Print help text.
.SH "FILES"
.nf
/etc/udev/*  udev config files
.fi
.LP
.SH "SEE ALSO"
.BR udev (8)
.SH AUTHORS
.B udevinfo
was developed primarily by Kay Sievers <kay.sievers@vrfy.org>, with help
from others.
