.\"     Title: udevsettle
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: March 2006
.\"    Manual: udevsettle
.\"    Source: udev
.\"
.TH "UDEVSETTLE" "8" "March 2006" "udev" "udevsettle"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevsettle \- wait until queued kernel/udev events are handled
.SH "SYNOPSIS"
.HP 11
\fBudevsettle\fR [\fB\-\-timeout=\fR\fB\fIseconds\fR\fR]
.SH "DESCRIPTION"
.PP
Waits watching the udev event queue and exits if all current events are handled.
.SH "OPTIONS"
.PP
\fB\-\-timeout=\fR\fB\fIseconds\fR\fR
.RS 4
maximum seconds to wait for the queue to become empty.
.RE
.SH "ENVIRONMENT"
.PP
\fBUDEV_LOG\fR
.RS 4
Overrides the syslog priority specified in the config file.
.RE
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay.sievers@vrfy.org>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
