.TH UDEVTEST 8 "March 2004" "" "Linux Administrator's Manual"
.SH NAME
udevtest \- simulates a udev run to test the configured rules
.SH SYNOPSIS
.B udevtest
.I sysfs_device_path subsystem
.SH "DESCRIPTION"
.B udevtest
simulates a
.B udev
run for the given device, and prints out the name of the node
the real udev would have created, or the name of the renamed network
interface.
.SH "SEE ALSO"
.BR udev (8)
.SH AUTHORS
.B udevtest
was developed by Greg Kroah-Hartman <greg@kroah.com> with much help
from others.
