.TH UDEV 8 "October 2003" "" "Linux Programmer's Manual"
.SH NAME
udev \- Linux dynamic device naming support
.SH SYNOPSIS
.B udev
.SH "DESCRIPTION"
.B udev
is a wonderful program whose man page has not been written yet.
.SH "FILES"
.nf
.ft B
.ft
/sbin/udev                           udev program
/etc/udev/*                          udev config and database files
/etc/hotplug.d/default/udev.hotplug  hotplug symlink to udev program
.fi
.LP
.SH "SEE ALSO"
.BR hotplug "(8)"
.PP
The
.I http://linux-hotplug.sourceforge.net/
web site.
.SH AUTHORS
udev was developed by Greg Kroah-Hartman <greg@kroah.com> with much help from
Dan Stekloff <dsteklof@us.ibm.com> and many others.
