.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "UDEVTRIGGER" "8" "March 2006" "udev" "udevtrigger"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevtrigger \- request kernel devices events for coldplug
.SH "SYNOPSIS"
.HP 12
\fBudevtrigger\fR [\fB\-\-verbose\fR] [\fB\-\-dry\-run\fR]
.SH "DESCRIPTION"
.PP
Trigger kernel device uevents to replay missing events at system coldplug.
.SH "OPTIONS"
.TP
\fB\-\-verbose\fR
print out the devices found in sysfs.
.TP
\fB\-\-dry\-run\fR
don't actually trigger the event.
.SH "ENVIRONMENT"
.TP
\fBUDEV_LOG\fR
Overrides the syslog priority specified in the config file.
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay.sievers@vrfy.org>
and Hannes Reinecke
<hare@suse.de>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
