.\"     Title: udevtrigger
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.70.1 <http://docbook.sf.net/>
.\"      Date: March 2006
.\"    Manual: udevtrigger
.\"    Source: udev
.\"
.TH "UDEVTRIGGER" "8" "March 2006" "udev" "udevtrigger"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevtrigger \- request kernel devices events for coldplug
.SH "SYNOPSIS"
.HP 12
\fBudevtrigger\fR [\fB\-\-verbose\fR] [\fB\-\-dry\-run\fR]
.SH "DESCRIPTION"
.PP
Trigger kernel device uevents to replay missing events at system coldplug.
.SH "OPTIONS"
.TP 3n
\fB\-\-verbose\fR
print out the devices found in sysfs.
.TP 3n
\fB\-\-dry\-run\fR
don't actually trigger the event.
.SH "ENVIRONMENT"
.TP 3n
\fBUDEV_LOG\fR
Overrides the syslog priority specified in the config file.
.SH "AUTHOR"
.PP
Written by Kay Sievers
<kay.sievers@vrfy.org>
and Hannes Reinecke
<hare@suse.de>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
