.\"     Title: udevstart
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.72.0 <http://docbook.sf.net/>
.\"      Date: August 2005
.\"    Manual: udevstart
.\"    Source: udev
.\"
.TH "UDEVSTART" "8" "August 2005" "udev" "udevstart"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
udevstart \- populate initial device directory
.SH "SYNOPSIS"
.HP 10
\fBudevstart\fR
.SH "DESCRIPTION"
.PP
udevstart scans the kernel exported device information available in sysfs for devices which require a device node to operate and creates the node using the specified udev rules. udevstart is used to create the initial device directory after system bootup.
.SH "AUTHOR"
.PP
Written by Harald Hoyer
<harald@redhat.com>.
.SH "SEE ALSO"
.PP
\fBudev\fR(7)
