# SPDX-License-Identifier: LGPL-2.1-or-later
# avoid pulling in the uutils package which is the default and is broken in several ways

[TriggerMatch]
Distribution=ubuntu
Release=!jammy
Release=!noble

[Content]
Packages=
        coreutils-from-gnu
        coreutils-from-uutils-
        rust-coreutils-
