/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include <fcntl.h>

#include "sd-device.h"
#include "sd-varlink.h"

#include "alloc-util.h"
#include "device-private.h"
#include "device-util.h"
#include "fd-util.h"
#include "log.h"
#include "metrics.h"
#include "path-util.h"
#include "report-diskhealth.h"
#include "report-diskhealth-ata.h"
#include "report-diskhealth-nvme.h"
#include "string-util.h"
#include "strv.h"
#include "udev-util.h"
#include "virt.h"

typedef enum DiskHealthMetric {
        DISK_HEALTH_METRIC_ATA_OFFLINE_UNCORRECTABLE,
        DISK_HEALTH_METRIC_ATA_PENDING_SECTORS,
        DISK_HEALTH_METRIC_ATA_REALLOCATED_SECTORS,
        DISK_HEALTH_METRIC_ATA_SMART_STATUS_FAILING,
        DISK_HEALTH_METRIC_DISK_LOGICAL_SECTOR_SIZE_BYTES,
        DISK_HEALTH_METRIC_DISK_MODEL,
        DISK_HEALTH_METRIC_DISK_PHYSICAL_SECTOR_SIZE_BYTES,
        DISK_HEALTH_METRIC_DISK_POWER_CYCLES,
        DISK_HEALTH_METRIC_DISK_POWER_ON_HOURS,
        DISK_HEALTH_METRIC_DISK_SERIAL,
        DISK_HEALTH_METRIC_DISK_SIZE_BYTES,
        DISK_HEALTH_METRIC_DISK_VENDOR,
        DISK_HEALTH_METRIC_NVME_AVAILABLE_SPARE_PERCENT,
        DISK_HEALTH_METRIC_NVME_CRITICAL_WARNING,
        DISK_HEALTH_METRIC_NVME_MEDIA_ERRORS,
        DISK_HEALTH_METRIC_NVME_PERCENTAGE_USED,
        _DISK_HEALTH_METRIC_MAX,
} DiskHealthMetric;

static int disk_health_generate(const MetricFamily *mf, sd_varlink *link, void *userdata);

static const MetricFamily disk_health_metric_family_table[_DISK_HEALTH_METRIC_MAX + 1] = {
        /* Keep metrics ordered alphabetically. All metrics are generated by the first entry, so that each
         * disk is queried only once per call. */
        [DISK_HEALTH_METRIC_ATA_OFFLINE_UNCORRECTABLE] = {
                "io.systemd.DiskHealth.ATAOfflineUncorrectable",
                "Per ATA disk metric: number of uncorrectable sectors found during offline scans (SMART attribute 198)",
                METRIC_FAMILY_TYPE_GAUGE,
                .generate = disk_health_generate,
        },
        [DISK_HEALTH_METRIC_ATA_PENDING_SECTORS] = {
                "io.systemd.DiskHealth.ATAPendingSectors",
                "Per ATA disk metric: number of unstable sectors waiting to be remapped (SMART attribute 197)",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_ATA_REALLOCATED_SECTORS] = {
                "io.systemd.DiskHealth.ATAReallocatedSectors",
                "Per ATA disk metric: number of sectors remapped to spare area (SMART attribute 5)",
                METRIC_FAMILY_TYPE_COUNTER,
        },
        [DISK_HEALTH_METRIC_ATA_SMART_STATUS_FAILING] = {
                "io.systemd.DiskHealth.ATASmartStatusFailing",
                "Per ATA disk metric: 1 if the disk's overall SMART status reports a threshold exceeded, 0 otherwise",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_DISK_LOGICAL_SECTOR_SIZE_BYTES] = {
                "io.systemd.DiskHealth.DiskLogicalSectorSizeBytes",
                "Per disk metric: logical sector size in bytes",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_DISK_MODEL] = {
                "io.systemd.DiskHealth.DiskModel",
                "Per disk metric: model name",
                METRIC_FAMILY_TYPE_STRING,
        },
        [DISK_HEALTH_METRIC_DISK_PHYSICAL_SECTOR_SIZE_BYTES] = {
                "io.systemd.DiskHealth.DiskPhysicalSectorSizeBytes",
                "Per disk metric: physical sector size in bytes",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_DISK_POWER_CYCLES] = {
                "io.systemd.DiskHealth.DiskPowerCycles",
                "Per NVMe or ATA disk metric: number of power cycles over the disk's lifetime",
                METRIC_FAMILY_TYPE_COUNTER,
        },
        [DISK_HEALTH_METRIC_DISK_POWER_ON_HOURS] = {
                "io.systemd.DiskHealth.DiskPowerOnHours",
                "Per NVMe or ATA disk metric: number of hours the disk has been powered on over its lifetime",
                METRIC_FAMILY_TYPE_COUNTER,
        },
        [DISK_HEALTH_METRIC_DISK_SERIAL] = {
                "io.systemd.DiskHealth.DiskSerial",
                "Per disk metric: serial number",
                METRIC_FAMILY_TYPE_STRING,
        },
        [DISK_HEALTH_METRIC_DISK_SIZE_BYTES] = {
                "io.systemd.DiskHealth.DiskSizeBytes",
                "Per disk metric: size in bytes",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_DISK_VENDOR] = {
                "io.systemd.DiskHealth.DiskVendor",
                "Per disk metric: vendor name",
                METRIC_FAMILY_TYPE_STRING,
        },
        [DISK_HEALTH_METRIC_NVME_AVAILABLE_SPARE_PERCENT] = {
                "io.systemd.DiskHealth.NVMeAvailableSparePercent",
                "Per NVMe disk metric: remaining spare capacity in percent",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_NVME_CRITICAL_WARNING] = {
                "io.systemd.DiskHealth.NVMeCriticalWarning",
                "Per NVMe disk metric: critical warning bitmask, 0 if all is well",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        [DISK_HEALTH_METRIC_NVME_MEDIA_ERRORS] = {
                "io.systemd.DiskHealth.NVMeMediaErrors",
                "Per NVMe disk metric: number of unrecovered data integrity errors",
                METRIC_FAMILY_TYPE_COUNTER,
        },
        [DISK_HEALTH_METRIC_NVME_PERCENTAGE_USED] = {
                "io.systemd.DiskHealth.NVMePercentageUsed",
                "Per NVMe disk metric: vendor estimate of the used up life time in percent, may exceed 100",
                METRIC_FAMILY_TYPE_GAUGE,
        },
        {}
};

static int disk_is_hardware(sd_device *device) {
        const char *devpath;
        int r;

        assert(device);

        r = sd_device_get_devpath(device, &devpath);
        if (r < 0)
                return r;

        if (!path_startswith(devpath, "/devices/virtual/"))
                return true;

        /* With native NVMe multipath the namespace block device sits below the (virtual) NVMe subsystem
         * device rather than below the controller, but it is backed by real hardware nonetheless. */
        r = sd_device_get_parent_with_subsystem_devtype(device, "nvme-subsystem", /* devtype= */ NULL, /* ret= */ NULL);
        if (r == -ENOENT)
                return false;
        if (r < 0)
                return r;

        return true;
}

static int disk_is_nvme(sd_device *device) {
        int r;

        assert(device);

        FOREACH_STRING(subsystem, "nvme", "nvme-subsystem") {
                r = sd_device_get_parent_with_subsystem_devtype(device, subsystem, /* devtype= */ NULL, /* ret= */ NULL);
                if (r >= 0)
                        return true;
                if (r != -ENOENT)
                        return r;
        }

        return false;
}

static int disk_is_ata(sd_device *device) {
        int r;

        assert(device);

        /* Set by ata_id, which also skips drives on which SMART is disabled. */
        r = device_get_property_bool(device, "ID_ATA_FEATURE_SET_SMART_ENABLED");
        if (r == -ENOENT)
                return false;
        if (r <= 0)
                return r;

        /* ata_id is also run on SATA disks in USB enclosures, but the quality of the USB bridges' SAT
         * implementations varies, and we better not send them anything they might choke on. */
        r = sd_device_get_parent_with_subsystem_devtype(device, "usb", /* devtype= */ NULL, /* ret= */ NULL);
        if (r >= 0)
                return false;
        if (r != -ENOENT)
                return r;

        sd_device *scsi;
        r = sd_device_get_parent_with_subsystem_devtype(device, "scsi", "scsi_device", &scsi);
        if (r == -ENOENT)
                return false;
        if (r < 0)
                return r;

        const char *vendor;
        r = sd_device_get_sysattr_value(scsi, "vendor", &vendor);
        if (r == -ENOENT)
                return false;
        if (r < 0)
                return r;

        /* libata reports "ATA" as SCSI vendor, padded with spaces */
        const char *e = startswith(vendor, "ATA");
        return e && isempty(skip_leading_chars(e, WHITESPACE));
}

static int disk_get_nvme_controller(sd_device *device, sd_device **ret) {
        const char *sysname, *e;
        sd_device *nvme;
        int r;

        assert(device);
        assert(ret);

        r = sd_device_get_parent_with_subsystem_devtype(device, "nvme", /* devtype= */ NULL, &nvme);
        if (r >= 0) {
                *ret = sd_device_ref(nvme);
                return 0;
        }
        if (r != -ENOENT)
                return r;

        r = sd_device_get_parent_with_subsystem_devtype(device, "nvme-subsystem", /* devtype= */ NULL, /* ret= */ NULL);
        if (r < 0)
                return r;

        /* With native NVMe multipath the namespace head block device sits below the NVMe subsystem rather
         * than below a controller. Its sysname is nvme%dn%d, where the first number is the instance of the
         * controller the subsystem was created for, hence look up the controller by that, the same way as
         * path_id does it. */
        r = sd_device_get_sysname(device, &sysname);
        if (r < 0)
                return r;

        e = startswith(sysname, "nvme");
        if (!e)
                return -ENOENT;
        e += strspn(e, DIGITS);

        _cleanup_free_ char *name = strndup(sysname, e - sysname);
        if (!name)
                return -ENOMEM;

        return sd_device_new_from_subsystem_sysname(ret, "nvme", name);
}

static int disk_get_hardware_parent(sd_device *device, sd_device **ret) {
        _cleanup_(sd_device_unrefp) sd_device *nvme = NULL;
        sd_device *parent;
        int r;

        assert(device);
        assert(ret);

        /* Returns the device representing the physical disk (or its enclosure) on the bus, from which we can
         * take vendor and model information from the hwdb, if the block device itself carries none. */

        r = sd_device_get_parent_with_subsystem_devtype(device, "usb", "usb_device", &parent);
        if (r >= 0) {
                *ret = sd_device_ref(parent);
                return 0;
        }
        if (r != -ENOENT)
                return r;

        r = disk_get_nvme_controller(device, &nvme);
        if (r < 0)
                return r;

        r = sd_device_get_parent_with_subsystem_devtype(nvme, "pci", /* devtype= */ NULL, &parent);
        if (r < 0)
                return r;

        *ret = sd_device_ref(parent);
        return 0;
}

static const char* disk_get_string(
                sd_device *device,
                sd_device *parent,
                int (*getter)(sd_device *device, const char **ret)) {

        const char *s;

        assert(device);
        assert(getter);

        if (getter(device, &s) >= 0 && !isempty(s))
                return s;

        if (parent && getter(parent, &s) >= 0 && !isempty(s))
                return s;

        return NULL;
}

static const char* disk_get_serial(sd_device *device) {
        const char *s;

        assert(device);

        FOREACH_STRING(property, "ID_SERIAL_SHORT", "ID_SERIAL")
                if (sd_device_get_property_value(device, property, &s) >= 0 && !isempty(s))
                        return s;

        return NULL;
}

static void disk_read_sysattr_u64(sd_device *device, const char *sysattr, uint64_t *ret) {
        int r;

        assert(device);
        assert(sysattr);
        assert(ret);

        r = device_get_sysattr_u64(device, sysattr, ret);
        if (r < 0) {
                log_device_debug_errno(device, r, "Failed to read '%s' attribute, ignoring: %m", sysattr);
                *ret = UINT64_MAX;
        }
}

static void disk_read_health(sd_device *device, uint64_t values[static _DISK_HEALTH_METRIC_MAX]) {
        int nvme, r;

        assert(device);
        assert(values);

        nvme = disk_is_nvme(device);
        if (nvme < 0)
                return (void) log_device_debug_errno(device, nvme, "Failed to determine whether disk is an NVMe disk, ignoring: %m");

        if (!nvme) {
                int ata = disk_is_ata(device);
                if (ata < 0)
                        return (void) log_device_debug_errno(device, ata, "Failed to determine whether disk is an ATA disk, ignoring: %m");
                if (!ata)
                        return;
        }

        _cleanup_close_ int fd = sd_device_open(device, O_RDONLY|O_CLOEXEC|O_NONBLOCK|O_NOCTTY);
        if (fd < 0)
                return (void) log_device_debug_errno(device, fd, "Failed to open disk, ignoring: %m");

        if (nvme) {
                NVMeHealth h;

                r = nvme_read_health(fd, &h);
                if (r < 0)
                        return (void) log_device_debug_errno(device, r, "Failed to read NVMe health information, ignoring: %m");

                values[DISK_HEALTH_METRIC_NVME_AVAILABLE_SPARE_PERCENT] = h.available_spare;
                values[DISK_HEALTH_METRIC_NVME_CRITICAL_WARNING] = h.critical_warning;
                values[DISK_HEALTH_METRIC_NVME_MEDIA_ERRORS] = h.media_errors;
                values[DISK_HEALTH_METRIC_NVME_PERCENTAGE_USED] = h.percentage_used;
                values[DISK_HEALTH_METRIC_DISK_POWER_CYCLES] = h.power_cycles;
                values[DISK_HEALTH_METRIC_DISK_POWER_ON_HOURS] = h.power_on_hours;
        } else {
                ATAHealth h;

                r = ata_read_health(fd, &h);
                if (r < 0)
                        return (void) log_device_debug_errno(device, r, "Failed to read ATA health information, ignoring: %m");
                if (r == 0)
                        return (void) log_device_debug(device, "Disk is in standby mode, not querying health data.");

                values[DISK_HEALTH_METRIC_ATA_OFFLINE_UNCORRECTABLE] = h.offline_uncorrectable;
                values[DISK_HEALTH_METRIC_ATA_PENDING_SECTORS] = h.pending_sectors;
                values[DISK_HEALTH_METRIC_ATA_REALLOCATED_SECTORS] = h.reallocated_sectors;
                if (h.smart_failing >= 0)
                        values[DISK_HEALTH_METRIC_ATA_SMART_STATUS_FAILING] = h.smart_failing;
                values[DISK_HEALTH_METRIC_DISK_POWER_CYCLES] = h.power_cycles;
                values[DISK_HEALTH_METRIC_DISK_POWER_ON_HOURS] = h.power_on_hours;
        }
}

static int disk_send(sd_varlink *link, sd_device *device) {
        const char *object;
        uint64_t size;
        int r;

        assert(link);
        assert(device);

        /* This skips the hidden per-path block devices of multipath NVMe namespaces, which have no device
         * node. */
        r = sd_device_get_devname(device, &object);
        if (r == -ENOENT)
                return 0;
        if (r < 0) {
                log_device_debug_errno(device, r, "Failed to get device node, ignoring: %m");
                return 0;
        }

        r = disk_is_hardware(device);
        if (r < 0) {
                log_device_debug_errno(device, r, "Failed to determine whether disk is backed by hardware, ignoring: %m");
                return 0;
        }
        if (r == 0)
                return 0;

        /* Skip drives without medium. Note that the 'size' attribute is always in 512 byte units. */
        r = device_get_sysattr_u64(device, "size", &size);
        if (r < 0) {
                log_device_debug_errno(device, r, "Failed to read disk size, ignoring: %m");
                return 0;
        }
        if (size == 0)
                return 0;
        if (!MUL_ASSIGN_SAFE(&size, 512)) {
                log_device_debug_errno(device, SYNTHETIC_ERRNO(EOVERFLOW), "Disk size out of range, ignoring.");
                return 0;
        }

        uint64_t values[_DISK_HEALTH_METRIC_MAX];
        FOREACH_ELEMENT(v, values)
                *v = UINT64_MAX;
        const char *strings[_DISK_HEALTH_METRIC_MAX] = {};

        values[DISK_HEALTH_METRIC_DISK_SIZE_BYTES] = size;
        disk_read_sysattr_u64(device, "queue/logical_block_size", values + DISK_HEALTH_METRIC_DISK_LOGICAL_SECTOR_SIZE_BYTES);
        disk_read_sysattr_u64(device, "queue/physical_block_size", values + DISK_HEALTH_METRIC_DISK_PHYSICAL_SECTOR_SIZE_BYTES);

        /* Prefer the information from the block device itself, and only fall back to the device on the bus
         * if there is none. In both cases the device_get_{model,vendor}_string() helpers prefer the hwdb
         * information over the one the device reports about itself. */
        _cleanup_(sd_device_unrefp) sd_device *parent = NULL;
        r = disk_get_hardware_parent(device, &parent);
        if (r < 0 && r != -ENOENT)
                log_device_debug_errno(device, r, "Failed to find hardware parent device, ignoring: %m");

        strings[DISK_HEALTH_METRIC_DISK_MODEL] = disk_get_string(device, parent, device_get_model_string);
        strings[DISK_HEALTH_METRIC_DISK_VENDOR] = disk_get_string(device, parent, device_get_vendor_string);
        strings[DISK_HEALTH_METRIC_DISK_SERIAL] = disk_get_serial(device);

        disk_read_health(device, values);

        for (DiskHealthMetric m = 0; m < _DISK_HEALTH_METRIC_MAX; m++) {
                const MetricFamily *mf = disk_health_metric_family_table + m;

                if (mf->type == METRIC_FAMILY_TYPE_STRING) {
                        if (!strings[m])
                                continue;

                        r = metric_build_send_string(mf, link, object, strings[m], /* fields= */ NULL);
                } else {
                        if (values[m] == UINT64_MAX)
                                continue;

                        r = metric_build_send_unsigned(mf, link, object, values[m], /* fields= */ NULL);
                }
                if (r < 0)
                        return r;
        }

        return 0;
}

static int disk_health_generate(const MetricFamily *mf, sd_varlink *link, void *userdata) {
        int r;

        assert(mf);
        assert(link);

        /* Disks are hardware the host manages, not something specific to the systems down the container
         * tree, hence let's not generate the metrics here, even if accessible. */
        if (detect_container() > 0)
                return 0;

        /* Note that a fresh enumerator (and hence fresh sd_device objects) is used for each call, so that
         * the sysattr cache in sd-device never hands out stale data. Uninitialized devices are skipped by
         * the enumerator, as we need the udev database for the model, vendor and serial information, and
         * to identify ATA disks with SMART enabled. */
        _cleanup_(sd_device_enumerator_unrefp) sd_device_enumerator *e = NULL;
        r = sd_device_enumerator_new(&e);
        if (r < 0)
                return log_error_errno(r, "Failed to allocate device enumerator: %m");

        r = sd_device_enumerator_add_match_subsystem(e, "block", /* match= */ true);
        if (r < 0)
                return log_error_errno(r, "Failed to add block subsystem match to enumerator: %m");

        r = sd_device_enumerator_add_match_property(e, "DEVTYPE", "disk");
        if (r < 0)
                return log_error_errno(r, "Failed to add DEVTYPE match to enumerator: %m");

        FOREACH_DEVICE(e, device) {
                r = disk_send(link, device);
                if (r < 0)
                        return r;
        }

        return 0;
}

int vl_method_describe_metrics(sd_varlink *link, sd_json_variant *parameters, sd_varlink_method_flags_t flags, void *userdata) {
        return metrics_method_describe(disk_health_metric_family_table, link, parameters, flags, userdata);
}

int vl_method_list_metrics(sd_varlink *link, sd_json_variant *parameters, sd_varlink_method_flags_t flags, void *userdata) {
        return metrics_method_list(disk_health_metric_family_table, link, parameters, flags, userdata);
}
