/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include <unistd.h>

#include "sd-json.h"
#include "sd-varlink.h"

#include "alloc-util.h"
#include "build.h"
#include "dirent-util.h"
#include "dlopen-note.h"
#include "fd-util.h"
#include "fileio.h"
#include "fs-util.h"
#include "iovec-util.h"
#include "json-util.h"
#include "log.h"
#include "main-func.h"
#include "options.h"
#include "path-util.h"
#include "string-table.h"
#include "string-util.h"
#include "strv.h"
#include "tmpfile-util.h"
#include "tpm2-pcr.h"
#include "tpm2-report.h"
#include "tpm2-util.h"
#include "varlink-io.systemd.Report.Signer.h"
#include "varlink-io.systemd.Report.TPM2SignerKeyManager.h"
#include "varlink-util.h"
#include "verbs.h"

COMMAND(
        "systemd-report-sign-tpm2\0",
        "Get an attestation report from a Trusted Platform Module (TPM) "
        "that includes the hash of the system report.",
        .man_pages = "systemd-report-sign-tpm2@.service(8)\0",
);

#define REPORT_SIGN_TPM2_PERSISTENT_DIR "/var/lib/systemd/report.sign.tpm2"
#define REPORT_SIGN_TPM2_RUNTIME_DIR "/run/systemd/report.sign.tpm2"

#define REPORT_SIGN_TPM2_KEY_DEFAULT_NAME "default"

/* Files containing the TPM signing key data. */
#define REPORT_SIGN_TPM2_KEY_EXT ".key"

/* Files containing an optional voucher for a signing key. The voucher is some credential optionally
 * issued as part of onboarding in order to certify the corresponding attestation key, and which is attached
 * to the report signature. It's intentionally not "certificate" as we don't prescribe that it has to be a
 * X.509 certificate - it's entirely opaque to us and an implementation detail of whatever platform we
 * onboard with. It's also not "cred" or "credential" because those terms already have other meanings in
 * systemd. */
#define REPORT_SIGN_TPM2_VOUCHER_EXT ".voucher"

/* Files containing a saved TPM key context. The context contains the TPM context blob generated by
 * TPM2_ContextSave, and is persisted between signing invocations for ordinary and primary signing keys.
 * This avoids having to recreate primary keys, or reload ordinary keys (which requires authorization
 * with the parent storage key, and which requires a policy session in some circumstances. */
#define REPORT_SIGN_TPM2_KEYCONTEXT_EXT ".context"

typedef struct SignRequestParameters {
        struct iovec digest;
        const char *algorithm;
} SignRequestParameters;

static void sign_request_parameters_done(SignRequestParameters *p) {
        assert(p);

        iovec_done(&p->digest);
        p->algorithm = NULL;
}

static int make_default_report_options(Tpm2ReportOptions *ret) {
        int r;

        assert(ret);

        /* Include all NvPCRs. */
        _cleanup_strv_free_ char **nv_pcrs = NULL;
        r = tpm2_nvpcr_all_names(&nv_pcrs);
        if (r < 0)
                return log_error_errno(r, "Failed to obtain all NvPCR names");

        /* Include all firmware PCRs except 6, and all on the "Linux TPM PCR Registry"
         * except for the IMA PCR as we're not including the log for that. */
        static const uint32_t pcr_mask =
                (UINT32_C(1) << TPM2_PCR_PLATFORM_CODE) |
                (UINT32_C(1) << TPM2_PCR_PLATFORM_CONFIG) |
                (UINT32_C(1) << TPM2_PCR_EXTERNAL_CODE) |
                (UINT32_C(1) << TPM2_PCR_EXTERNAL_CONFIG) |
                (UINT32_C(1) << TPM2_PCR_BOOT_LOADER_CODE) |
                (UINT32_C(1) << TPM2_PCR_BOOT_LOADER_CONFIG) |
                (UINT32_C(1) << TPM2_PCR_SECURE_BOOT_POLICY) |
                (UINT32_C(1) << TPM2_PCR_KERNEL_INITRD) |
                (UINT32_C(1) << TPM2_PCR_KERNEL_BOOT) |
                (UINT32_C(1) << TPM2_PCR_KERNEL_CONFIG) |
                (UINT32_C(1) << TPM2_PCR_SYSEXTS) |
                (UINT32_C(1) << TPM2_PCR_SHIM_POLICY) |
                (UINT32_C(1) << TPM2_PCR_SYSTEM_IDENTITY);

        *ret = (Tpm2ReportOptions) {
                .pcr_mask = pcr_mask,
                .nv_pcrs = TAKE_PTR(nv_pcrs),
        };
        return 0;
}

typedef enum SigningKeyType {
        SIGNING_KEY_ORDINARY,
        SIGNING_KEY_PERSISTENT,
        SIGNING_KEY_PRIMARY,

        _SIGNING_KEY_TYPE_MAX,
        _SIGNING_KEY_TYPE_INVALID = -EINVAL,
} SigningKeyType;

static const char* const signing_key_type_table[_SIGNING_KEY_TYPE_MAX] = {
        [SIGNING_KEY_ORDINARY]   = "ordinary",
        [SIGNING_KEY_PERSISTENT] = "persistent",
        [SIGNING_KEY_PRIMARY]    = "primary",
};
DEFINE_PRIVATE_STRING_TABLE_LOOKUP(signing_key_type, SigningKeyType);
static JSON_DISPATCH_ENUM_DEFINE(json_dispatch_signing_key_type, SigningKeyType, signing_key_type_from_string);

typedef enum SigningKeyHierarchy {
        SIGNING_KEY_HIERARCHY_OWNER,
        SIGNING_KEY_HIERARCHY_ENDORSEMENT,

        _SIGNING_KEY_HIERARCHY_MAX,
        _SIGNING_KEY_HIERARCHY_INVALID = -EINVAL,
} SigningKeyHierarchy;

static const char* const signing_key_hierarchy_table[_SIGNING_KEY_HIERARCHY_MAX] = {
        [SIGNING_KEY_HIERARCHY_OWNER]       = "owner",
        [SIGNING_KEY_HIERARCHY_ENDORSEMENT] = "endorsement",
};
DEFINE_PRIVATE_STRING_TABLE_LOOKUP(signing_key_hierarchy, SigningKeyHierarchy);
static JSON_DISPATCH_ENUM_DEFINE(json_dispatch_signing_key_hierarchy, SigningKeyHierarchy, signing_key_hierarchy_from_string);

/* SigningKeyData represents the stored data corresponding to a TPM signing key. */
typedef struct SigningKeyData {
        SigningKeyType type;

        struct iovec parent_handle;    /* Persistent handle for the parent of ordinary keys */
        struct iovec public;           /* Public area of ordinary keys */
        struct iovec private;          /* Private area of ordinary keys */

        struct iovec handle;           /* Handle of persistent key. */

        SigningKeyHierarchy hierarchy; /* Hierarchy in which to recreate primary key. */
        struct iovec template;         /* Template used to recreate primary key. */
        struct iovec name;             /* Expected name of primary key. */
} SigningKeyData;

static SigningKeyData *signing_key_data_free(SigningKeyData *d) {
        if (!d)
                return NULL;

        iovec_done(&d->parent_handle);
        iovec_done(&d->public);
        iovec_done(&d->private);

        iovec_done(&d->handle);

        iovec_done(&d->template);
        iovec_done(&d->name);

        return mfree(d);
}

DEFINE_TRIVIAL_CLEANUP_FUNC(SigningKeyData*, signing_key_data_free);

static int load_signing_key_data(int dir_fd, const char *fname, SigningKeyData *ret) {
        int r;

        assert(dir_fd >= 0);
        assert(fname);
        assert(ret);

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        _cleanup_fclose_ FILE *f = NULL;
        r = xfopenat(dir_fd, fname, "re", /* open_flags= */ 0, &f);
        if (r < 0)
                return log_error_errno(r, "Failed to open TPM signing key data '%s/%s': %m",
                                       strnull(dir_path), fname);

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *v = NULL;
        r = sd_json_parse_file(
                        f,
                        /* path= */ NULL,
                        /* flags= */ 0,
                        &v,
                        /* reterr_line= */ NULL,
                        /* reterr_column= */ NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to load TPM signing key data from '%s/%s': %m",
                                       strnull(dir_path), fname);

        static const sd_json_dispatch_field dispatch_table[] = {
                { "type",         SD_JSON_VARIANT_STRING,        json_dispatch_signing_key_type,      offsetof(SigningKeyData, type),          SD_JSON_MANDATORY },
                { "parentHandle", SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(SigningKeyData, parent_handle), 0                 },
                { "public",       SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(SigningKeyData, public),        0                 },
                { "private",      SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(SigningKeyData, private),       0                 },
                { "handle",       SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(SigningKeyData, handle),        0                 },
                { "hierarchy",    _SD_JSON_VARIANT_TYPE_INVALID, json_dispatch_signing_key_hierarchy, offsetof(SigningKeyData, hierarchy),     0                 },
                { "template",     SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(SigningKeyData, template),      0                 },
                { "name",         SD_JSON_VARIANT_STRING,        json_dispatch_unhex_iovec,           offsetof(SigningKeyData, name),          0                 },
                {},
        };

        r = sd_json_dispatch(v, dispatch_table, SD_JSON_ALLOW_EXTENSIONS, ret);
        if (r < 0)
                return log_error_errno(r, "Failed to dispatch TPM signing key data from '%s/%s': %m",
                                       strnull(dir_path), fname);

        log_debug("Loaded TPM signing key data from '%s/%s'.", strnull(dir_path), fname);
        return 0;
}

/* Build the JSON key data for an ordinary key. */
static int build_ordinary_key_data(
                Tpm2Context *c,
                const Tpm2Handle *parent,
                const TPM2B_PUBLIC *public,
                const TPM2B_PRIVATE *private,
                sd_json_variant **ret) {
        int r;

        assert(c);
        assert(parent);
        assert(public);
        assert(private);
        assert(ret);

        _cleanup_(iovec_done) struct iovec parent_handle_buf = {};
        r = tpm2_serialize(c, parent, &parent_handle_buf);
        if (r < 0)
                return log_error_errno(r, "Failed to serialize parent handle: %m");

        _cleanup_free_ void *public_buf = NULL;
        size_t public_sz;
        r = tpm2_marshal_public(public, &public_buf, &public_sz);
        if (r < 0)
                return log_error_errno(r, "Failed to marshal public area for new ordinary signing key: %m");

        _cleanup_free_ void *private_buf = NULL;
        size_t private_sz;
        r = tpm2_marshal_private(private, &private_buf, &private_sz);
        if (r < 0)
                return log_error_errno(r, "Failed to marshal private area for new ordinary signing key: %m");

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *v = NULL;
        r = sd_json_buildo(
                        &v,
                        SD_JSON_BUILD_PAIR_STRING("type", signing_key_type_to_string(SIGNING_KEY_ORDINARY)),
                        JSON_BUILD_PAIR_IOVEC_BASE64("parentHandle", &parent_handle_buf),
                        SD_JSON_BUILD_PAIR_BASE64("public", public_buf, public_sz),
                        SD_JSON_BUILD_PAIR_BASE64("private", private_buf, private_sz));
        if (r < 0)
                return log_error_errno(r, "Failed to build signing key data: %m");

        *ret = TAKE_PTR(v);
        return 0;
}

/* Generate an ordinary attestation key as a child of the EK, using the best available template. */
static int generate_key(Tpm2Context *c, int dir_fd) {
        int r;

        assert(c);
        assert(dir_fd >= 0);

        TPMT_PUBLIC template;
        r = tpm2_get_best_attestation_key_template(c, &template);
        if (r < 0)
                return log_error_errno(r, "Failed to get attestation key template: %m");

        _cleanup_(tpm2_handle_freep) Tpm2Handle *ek_handle = NULL;
        r = tpm2_get_or_create_ek(c, /* session= */ NULL, /*  ret_public= */ NULL, /* ret_name= */ NULL, /* ret_qname= */ NULL, &ek_handle);
        if (r < 0)
                return log_error_errno(r, "Failed to get handle to persistent EK: %m");

        /* The EK requires a policy session for authorization. */
        _cleanup_(tpm2_handle_freep) Tpm2Handle *session = NULL;
        r = tpm2_open_ek_user_policy_session(c, /* session= */ NULL, ek_handle, &session);
        if (r < 0)
                return log_error_errno(r, "Failed to open policy session for EK: %m");

        _cleanup_(Esys_Freep) TPM2B_PUBLIC *public = NULL;
        _cleanup_(Esys_Freep) TPM2B_PRIVATE *private = NULL;
        r = tpm2_create(c, ek_handle, session, &template, /* sensitive= */ NULL, &public, &private);
        if (r < 0)
                return log_error_errno(r, "Failed to create new ordinary signing key: %m");

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *v = NULL;
        r = build_ordinary_key_data(c, ek_handle, public, private, &v);
        if (r < 0)
                return r;

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        const char *fname = REPORT_SIGN_TPM2_KEY_DEFAULT_NAME REPORT_SIGN_TPM2_KEY_EXT;

        _cleanup_fclose_ FILE *f = NULL;
        _cleanup_free_ char *temp = NULL;
        r = fopen_tmpfile_linkable_at(dir_fd, fname, O_WRONLY, &temp, &f);
        if (r < 0)
                return log_error_errno(r, "Failed to open signing key data file '%s/%s' for writing: %m",
                                       strnull(dir_path), fname);

        CLEANUP_TMPFILE_AT(dir_fd, temp);

        r = sd_json_variant_dump(v, SD_JSON_FORMAT_NEWLINE, f, /* prefix= */ NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to write signing key data: %m");

        r = flink_tmpfile_at(f, dir_fd, temp, fname, LINK_TMPFILE_SYNC);
        if (r < 0)
                return log_error_errno(r, "Failed to move signing key data file '%s/%s' into place: %m",
                                       strnull(dir_path), fname);

        temp = mfree(temp);

        log_debug("Generated signing key and saved to '%s/%s'.", strnull(dir_path), fname);
        return 0;
}

typedef struct SigningKey {
        char *name;
        SigningKeyData *data;
        struct iovec voucher;
} SigningKey;

static void signing_key_done(SigningKey *k) {
        assert(k);

        k->name = mfree(k->name);
        k->data = signing_key_data_free(k->data);
        iovec_done(&k->voucher);
}

static void signing_key_array_free(SigningKey *keys, size_t n_keys) {
        assert(keys || n_keys == 0);

        FOREACH_ARRAY(k, keys, n_keys)
                signing_key_done(k);

        mfree(keys);
}

/* Load a single signing key and its optional voucher. */
static int load_signing_key(int dir_fd, const char *key_fname, SigningKey *ret) {
        int r;

        assert(dir_fd >= 0);
        assert(key_fname);
        assert(ret);

        const char *e = endswith(key_fname, REPORT_SIGN_TPM2_KEY_EXT);
        assert(e);

        _cleanup_free_ char *name = strndup(key_fname, e - key_fname);
        if (!name)
                return log_oom();

        _cleanup_(signing_key_data_freep) SigningKeyData *data = new0(SigningKeyData, 1);
        if (!data)
                return log_oom();

        r = load_signing_key_data(dir_fd, key_fname, data);
        if (r < 0)
                return r;

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        _cleanup_free_ char *voucher_fname = strjoin(name, REPORT_SIGN_TPM2_VOUCHER_EXT);
        if (!voucher_fname)
                return log_oom();

        _cleanup_(iovec_done) struct iovec voucher = {};
        _cleanup_free_ char *voucher_buf = NULL;
        size_t voucher_sz = 0;
        r = read_full_file_at(dir_fd, voucher_fname, &voucher_buf, &voucher_sz);
        if (r < 0 && r != -ENOENT)
                return log_error_errno(r, "Failed to read signing key voucher '%s/%s': %m",
                                       strnull(dir_path), voucher_fname);
        if (r >= 0) {
                log_debug("Loaded signing key voucher from '%s/%s'.", strnull(dir_path), voucher_fname);
                voucher = IOVEC_MAKE(TAKE_PTR(voucher_buf), voucher_sz);
        }

        *ret = (SigningKey) {
                .name = TAKE_PTR(name),
                .data = TAKE_PTR(data),
                .voucher = TAKE_STRUCT(voucher),
        };

        return 0;
}

/* Load all signing keys and their optional vouchers.
 *
 * If there are no existing signing keys, then one is created automatically as an ordinary child of the EK,
 * unless a voucher for the default key already exists.
 *
 * It might also be nice to have some way of customizing what type of signing key is automatically created
 * if one doesn't exist. */
static int load_signing_keys(Tpm2Context *c, SigningKey **ret_keys, size_t *ret_n_keys) {
        int r;

        assert(c);
        assert(ret_keys);
        assert(ret_n_keys);

        /* Open (creating if necessary) and exclusively lock the key directory, so that loading/generating the
         * key is safe against parallel invocations (we are spawned once per connection). Like with the plain
         * signer, the directory has 0700 permissions but this is just to be conservative - there's no
         * unencrypted key material here. */
        _cleanup_close_ int dir_fd = xopenat_lock_full(
                        AT_FDCWD,
                        REPORT_SIGN_TPM2_PERSISTENT_DIR,
                        O_CLOEXEC|O_DIRECTORY|O_CREAT,
                        /* xopen_flags= */ 0,
                        /* mode= */ 0700,
                        LOCK_BSD,
                        LOCK_EX);
        if (dir_fd < 0)
                return log_error_errno(dir_fd, "Failed to open and lock directory '%s': %m", REPORT_SIGN_TPM2_PERSISTENT_DIR);

        SigningKey *keys = NULL;
        size_t n_keys = 0;
        CLEANUP_ARRAY(keys, n_keys, signing_key_array_free);

        _cleanup_closedir_ DIR *d = xopendirat(dir_fd, "", O_CLOEXEC);
        if (!d)
                return log_error_errno(errno, "Failed to open directory '%s': %m", REPORT_SIGN_TPM2_PERSISTENT_DIR);

        FOREACH_DIRENT(de, d, return log_error_errno(errno, "Failed to read directory '%s': %m", REPORT_SIGN_TPM2_PERSISTENT_DIR)) {
                if (!dirent_is_file_with_suffix(de, REPORT_SIGN_TPM2_KEY_EXT))
                        continue;

                if (!GREEDY_REALLOC(keys, n_keys + 1))
                        return log_oom();

                r = load_signing_key(dir_fd, de->d_name, keys + n_keys);
                if (r < 0)
                        return r;

                n_keys++;
        }

        /* If there are no keys yet, generate a default one and load it. */
        if (n_keys == 0) {
                /* This shouldn't be a scenario that happens in practice, unless somebody erased default.key.
                 * But nevertheless, if we get here with no signing keys but there is a default.voucher, we
                 * refuse to generate the default key. */
                const char *voucher_fname = REPORT_SIGN_TPM2_KEY_DEFAULT_NAME REPORT_SIGN_TPM2_VOUCHER_EXT;
                if (faccessat(dir_fd, voucher_fname, F_OK, AT_SYMLINK_NOFOLLOW) >= 0)
                        return log_error_errno(SYNTHETIC_ERRNO(ENOENT),
                                               "Voucher '%s/%s' exists but its signing key does not, refusing to generate a default signing key.",
                                               REPORT_SIGN_TPM2_PERSISTENT_DIR, voucher_fname);
                if (errno != ENOENT)
                        return log_error_errno(errno, "Failed to check whether voucher '%s/%s' exists: %m",
                                               REPORT_SIGN_TPM2_PERSISTENT_DIR, voucher_fname);

                log_debug("No existing signing keys, generating a default signing key.");

                r = generate_key(c, dir_fd);
                if (r < 0)
                        return r;

                if (!GREEDY_REALLOC(keys, n_keys + 1))
                        return log_oom();

                r = load_signing_key(dir_fd, REPORT_SIGN_TPM2_KEY_DEFAULT_NAME REPORT_SIGN_TPM2_KEY_EXT, keys + n_keys);
                if (r < 0)
                        return r;

                n_keys++;
        }

        *ret_keys = TAKE_PTR(keys);
        *ret_n_keys = n_keys;

        return 0;
}

/* Create a primary TPM key in the specified hierarchy, using the supplied template. */
static int create_primary_key(
                Tpm2Context *c,
                SigningKeyHierarchy hierarchy,
                const TPMT_PUBLIC *template,
                TPM2B_NAME **ret_name,
                TPM2B_PUBLIC **ret_public,
                Tpm2Handle **ret_handle) {
        int r;

        assert(c);
        assert(template);
        assert(ret_handle);

        ESYS_TR hierarchy_esys;
        switch (hierarchy) {
        case SIGNING_KEY_HIERARCHY_OWNER:
                hierarchy_esys = ESYS_TR_RH_OWNER;
                break;
        case SIGNING_KEY_HIERARCHY_ENDORSEMENT:
                hierarchy_esys = ESYS_TR_RH_ENDORSEMENT;
                break;
        default:
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL), "Unsupported hierarchy for primary key");
        }

        TPM2B_PUBLIC template_tpm2b = {
                .size = sizeof(TPMT_PUBLIC),
                .publicArea = *template,
        };

        _cleanup_(Esys_Freep) TPM2B_PUBLIC *public = NULL;
        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        r = tpm2_create_primary(c, /* session= */ NULL, hierarchy_esys, &template_tpm2b, /* sensitive= */ NULL, &public, &handle);
        if (r < 0)
                return log_error_errno(r, "Failed to create primary key: %m");

        _cleanup_(Esys_Freep) TPM2B_NAME *name = NULL;
        if (ret_name) {
                r = tpm2_get_name(c, handle, &name);
                if (r < 0)
                        return log_error_errno(r, "Failed to get name of primary key: %m");

                *ret_name = TAKE_PTR(name);
        }
        if (ret_public)
                *ret_public = TAKE_PTR(public);
        *ret_handle = TAKE_PTR(handle);

        return 0;
}

/* Recreate a primary TPM key in the specified hierarchy, using the supplied template data. */
static int recreate_primary_key(
                Tpm2Context *c,
                SigningKeyHierarchy hierarchy,
                const struct iovec *template,
                const struct iovec *expected_name,
                Tpm2Handle **ret) {
        int r;

        assert(c);
        assert(iovec_is_valid(template));
        assert(iovec_is_valid(expected_name));
        assert(ret);

        TPM2B_PUBLIC template_tpm2b;
        r = tpm2_unmarshal_public(template->iov_base, template->iov_len, &template_tpm2b);
        if (r < 0)
                return log_error_errno(r, "Failed to unmarshal primary signing key template: %m");

        _cleanup_(Esys_Freep) TPM2B_NAME *name = NULL;
        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        r = create_primary_key(c, hierarchy, &template_tpm2b.publicArea, &name, /* ret_public= */ NULL, &handle);
        if (r < 0)
                return r;

        if (memcmp_nn(expected_name->iov_base, expected_name->iov_len, name->name, name->size) != 0)
                return log_warning_errno(SYNTHETIC_ERRNO(ENOKEY),
                                       "Recreated primary attestation key does not have the expected name. This is likely because the primary seed of the TPM hierarchy has changed");

        log_debug("Acquired primary signing key handle.");

        *ret = TAKE_PTR(handle);

        return 0;
}

/* Acquire a handle for a persistent TPM key using the supplied persistent handle data. */
static int acquire_persistent_key(Tpm2Context *c, const struct iovec *handle_data, Tpm2Handle **ret) {
        int r;

        assert(c);
        assert(iovec_is_valid(handle_data));
        assert(ret);

        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        r = tpm2_deserialize(c, handle_data, &handle);
        if (r < 0)
                return log_error_errno(r, "Failed to deserialize persistent signing key handle: %m");

        /* Make sure that the loaded handle matches the TPM object. */

        _cleanup_(Esys_Freep) TPM2B_NAME *handle_name = NULL;
        r = tpm2_get_name(c, handle, &handle_name);
        if (r < 0)
                return log_error_errno(r, "Failed to get name of persistent signing key handle: %m");

        _cleanup_(Esys_Freep) TPM2B_NAME *real_name = NULL;
        r = tpm2_read_public(c, /* session= */ NULL, handle, /* ret_public= */ NULL, &real_name, /* ret_qname= */ NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to read name of persistent signing key from TPM: %m");

        if (memcmp_nn(handle_name->name, handle_name->size, real_name->name, real_name->size) != 0)
                return log_warning_errno(SYNTHETIC_ERRNO(ENOKEY),
                                         "Persistent object in the TPM does not match the saved handle");

        log_debug("Acquired persistent signing key handle.");

        *ret = TAKE_PTR(handle);

        return 0;
}

/* Load an ordinary TPM key using the supplied parent handle data, and public and private areas. */
static int load_ordinary_key(
                Tpm2Context *c,
                const struct iovec *parent_handle_data,
                const struct iovec *public,
                const struct iovec *private,
                Tpm2Handle **ret) {
        int r;

        assert(c);
        assert(iovec_is_valid(parent_handle_data));
        assert(iovec_is_valid(public));
        assert(iovec_is_valid(private));
        assert(ret);

        _cleanup_(tpm2_handle_freep) Tpm2Handle *parent = NULL;
        r = tpm2_deserialize(c, parent_handle_data, &parent);
        if (r < 0)
                return log_error_errno(r, "Failed to deserialize ordinary signing key parent handle: %m");

        TPM2B_PUBLIC public_tpm2b;
        r = tpm2_unmarshal_public(public->iov_base, public->iov_len, &public_tpm2b);
        if (r < 0)
                return log_error_errno(r, "Failed to unmarshal ordinary signing key public area: %m");

        TPM2B_PRIVATE private_tpm2b;
        r = tpm2_unmarshal_private(private->iov_base, private->iov_len, &private_tpm2b);
        if (r < 0)
                return log_error_errno(r, "Failed to unmarshal ordinary signing key private area: %m");

        _cleanup_(tpm2_handle_freep) Tpm2Handle *session = NULL;
        r = tpm2_open_ek_user_policy_session(c, /* session= */ NULL, parent, &session);
        if (r < 0)
                return log_error_errno(r, "Failed to open policy session for EK: %m");

        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        r = tpm2_load(c, parent, session, &public_tpm2b, &private_tpm2b, &handle);
        if (r == -EREMOTE)
                return log_warning_errno(SYNTHETIC_ERRNO(ENOKEY),
                                         "Ordinary attestation key failed an integrity check when loading it into the TPM. "
                                         "Either the storage key at the parent handle in the TPM isn't the correct one or the saved key data is invalid.");
        if (r < 0)
                return log_error_errno(r, "Failed to load ordinary attestation key into the TPM: %m");

        log_debug("Acquired ordinary signing key handle.");

        *ret = TAKE_PTR(handle);

        return 0;
}

/* Try to load a TPM context for the specified name from the supplied directory. */
static int load_key_context(Tpm2Context *c, int dir_fd, const char *name, Tpm2Handle **ret) {
        int r;

        assert(c);
        assert(dir_fd >= 0);
        assert(name);
        assert(ret);

        _cleanup_free_ char *fname = strjoin(name, REPORT_SIGN_TPM2_KEYCONTEXT_EXT);
        if (!fname)
                return log_oom();

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        _cleanup_free_ char *buf = NULL;
        size_t buf_sz;
        r = read_full_file_at(dir_fd, fname, &buf, &buf_sz);
        if (r == -ENOENT)
                return r;
        if (r < 0)
                return log_error_errno(r, "Failed to read saved signing key context from '%s/%s': %m",
                                       strnull(dir_path), fname);

        TPMS_CONTEXT context;
        r = tpm2_unmarshal_saved_handle_context(buf, buf_sz, &context);
        if (r < 0)
                return log_error_errno(r, "Failed to unmarshal saved signing key context '%s': %m", name);

        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        r = tpm2_load_saved_handle_context(c, &context, /* ret_name= */ NULL, &handle);
        if (r < 0)
                return log_error_errno(r, "Failed to load saved signing key context '%s': %m", name);

        log_debug("Acquired signing key handle from saved context at '%s/%s.", strnull(dir_path), fname);

        *ret = TAKE_PTR(handle);

        return 0;
}

/* Save the TPM context for the key at the supplied handle to the specified directory. */
static int save_key_context(Tpm2Context *c, int dir_fd, const char *name, const Tpm2Handle *handle) {
        int r;

        assert(c);
        assert(dir_fd >= 0);
        assert(name);
        assert(handle);

        _cleanup_free_ char *fname = strjoin(name, REPORT_SIGN_TPM2_KEYCONTEXT_EXT);
        if (!fname)
                return log_oom();

        _cleanup_(Esys_Freep) TPMS_CONTEXT *context = NULL;
        r = tpm2_save_handle_context(c, handle, &context);
        if (r < 0)
                return log_debug_errno(r, "Failed to save signing key context '%s': %m", name);

        _cleanup_free_ void *buf = NULL;
        size_t buf_sz;
        r = tpm2_marshal_saved_handle_context(context, &buf, &buf_sz);
        if (r < 0)
                return log_debug_errno(r, "Failed to marshal signing key context '%s': %m", name);

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        r = write_data_file_atomic_at(
                        dir_fd,
                        fname,
                        &IOVEC_MAKE(buf, buf_sz),
                        /* flags= */ 0);
        if (r < 0)
                return log_error_errno(r, "Failed to write saved signing key context to '%s/%s': %m",
                                       strnull(dir_path), fname);

        log_debug("Saved signing key context to '%s/%s'.", strnull(dir_path), fname);

        return 0;
}

/* Acquire a signing key handle. This can acquire several types of signing key:
 * - An ordinary object that is protected by an existing persistent object (like the EK or SRK). These are
 *   loaded from a saved context if one exists, otherwise falling back to doing TPM2_Load again.
 * - A persistent object.
 * - A primary object that is created from a template on each use. */
static int acquire_key_handle(Tpm2Context *c, int runtime_dir_fd, const char *name, const SigningKeyData *data, Tpm2Handle **ret) {
        int r;

        assert(c);
        assert(runtime_dir_fd >= 0);
        assert(name);
        assert(data);
        assert(ret);

        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
        switch (data->type) {
        case SIGNING_KEY_ORDINARY:
                r = load_key_context(c, runtime_dir_fd, name, &handle);
                if (r == -ENOENT) {
                        r = load_ordinary_key(c, &data->parent_handle, &data->public, &data->private, &handle);
                        if (r < 0)
                                return r;

                        (void) save_key_context(c, runtime_dir_fd, name, handle);
                } else if (r < 0)
                        return r;
                break;
        case SIGNING_KEY_PERSISTENT:
                r = acquire_persistent_key(c, &data->handle, &handle);
                if (r < 0)
                        return r;
                break;
        case SIGNING_KEY_PRIMARY:
                r = load_key_context(c, runtime_dir_fd, name, &handle);
                if (r == -ENOENT) {
                        r = recreate_primary_key(c, data->hierarchy, &data->template, &data->name, &handle);
                        if (r < 0)
                                return r;

                        (void) save_key_context(c, runtime_dir_fd, name, handle);
                } else if (r < 0)
                        return r;
                break;
        default:
                assert_not_reached();
        }

        *ret = TAKE_PTR(handle);
        return 0;
}

static int build_report(sd_json_variant **v, const Tpm2Report *report, const struct iovec *voucher) {
        int r;

        assert(v);
        assert(report);
        assert(iovec_is_valid(voucher));

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *pubkey = NULL;
        r = tpm2_tpmt_public_to_json(report->public_key, &pubkey);
        if (r < 0)
                return log_error_errno(r, "Cannot convert public key to JSON: %m");

        _cleanup_free_ char *pubkey_pem = NULL;
        r = tpm2_tpmt_public_to_pem(report->public_key, &pubkey_pem);
        if (r < 0)
                return log_error_errno(r, "Cannot convert public key to PEM: %m");

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *cv = NULL;
        FOREACH_ARRAY(c, report->components, report->n_components) {
                _cleanup_(sd_json_variant_unrefp) sd_json_variant *nv_public = NULL;
                if (c->type == TPM2_REPORT_TYPE_NVPCR) {
                        r = tpm2_tpms_nv_public_to_json(c->nv_public, &nv_public);
                        if (r < 0)
                                return log_error_errno(r, "Cannot convert NvPCR public area to JSON: %m");
                }

                const char *session_audit_hash_alg = NULL;
                if (c->type == TPM2_REPORT_TYPE_SESSION_AUDIT) {
                        session_audit_hash_alg = tpm2_hash_alg_to_string_tss2(c->session_audit_hash_alg);
                        if (!session_audit_hash_alg)
                                return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE),
                                                       "Unsupported session audit hash algorithm 0x%" PRIx16, c->session_audit_hash_alg);
                }

                TPMT_SIG_SCHEME scheme = {
                        .scheme = c->signature->sigAlg,
                };
                if (IN_SET(scheme.scheme, TPM2_ALG_RSASSA, TPM2_ALG_RSAPSS, TPM2_ALG_ECDSA))
                        scheme.details.any = c->signature->signature.any;
                else if (scheme.scheme != TPM2_ALG_NULL)
                        return log_error_errno(SYNTHETIC_ERRNO(ENOTRECOVERABLE),
                                               "Unsupported signature scheme 0x%" PRIx16, scheme.scheme);

                _cleanup_(sd_json_variant_unrefp) sd_json_variant *attest_info = NULL;
                r = tpm2_attest_info_to_json(&scheme, c->attestation, &attest_info);
                if (r < 0)
                        return log_error_errno(r, "Cannot convert attestation info to JSON: %m");

                _cleanup_(sd_json_variant_unrefp) sd_json_variant *sig = NULL;
                r = tpm2_tpmt_signature_to_json(c->signature, &sig);
                if (r < 0)
                        return log_error_errno(r, "Cannot convert signature to JSON: %m");

                _cleanup_free_ char *sig_pem = NULL;
                r = tpm2_tpmt_signature_to_pem(c->signature, &sig_pem);
                if (r < 0)
                        return log_error_errno(r, "Cannot convert signature to PEM: %m");

                r = sd_json_variant_append_arraybo(
                                &cv,
                                SD_JSON_BUILD_PAIR_STRING("type", tpm2_report_component_type_to_string(c->type)),
                                SD_JSON_BUILD_PAIR_CONDITION(c->type == TPM2_REPORT_TYPE_NVPCR, "nvpcrName", SD_JSON_BUILD_STRING(c->nv_pcr_name)),
                                SD_JSON_BUILD_PAIR_CONDITION(c->type == TPM2_REPORT_TYPE_NVPCR, "nvPublic", SD_JSON_BUILD_VARIANT(nv_public)),
                                SD_JSON_BUILD_PAIR_CONDITION(c->type != TPM2_REPORT_TYPE_SESSION_AUDIT && c->authenticated_data, "authenticatedData", SD_JSON_BUILD_STRING(c->authenticated_data)),
                                JSON_BUILD_PAIR_STRING_NON_EMPTY("sessionAuditHashAlg", session_audit_hash_alg),
                                SD_JSON_BUILD_PAIR_VARIANT("attestInfo", attest_info),
                                SD_JSON_BUILD_PAIR_VARIANT("signature", sig),
                                SD_JSON_BUILD_PAIR_STRING("signaturePEM", sig_pem));
                if (r < 0)
                        return log_error_errno(r, "Cannot add component to report array: %m");
        }

        return sd_json_variant_append_arraybo(
                        v,
                        SD_JSON_BUILD_PAIR_VARIANT("eventLog", report->event_log),
                        SD_JSON_BUILD_PAIR_VARIANT("publicKey", pubkey),
                        SD_JSON_BUILD_PAIR_STRING("publicKeyPEM", pubkey_pem),
                        SD_JSON_BUILD_PAIR_CONDITION(iovec_is_set(voucher), "voucher", JSON_BUILD_IOVEC_BASE64(voucher)),
                        SD_JSON_BUILD_PAIR_VARIANT("components", cv));
}

static int vl_method_sign(
                sd_varlink *link,
                sd_json_variant *parameters,
                sd_varlink_method_flags_t flags,
                void *userdata) {

        static const sd_json_dispatch_field dispatch_table[] = {
                { "digest",    SD_JSON_VARIANT_STRING, json_dispatch_unhex_iovec,     offsetof(SignRequestParameters, digest),    SD_JSON_MANDATORY },
                { "algorithm", SD_JSON_VARIANT_STRING, sd_json_dispatch_const_string, offsetof(SignRequestParameters, algorithm), SD_JSON_MANDATORY },
                {}
        };

        int r;
        _cleanup_(sign_request_parameters_done) SignRequestParameters sign_params = {};

        assert(link);
        assert(parameters);

        r = sd_varlink_dispatch(link, parameters, dispatch_table, &sign_params);
        if (r != 0)
                return r;

        /* Serialize the supplied digest to a TPM2B_DATA structure prefixed with the algorithm ID,
         * and include this in the TPM report. Note that tpm2_digest_buf_to_data checks that the
         * supplied digest has the correct size. */
        r = tpm2_hash_alg_from_string(sign_params.algorithm);
        if (r < 0)
                return sd_varlink_error_invalid_parameter_name(link, "algorithm");

        TPM2B_DATA external_data;
        r = tpm2_digest_iovec_to_data((TPMI_ALG_HASH) r, &sign_params.digest, &external_data);
        if (r == -EINVAL)
                return sd_varlink_error_invalid_parameter_name(link, "digest");
        if (r < 0)
                return log_error_errno(r, "Failed to marshal digest: %m");

        /* Use fixed options. Maybe it would be good to have a way to configure this. */
        _cleanup_(tpm2_report_options_done) Tpm2ReportOptions opts = {};
        r = make_default_report_options(&opts);
        if (r < 0)
                return r;

        _cleanup_(tpm2_context_unrefp) Tpm2Context *c = NULL;
        r = tpm2_context_new_or_warn(/* device= */ NULL, &c);
        if (r < 0)
                return r;

        /* Open (creating if necessary) and exclusively lock the runtime directory which we use for loading
         * and saving TPM key contexts. The exclusive lock ensures we serialize parallel invocations, as
         * the report signing requires TPM exclusivity. */
        _cleanup_close_ int runtime_dir_fd = xopenat_lock_full(
                        AT_FDCWD,
                        REPORT_SIGN_TPM2_RUNTIME_DIR,
                        O_CLOEXEC|O_DIRECTORY|O_CREAT,
                        /* xopen_flags = */ 0,
                        /* mode= */ 0700,
                        LOCK_BSD,
                        LOCK_EX);
        if (runtime_dir_fd < 0)
                return log_error_errno(runtime_dir_fd, "Failed to open and lock directory '%s': %m", REPORT_SIGN_TPM2_RUNTIME_DIR);

        /* Load all signing keys. */
        SigningKey *keys = NULL;
        size_t n_keys = 0;
        CLEANUP_ARRAY(keys, n_keys, signing_key_array_free);

        r = load_signing_keys(c, &keys, &n_keys);
        if (r < 0)
                return log_error_errno(r, "Failed to load any signing keys: %m");

        /* Generate a signed TPM report for each signing key. */
        _cleanup_(sd_json_variant_unrefp) sd_json_variant *dv = NULL;
        FOREACH_ARRAY(key, keys, n_keys) {
                _cleanup_(tpm2_handle_freep) Tpm2Handle *key_handle = NULL;
                r = acquire_key_handle(c, runtime_dir_fd, key->name, key->data, &key_handle);
                if (r == -ENOKEY) {
                        log_warning("The signing key '%s' is not available, skipping.", key->name);
                        continue;
                }
                if (r < 0)
                        return log_error_errno(r, "Failed to acquire a signing key handle for key '%s': %m", key->name);

                _cleanup_(tpm2_report_freep) Tpm2Report *report = NULL;
                r = tpm2_generate_report(c, &opts, key_handle, &external_data, &report);
                if (r < 0)
                        return log_error_errno(r, "Failed to generate TPM report with key '%s': %m", key->name);

                r = build_report(&dv, report, &key->voucher);
                if (r < 0)
                        return log_error_errno(r, "Failed to build TPM report JSON for key '%s': %m", key->name);
        }
        if (!dv)
                return sd_varlink_replybo(link, SD_JSON_BUILD_PAIR_EMPTY_ARRAY("data"));

        return sd_varlink_replybo(link, SD_JSON_BUILD_PAIR_VARIANT("data", dv));
}

typedef enum SigningScheme {
        SIGNING_SCHEME_RSASSA,
        SIGNING_SCHEME_RSAPSS,
        SIGNING_SCHEME_ECDSA,

        _SIGNING_SCHEME_MAX,
        _SIGNING_SCHEME_INVALID = -EINVAL,
} SigningScheme;

static const char* const signing_scheme_table[_SIGNING_SCHEME_MAX] = {
        [SIGNING_SCHEME_RSASSA] = "rsassa",
        [SIGNING_SCHEME_RSAPSS] = "rsapss",
        [SIGNING_SCHEME_ECDSA]  = "ecdsa",
};
DEFINE_PRIVATE_STRING_TABLE_LOOKUP_FROM_STRING(signing_scheme, SigningScheme);
static JSON_DISPATCH_ENUM_DEFINE(json_dispatch_signing_scheme, SigningScheme, signing_scheme_from_string);

typedef enum HashAlgorithm {
        HASH_ALGORITHM_SHA256,
        HASH_ALGORITHM_SHA384,
        HASH_ALGORITHM_SHA512,

        _HASH_ALGORITHM_MAX,
        _HASH_ALGORITHM_INVALID = -EINVAL,
} HashAlgorithm;

static const char* const hash_algorithm_table[_HASH_ALGORITHM_MAX] = {
        [HASH_ALGORITHM_SHA256] = "sha256",
        [HASH_ALGORITHM_SHA384] = "sha384",
        [HASH_ALGORITHM_SHA512] = "sha512",
};
DEFINE_PRIVATE_STRING_TABLE_LOOKUP_FROM_STRING(hash_algorithm, HashAlgorithm);
static JSON_DISPATCH_ENUM_DEFINE(json_dispatch_hash_algorithm, HashAlgorithm, hash_algorithm_from_string);

static TPMI_ALG_HASH hash_algorithm_to_tpm(HashAlgorithm alg) {
        switch (alg) {
        case HASH_ALGORITHM_SHA256:
                return TPM2_ALG_SHA256;
        case HASH_ALGORITHM_SHA384:
                return TPM2_ALG_SHA384;
        case HASH_ALGORITHM_SHA512:
                return TPM2_ALG_SHA512;
        default:
                return TPM2_ALG_ERROR;
        }
}

typedef enum ECCCurve {
        ECC_CURVE_NISTP256,
        ECC_CURVE_NISTP384,
        ECC_CURVE_NISTP521,

        _ECC_CURVE_MAX,
        _ECC_CURVE_INVALID = -EINVAL,
} ECCCurve;

static const char* const ecc_curve_table[_ECC_CURVE_MAX] = {
        [ECC_CURVE_NISTP256] = "nistp256",
        [ECC_CURVE_NISTP384] = "nistp384",
        [ECC_CURVE_NISTP521] = "nistp521",
};
DEFINE_PRIVATE_STRING_TABLE_LOOKUP_FROM_STRING(ecc_curve, ECCCurve);
static JSON_DISPATCH_ENUM_DEFINE(json_dispatch_ecc_curve, ECCCurve, ecc_curve_from_string);

static TPMI_ECC_CURVE ecc_curve_to_tpm(ECCCurve c) {
        switch (c) {
        case ECC_CURVE_NISTP256:
                return TPM2_ECC_NIST_P256;
        case ECC_CURVE_NISTP384:
                return TPM2_ECC_NIST_P384;
        case ECC_CURVE_NISTP521:
                return TPM2_ECC_NIST_P521;
        default:
                return TPM2_ECC_NONE;
        }
}

/* The TPM persistent handle range. Like tpm2_persist_handle() we don't use TPM2_PERSISTENT_FIRST/LAST here,
 * see the comment there. */
static bool is_persistent_handle(uint64_t h) {
        return h >= UINT64_C(0x81000000) && h <= UINT64_C(0x81ffffff);
}

/* Build the template for a new signing key. The unique area (used to customize primary keys) is not set here. */
static void make_signing_key_template(
                SigningScheme scheme,
                TPMI_ALG_HASH hash_alg,
                uint16_t rsa_key_bits,
                TPMI_ECC_CURVE ecc_curve,
                TPMT_PUBLIC *ret) {

        assert(ret);

        TPMT_PUBLIC template = {
                .nameAlg = hash_alg,
                .objectAttributes =
                        TPMA_OBJECT_FIXEDTPM |
                        TPMA_OBJECT_FIXEDPARENT |
                        TPMA_OBJECT_SENSITIVEDATAORIGIN |
                        TPMA_OBJECT_USERWITHAUTH |
                        TPMA_OBJECT_RESTRICTED |
                        TPMA_OBJECT_SIGN_ENCRYPT,
                .parameters.asymDetail.symmetric.algorithm = TPM2_ALG_NULL,
        };

        switch (scheme) {
        case SIGNING_SCHEME_RSASSA:
        case SIGNING_SCHEME_RSAPSS:
                template.type = TPM2_ALG_RSA;
                template.parameters.rsaDetail.scheme.scheme = scheme == SIGNING_SCHEME_RSASSA ? TPM2_ALG_RSASSA : TPM2_ALG_RSAPSS;
                template.parameters.rsaDetail.scheme.details.anySig.hashAlg = hash_alg;
                template.parameters.rsaDetail.keyBits = rsa_key_bits;
                template.parameters.rsaDetail.exponent = 0;
                break;
        case SIGNING_SCHEME_ECDSA:
                template.type = TPM2_ALG_ECC;
                template.parameters.eccDetail.scheme.scheme = TPM2_ALG_ECDSA;
                template.parameters.eccDetail.scheme.details.ecdsa.hashAlg = hash_alg;
                template.parameters.eccDetail.curveID = ecc_curve;
                template.parameters.eccDetail.kdf.scheme = TPM2_ALG_NULL;
                break;
        default:
                assert_not_reached();
        }

        *ret = template;
}

/* Copy the supplied nonce into the unique area of the template, used to customize primary keys. */
static int signing_key_template_set_nonce(TPMT_PUBLIC *template, const struct iovec *nonce) {
        assert(template);
        assert(iovec_is_valid(nonce));

        switch (template->type) {
        case TPM2_ALG_RSA:
                if (nonce->iov_len > sizeof(template->unique.rsa.buffer))
                        return -EINVAL;

                template->unique.rsa.size = nonce->iov_len;
                memcpy_safe(template->unique.rsa.buffer, nonce->iov_base, nonce->iov_len);
                break;
        case TPM2_ALG_ECC:
                if (nonce->iov_len > sizeof(template->unique.ecc.x.buffer))
                        return -EINVAL;

                /* For elliptic keys, the nonce is only used to customize the x coordinate. The y coordinate
                 * is left empty. This is consistent with section 7.4.1.1.2 (unique field for an ECC key) of
                 * the "TPM 2.0 Keys for Device Identity and Attestation" specification. */
                template->unique.ecc.x.size = nonce->iov_len;
                memcpy_safe(template->unique.ecc.x.buffer, nonce->iov_base, nonce->iov_len);
                break;
        default:
                assert_not_reached();
        }

        return 0;
}

typedef struct CreateKeyParameters {
        const char *name;
        SigningKeyType type;
        SigningScheme scheme;
        HashAlgorithm hash_alg;
        uint64_t rsa_key_bits;
        ECCCurve ecc_curve;
        uint64_t parent_handle;
        SigningKeyHierarchy hierarchy;
        uint64_t persistent_handle;
        struct iovec primary_nonce;
} CreateKeyParameters;

static void create_key_parameters_done(CreateKeyParameters *p) {
        assert(p);

        iovec_done(&p->primary_nonce);
}

static int reply_unsupported_template(sd_varlink *link, const char *parameter) {
        assert(link);

        return sd_varlink_errorbo(
                        link,
                        "io.systemd.Report.TPM2SignerKeyManager.UnsupportedTemplate",
                        SD_JSON_BUILD_PAIR_CONDITION(!!parameter, "parameter", SD_JSON_BUILD_STRING(parameter)));
}

/* Build the JSON key data for a primary key. */
static int build_primary_key_data(
                SigningKeyHierarchy hierarchy,
                const TPMT_PUBLIC *template,
                const TPM2B_NAME *name,
                sd_json_variant **ret) {
        int r;

        assert(template);
        assert(name);
        assert(ret);

        TPM2B_PUBLIC template_tpm2b = {
                .size = sizeof(TPMT_PUBLIC),
                .publicArea = *template,
        };

        _cleanup_free_ void *template_buf = NULL;
        size_t template_sz;
        r = tpm2_marshal_public(&template_tpm2b, &template_buf, &template_sz);
        if (r < 0)
                return log_error_errno(r, "Failed to marshal template for new primary signing key: %m");

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *v = NULL;
        r = sd_json_buildo(
                        &v,
                        SD_JSON_BUILD_PAIR_STRING("type", signing_key_type_to_string(SIGNING_KEY_PRIMARY)),
                        SD_JSON_BUILD_PAIR_STRING("hierarchy", signing_key_hierarchy_to_string(hierarchy)),
                        SD_JSON_BUILD_PAIR_BASE64("template", template_buf, template_sz),
                        SD_JSON_BUILD_PAIR_HEX("name", name->name, name->size));
        if (r < 0)
                return log_error_errno(r, "Failed to build signing key data: %m");

        *ret = TAKE_PTR(v);
        return 0;
}

/* Persist the transient key in the TPM and build the JSON key data for it. Note that the key has to be
 * persisted before we generate the data for it. */
static int persist_and_build_key_data(
                Tpm2Context *c,
                const Tpm2Handle *handle,
                TPMI_DH_PERSISTENT persistent_handle_index,
                sd_json_variant **ret) {
        int r;

        assert(c);
        assert(handle);
        assert(ret);

        _cleanup_(tpm2_handle_freep) Tpm2Handle *persistent_handle = NULL;
        r = tpm2_persist_handle(c, handle, /* session= */ NULL, persistent_handle_index, &persistent_handle);
        if (r < 0)
                return r;
        if (r == 0)
                return -EEXIST;

        _cleanup_(iovec_done) struct iovec handle_buf = {};
        r = tpm2_serialize(c, persistent_handle, &handle_buf);
        if (r < 0) {
                (void) tpm2_evict_handle(c, /* session= */ NULL, persistent_handle_index);
                return log_error_errno(r, "Failed to serialize persistent signing key handle: %m");
        }

        _cleanup_(sd_json_variant_unrefp) sd_json_variant *v = NULL;
        r = sd_json_buildo(
                        &v,
                        SD_JSON_BUILD_PAIR_STRING("type", signing_key_type_to_string(SIGNING_KEY_PERSISTENT)),
                        JSON_BUILD_PAIR_IOVEC_BASE64("handle", &handle_buf));
        if (r < 0) {
                (void) tpm2_evict_handle(c, /* session= */ NULL, persistent_handle_index);
                return log_error_errno(r, "Failed to build signing key data: %m");
        }

        *ret = TAKE_PTR(v);
        return 0;
}

static int vl_method_create_key(
                sd_varlink *link,
                sd_json_variant *parameters,
                sd_varlink_method_flags_t flags,
                void *userdata) {

        static const sd_json_dispatch_field dispatch_table[] = {
                { "name",             SD_JSON_VARIANT_STRING,        sd_json_dispatch_const_string,       offsetof(CreateKeyParameters, name),              SD_JSON_MANDATORY },
                { "type",             SD_JSON_VARIANT_STRING,        json_dispatch_signing_key_type,      offsetof(CreateKeyParameters, type),              SD_JSON_MANDATORY },
                { "scheme",           SD_JSON_VARIANT_STRING,        json_dispatch_signing_scheme,        offsetof(CreateKeyParameters, scheme),            SD_JSON_MANDATORY },
                { "hashAlg",          _SD_JSON_VARIANT_TYPE_INVALID, json_dispatch_hash_algorithm,        offsetof(CreateKeyParameters, hash_alg),          SD_JSON_MANDATORY },
                { "rsaKeyBits",       _SD_JSON_VARIANT_TYPE_INVALID, sd_json_dispatch_uint64,             offsetof(CreateKeyParameters, rsa_key_bits),      SD_JSON_NULLABLE },
                { "eccCurve",         SD_JSON_VARIANT_STRING,        json_dispatch_ecc_curve,             offsetof(CreateKeyParameters, ecc_curve),         SD_JSON_NULLABLE },
                { "parentHandle",     _SD_JSON_VARIANT_TYPE_INVALID, sd_json_dispatch_uint64,             offsetof(CreateKeyParameters, parent_handle),     SD_JSON_NULLABLE },
                { "hierarchy",        SD_JSON_VARIANT_STRING,        json_dispatch_signing_key_hierarchy, offsetof(CreateKeyParameters, hierarchy),         SD_JSON_NULLABLE },
                { "persistentHandle", _SD_JSON_VARIANT_TYPE_INVALID, sd_json_dispatch_uint64,             offsetof(CreateKeyParameters, persistent_handle), SD_JSON_NULLABLE },
                { "primaryNonce",     SD_JSON_VARIANT_STRING,        json_dispatch_unbase64_iovec,        offsetof(CreateKeyParameters, primary_nonce),     SD_JSON_NULLABLE },
                {}
        };

        int r;

        assert(link);
        assert(parameters);

        _cleanup_(create_key_parameters_done) CreateKeyParameters p = {
                .type = _SIGNING_KEY_TYPE_INVALID,
                .scheme = _SIGNING_SCHEME_INVALID,
                .ecc_curve = _ECC_CURVE_INVALID,
                .hierarchy = _SIGNING_KEY_HIERARCHY_INVALID,
        };

        r = sd_varlink_dispatch(link, parameters, dispatch_table, &p);
        if (r != 0)
                return r;

        /* An explicit null for uint64 fields is dispatched as UINT64_MAX. Normalize them back to their
         * unset state (0). */
        if (p.rsa_key_bits == UINT64_MAX)
                p.rsa_key_bits = 0;
        if (p.parent_handle == UINT64_MAX)
                p.parent_handle = 0;
        if (p.persistent_handle == UINT64_MAX)
                p.persistent_handle = 0;

        /* Check the mandatory fields. */
        if (p.type < 0)
                return sd_varlink_error_invalid_parameter_name(link, "type");
        if (p.scheme < 0)
                return sd_varlink_error_invalid_parameter_name(link, "scheme");

        if (!filename_is_valid(p.name))
                return sd_varlink_error_invalid_parameter_name(link, "name");

        bool is_rsa = IN_SET(p.scheme, SIGNING_SCHEME_RSASSA, SIGNING_SCHEME_RSAPSS);

        if (is_rsa) {
                if (p.rsa_key_bits == 0 || p.rsa_key_bits > UINT16_MAX)
                        return sd_varlink_error_invalid_parameter_name(link, "rsaKeyBits");
                if (p.ecc_curve >= 0)
                        return sd_varlink_error_invalid_parameter_name(link, "eccCurve");
        } else {
                if (p.ecc_curve < 0)
                        return sd_varlink_error_invalid_parameter_name(link, "eccCurve");
                if (p.rsa_key_bits != 0)
                        return sd_varlink_error_invalid_parameter_name(link, "rsaKeyBits");
        }

        /* Validate the handle/hierarchy combination for the chosen key type. */
        switch (p.type) {
        case SIGNING_KEY_ORDINARY:
                /* Must have a parentHandle. */
                if (p.parent_handle == 0)
                        return sd_varlink_error_invalid_parameter_name(link, "parentHandle");

                /* Must not specify a hierarchy or persistentHandle. */
                if (p.hierarchy >= 0)
                        return sd_varlink_error_invalid_parameter_name(link, "hierarchy");
                if (p.persistent_handle != 0)
                        return sd_varlink_error_invalid_parameter_name(link, "persistentHandle");
                break;

        case SIGNING_KEY_PERSISTENT:
                /* Exactly one of parentHandle or hierarchy must be specified. */
                if ((p.parent_handle != 0) == (p.hierarchy >= 0))
                        return sd_varlink_error_invalid_parameter_name(link, p.parent_handle != 0 ? "hierarchy" : "parentHandle");
                /* Must have a persistentHandle too. */
                if (p.persistent_handle == 0)
                        return sd_varlink_error_invalid_parameter_name(link, "persistentHandle");
                break;

        case SIGNING_KEY_PRIMARY:
                /* Must have a hierarchy. */
                if (p.hierarchy < 0)
                        return sd_varlink_error_invalid_parameter_name(link, "hierarchy");

                /* Must not have a parentHandle or persistentHandle. */
                if (p.parent_handle != 0)
                        return sd_varlink_error_invalid_parameter_name(link, "parentHandle");
                if (p.persistent_handle != 0)
                        return sd_varlink_error_invalid_parameter_name(link, "persistentHandle");
                break;

        default:
                assert_not_reached();
        }

        /* Make sure parentHandle or persistentHandle where supplied corresponds to a persistent handle. */
        if (p.parent_handle != 0 && !is_persistent_handle(p.parent_handle))
                return sd_varlink_error_invalid_parameter_name(link, "parentHandle");
        if (p.persistent_handle != 0 && !is_persistent_handle(p.persistent_handle))
                return sd_varlink_error_invalid_parameter_name(link, "persistentHandle");

        /* The key is created as a primary key whenever the type is "primary", or where the type is
         * "persistent" with "hierarchy" rather than "parentHandle". */
        bool as_primary = p.type == SIGNING_KEY_PRIMARY || (p.type == SIGNING_KEY_PERSISTENT && p.hierarchy >= 0);

        /* The unique area of the template can only be customized for primary keys. */
        if (iovec_is_set(&p.primary_nonce) && !as_primary)
                return sd_varlink_error_invalid_parameter_name(link, "primaryNonce");

        /* Build the template for the new restricted signing key. */
        TPMT_PUBLIC template;
        make_signing_key_template(
                        p.scheme,
                        hash_algorithm_to_tpm(p.hash_alg),
                        (uint16_t) p.rsa_key_bits,
                        ecc_curve_to_tpm(p.ecc_curve),
                        &template);

        /* We've already verified that primaryNonce is only set if we're creating a primary key. */
        r = signing_key_template_set_nonce(&template, &p.primary_nonce);
        if (r < 0)
                return sd_varlink_error_invalid_parameter_name(link, "primaryNonce");

        _cleanup_(tpm2_context_unrefp) Tpm2Context *c = NULL;
        r = tpm2_context_new_or_warn(/* device= */ NULL, &c);
        if (r < 0)
                return r;

        /* Check the TPM actually supports the requested template. */
        if (!tpm2_supports_alg(c, template.type))
                return reply_unsupported_template(link, "scheme");
        if (template.type == TPM2_ALG_ECC && !tpm2_supports_ecc_curve(c, template.parameters.eccDetail.curveID))
                return reply_unsupported_template(link, "eccCurve");
        if (!tpm2_test_parms(c, template.type, &template.parameters))
                return reply_unsupported_template(link, /* parameter= */ NULL);

        /* Open (creating if necessary) and exclusively lock the key directory, so that creating the key is
         * safe against signing invocations (which load the keys under the same lock). */
        _cleanup_close_ int dir_fd = xopenat_lock_full(
                        AT_FDCWD,
                        REPORT_SIGN_TPM2_PERSISTENT_DIR,
                        O_CLOEXEC|O_DIRECTORY|O_CREAT,
                        /* xopen_flags= */ 0,
                        /* mode= */ 0700,
                        LOCK_BSD,
                        LOCK_EX);
        if (dir_fd < 0)
                return log_error_errno(dir_fd, "Failed to open and lock directory '%s': %m", REPORT_SIGN_TPM2_PERSISTENT_DIR);

        _cleanup_free_ char *fname = strjoin(p.name, REPORT_SIGN_TPM2_KEY_EXT);
        if (!fname)
                return log_oom();

        if (faccessat(dir_fd, fname, F_OK, AT_SYMLINK_NOFOLLOW) >= 0)
                return sd_varlink_error(link, "io.systemd.Report.TPM2SignerKeyManager.KeyExists", /* parameters= */ NULL);
        if (errno != ENOENT)
                return log_error_errno(errno, "Failed to check whether signing key '%s' already exists: %m", fname);

        /* Now we can create the new key. */
        _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL, *parent = NULL;
        _cleanup_(Esys_Freep) TPM2B_PUBLIC *public = NULL;
        _cleanup_(Esys_Freep) TPM2B_PRIVATE *private = NULL;
        _cleanup_(Esys_Freep) TPM2B_NAME *name = NULL;

        if (as_primary) {
                /* This is the path for "primary" keys, or "persistent" keys with a hierarchy rather than
                 * parentHandle. */
                r = create_primary_key(c, p.hierarchy, &template, &name, &public, &handle);
                if (r < 0)
                        return log_error_errno(r, "Failed to create new signing key in TPM: %m");
        } else {
                /* This is the path for "ordinary" keys, or "persistent" keys with a parentHandle rather than
                 * a "hierarchy". */
                r = tpm2_index_to_handle(c, (TPM2_HANDLE) p.parent_handle, /* session= */ NULL, /* ret_name= */ NULL, &parent);
                if (r < 0)
                        return log_error_errno(r, "Failed to acquire parent handle: %m");
                if (r == 0)
                        return sd_varlink_error_invalid_parameter_name(link, "parentHandle");

                /* If parentHandle corresponds to the EK, we may require a policy session for authorization. */
                _cleanup_(tpm2_handle_freep) Tpm2Handle *session = NULL;
                r = tpm2_open_ek_user_policy_session(c, /* session= */ NULL, parent, &session);
                if (r < 0)
                        return log_error_errno(r, "Failed to open policy session for EK: %m");

                r = tpm2_create(c, parent, session, &template, /* sensitive= */ NULL, &public, &private);
                if (r < 0)
                        return log_error_errno(r, "Failed to create new signing key in TPM: %m");

                /* A persistent key must be loaded before it can be persisted below. */
                if (p.type == SIGNING_KEY_PERSISTENT) {
                        /* If parentHandle corresponds to the EK, we may require a policy session for authorization. */
                        session = tpm2_handle_free(session);
                        r = tpm2_open_ek_user_policy_session(c, /* session= */ NULL, parent, &session);
                        if (r < 0)
                                return log_error_errno(r, "Failed to open policy session for EK: %m");

                        r = tpm2_load(c, parent, session, public, private, &handle);
                        if (r < 0)
                                return log_error_errno(r, "Failed to load new signing key: %m");
                }
        }

        /* Build the JSON encoded key data to persist. */
        _cleanup_(sd_json_variant_unrefp) sd_json_variant *kd = NULL;

        switch (p.type) {
        case SIGNING_KEY_ORDINARY:
                r = build_ordinary_key_data(c, parent, public, private, &kd);
                if (r < 0)
                        return r;
                break;

        case SIGNING_KEY_PERSISTENT:
                r = persist_and_build_key_data(c, handle, (TPMI_DH_PERSISTENT) p.persistent_handle, &kd);
                if (r == -ENOSPC)
                        return sd_varlink_error(link, "io.systemd.Report.TPM2SignerKeyManager.NotEnoughSpace", /* parameters= */ NULL);
                if (r == -EEXIST)
                        return sd_varlink_error(link, "io.systemd.Report.TPM2SignerKeyManager.PersistentHandleExists", /* parameters= */ NULL);
                if (r < 0)
                        return log_error_errno(r, "Failed to persist new signing key: %m");
                break;

        case SIGNING_KEY_PRIMARY:
                r = build_primary_key_data(p.hierarchy, &template, name, &kd);
                if (r < 0)
                        return r;
                break;

        default:
                assert_not_reached();
        }

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        /* Write the key data to the persistent directory, without overwriting an existing file. */
        _cleanup_fclose_ FILE *f = NULL;
        _cleanup_free_ char *temp = NULL;
        r = fopen_tmpfile_linkable_at(dir_fd, fname, O_WRONLY, &temp, &f);
        if (r < 0) {
                if (p.type == SIGNING_KEY_PERSISTENT)
                        (void) tpm2_evict_handle(c, /* session= */ NULL, p.persistent_handle);
                return log_error_errno(r, "Failed to open signing key data file '%s/%s' for writing: %m",
                                       strnull(dir_path), fname);
        }

        CLEANUP_TMPFILE_AT(dir_fd, temp);

        r = sd_json_variant_dump(kd, SD_JSON_FORMAT_NEWLINE, f, /* prefix= */ NULL);
        if (r < 0) {
                if (p.type == SIGNING_KEY_PERSISTENT)
                        (void) tpm2_evict_handle(c, /* session= */ NULL, p.persistent_handle);
                return log_error_errno(r, "Failed to write signing key data: %m");
        }

        r = flink_tmpfile_at(f, dir_fd, temp, fname, LINK_TMPFILE_SYNC);
        if (r < 0) {
                if (p.type == SIGNING_KEY_PERSISTENT)
                        (void) tpm2_evict_handle(c, /* session= */ NULL, p.persistent_handle);
                return log_error_errno(r, "Failed to move signing key data file '%s/%s' into place: %m",
                                       strnull(dir_path), fname);
        }

        temp = mfree(temp);

        log_debug("Created signing key and saved to '%s/%s'.", strnull(dir_path), fname);

        /* Build the reply describing the new key. */
        _cleanup_(sd_json_variant_unrefp) sd_json_variant *public_json = NULL;
        r = tpm2_tpmt_public_to_json(&public->publicArea, &public_json);
        if (r < 0)
                return log_error_errno(r, "Failed to convert public area to JSON: %m");

        _cleanup_free_ char *public_pem = NULL;
        r = tpm2_tpmt_public_to_pem(&public->publicArea, &public_pem);
        if (r < 0)
                return log_error_errno(r, "Failed to convert public area to PEM: %m");

        return sd_varlink_replybo(
                        link,
                        SD_JSON_BUILD_PAIR_VARIANT("public", public_json),
                        SD_JSON_BUILD_PAIR_STRING("publicPEM", public_pem));
}

typedef struct DeleteKeyParameters {
        const char *name;
} DeleteKeyParameters;

static int vl_method_delete_key(
                sd_varlink *link,
                sd_json_variant *parameters,
                sd_varlink_method_flags_t flags,
                void *userdata) {

        static const sd_json_dispatch_field dispatch_table[] = {
                { "name", SD_JSON_VARIANT_STRING, sd_json_dispatch_const_string, offsetof(DeleteKeyParameters, name), SD_JSON_MANDATORY },
                {}
        };

        DeleteKeyParameters p = {};
        int r;

        assert(link);
        assert(parameters);

        r = sd_varlink_dispatch(link, parameters, dispatch_table, &p);
        if (r != 0)
                return r;

        if (!filename_is_valid(p.name))
                return sd_varlink_error_invalid_parameter_name(link, "name");

        _cleanup_free_ char *key_fname = strjoin(p.name, REPORT_SIGN_TPM2_KEY_EXT);
        _cleanup_free_ char *voucher_fname = strjoin(p.name, REPORT_SIGN_TPM2_VOUCHER_EXT);
        _cleanup_free_ char *context_fname = strjoin(p.name, REPORT_SIGN_TPM2_KEYCONTEXT_EXT);
        if (!key_fname || !voucher_fname || !context_fname)
                return log_oom();

        /* Lock the runtime directory and then the persistent directory, both exclusively. We take the two
         * locks in the same order as the signing path (runtime first, then persistent) to avoid deadlocking. */
        _cleanup_close_ int runtime_dir_fd = xopenat_lock_full(
                        AT_FDCWD,
                        REPORT_SIGN_TPM2_RUNTIME_DIR,
                        O_CLOEXEC|O_DIRECTORY|O_CREAT,
                        /* xopen_flags= */ 0,
                        /* mode= */ 0700,
                        LOCK_BSD,
                        LOCK_EX);
        if (runtime_dir_fd < 0)
                return log_error_errno(runtime_dir_fd, "Failed to open and lock directory '%s': %m", REPORT_SIGN_TPM2_RUNTIME_DIR);

        _cleanup_close_ int dir_fd = xopenat_lock_full(
                        AT_FDCWD,
                        REPORT_SIGN_TPM2_PERSISTENT_DIR,
                        O_CLOEXEC|O_DIRECTORY|O_CREAT,
                        /* xopen_flags= */ 0,
                        /* mode= */ 0700,
                        LOCK_BSD,
                        LOCK_EX);
        if (dir_fd < 0)
                return log_error_errno(dir_fd, "Failed to open and lock directory '%s': %m", REPORT_SIGN_TPM2_PERSISTENT_DIR);

        /* Check that the key exists. */
        if (faccessat(dir_fd, key_fname, F_OK, AT_SYMLINK_NOFOLLOW) < 0) {
                if (errno == ENOENT)
                        return sd_varlink_error(link, "io.systemd.Report.TPM2SignerKeyManager.NoSuchKey", /* parameters= */ NULL);
                return log_error_errno(errno, "Failed to check whether signing key '%s' exists: %m", key_fname);
        }

        /* Load the key data so we know its type, and for persistent keys the handle we may need to evict. */
        _cleanup_(signing_key_data_freep) SigningKeyData *data = new0(SigningKeyData, 1);
        if (!data)
                return log_oom();

        r = load_signing_key_data(dir_fd, key_fname, data);
        if (r < 0)
                return r;

        /* For a persistent key, evict the corresponding TPM object too as long as the object matches the
         * persistent handle stored in the key file. */
        if (data->type == SIGNING_KEY_PERSISTENT) {
                _cleanup_(tpm2_context_unrefp) Tpm2Context *c = NULL;
                r = tpm2_context_new_or_warn(/* device= */ NULL, &c);
                if (r < 0)
                        return r;

                _cleanup_(tpm2_handle_freep) Tpm2Handle *handle = NULL;
                r = acquire_persistent_key(c, &data->handle, &handle);
                if (r < 0)
                        log_warning_errno(r, "Persistent object for signing key '%s' is missing or no longer matches, not evicting it: %m", p.name);
                else {
                        TPM2_HANDLE index;
                        r = tpm2_index_from_handle(c, handle, &index);
                        if (r < 0)
                                /* Note that this fails on versions of tss2 that don't have Esys_TR_GetTpmHandle. */
                                return log_error_errno(r, "Failed to determine persistent handle for signing key '%s': %m", p.name);

                        r = tpm2_evict_handle(c, /* session= */ NULL, index);
                        if (r < 0)
                                return log_error_errno(r, "Failed to evict persistent object for signing key '%s': %m", p.name);
                }
        }

        _cleanup_free_ char *dir_path = NULL;
        (void) fd_get_path(dir_fd, &dir_path);

        /* Remove the key file and its optional voucher from the persistent directory. */
        if (unlinkat(dir_fd, key_fname, 0) < 0)
                return log_error_errno(errno, "Failed to remove signing key data file '%s/%s': %m", strnull(dir_path), key_fname);

        if (unlinkat(dir_fd, voucher_fname, 0) < 0 && errno != ENOENT)
                return log_error_errno(errno, "Failed to remove signing key voucher '%s/%s': %m", strnull(dir_path), voucher_fname);

        /* Remove the cached key context from the runtime directory. */
        if (unlinkat(runtime_dir_fd, context_fname, 0) < 0 && errno != ENOENT)
                return log_error_errno(errno, "Failed to remove signing key context '%s': %m", context_fname);

        log_debug("Deleted signing key '%s'.", p.name);

        return sd_varlink_reply(link, /* parameters= */ NULL);
}

static int vl_server(void) {
        _cleanup_(sd_varlink_server_unrefp) sd_varlink_server *vs = NULL;
        int r;

        r = varlink_server_new(&vs, SD_VARLINK_SERVER_ROOT_ONLY|SD_VARLINK_SERVER_MYSELF_ONLY, /* userdata= */ NULL);
        if (r < 0)
                return log_error_errno(r, "Failed to allocate Varlink server: %m");

        r = sd_varlink_server_add_interface_many(vs,
                        &vl_interface_io_systemd_Report_Signer,
                        &vl_interface_io_systemd_Report_TPM2SignerKeyManager);
        if (r < 0)
                return log_error_errno(r, "Failed to add Varlink interface: %m");

        r = sd_varlink_server_bind_method_many(
                        vs,
                        "io.systemd.Report.Signer.Sign", vl_method_sign,
                        "io.systemd.Report.TPM2SignerKeyManager.CreateKey", vl_method_create_key,
                        "io.systemd.Report.TPM2SignerKeyManager.DeleteKey", vl_method_delete_key);
        if (r < 0)
                return log_error_errno(r, "Failed to bind Varlink methods: %m");

        r = sd_varlink_server_loop_auto(vs);
        if (r < 0)
                return log_error_errno(r, "Failed to run Varlink event loop: %m");

        return 0;
}

static int parse_argv(int argc, char *argv[]) {
        int r;

        assert(argc >= 0);
        assert(argv);

        OptionParser opts = { argc, argv };

        FOREACH_OPTION_OR_RETURN(c, &opts)
                switch (c) {
                OPTION_COMMON_HELP:
                        return command_print_help();

                OPTION_COMMON_VERSION:
                        return version();

                OPTION_COMMON_INTROSPECT_CLI:
                        return introspect_cli(SD_JSON_FORMAT_OFF);
                }

        if (option_parser_get_n_args(&opts) > 0)
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "This program takes no arguments.");

        r = sd_varlink_invocation(SD_VARLINK_ALLOW_ACCEPT);
        if (r < 0)
                return log_error_errno(r, "Failed to check if invoked in Varlink mode: %m");
        if (r == 0)
                return log_error_errno(SYNTHETIC_ERRNO(EINVAL),
                                       "This program can only run as a Varlink service.");

        return 1;
}

static int run(int argc, char *argv[]) {
        int r;

        TPM2_NOTE(suggested);
        LIBCRYPTO_NOTE(suggested);

        log_setup();

        r = parse_argv(argc, argv);
        if (r <= 0)
                return r;

        return vl_server();
}

DEFINE_MAIN_FUNCTION(run);
