.TH ATA_ID 8 "November 2005" "" "Linux Administrator's Manual"
.SH NAME
ata_id \- udev callout to read product/serial number from ATA drives
.SH SYNOPSIS
.BI ata_id
[\fI--export\fP] \fIblockdevice\fP
.SH "DESCRIPTION"
.B ata_id
is normally called from a udev rule, to provide udev with a unique string and
additional information (uuid, label) for an ATA drive. Udev can use this
information to create symlinks in /dev/disk/by-id and /dev/disk/by-label
to the real device node.
.SH USAGE
.B ata_id
opens the blockdevice node specified at the commandline and prints the
information chosen by the options.
.SH OPTIONS
The following commandline switches are supported to specify what ata_id
should print:
.TP
.BI --export
print all values (instead of only the id)
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Kay Sievers <kay.sievers@vrfy.org>.

