# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Content]
Packages=
        btrfs-progs
        coreutils
        device-mapper
        e2fsprogs
        musl-utils
        tpm2-tools
        # For TEST-92-TPM2-SWTPM, install following packages when
        # https://github.com/systemd/systemd/pull/42760
        # https://gitlab.alpinelinux.org/alpine/aports/-/work_items/18293
        # are resolved.
        #gnutls-utils
        #kmod
        #linux-firmware-none
        #linux-stable

VolatilePackages=
        systemd
        systemd-journald
        systemd-libs
        systemd-udevd
