.TH MODEM_MODESWITCH 8 "November 2005" "" "Linux Administrator's Manual"
.SH NAME
modem-modeswitch \- udev callout to switch mobile broadband devices to their
intended modem mode
.SH SYNOPSIS
.BI modem-modeswitch
\fI--vendor <vendor id>\fP \fI--product <product id>\fP [\fI--debug\fP]
\fI--type <type>\fP \fI<devpath>\fP
.SH "DESCRIPTION"
.B modem-modeswitch
is normally called from a udev rule, to eject the driver CD that many mobile
broadband devices mount by default, and switch them into modem mode.
.SH USAGE
.B modem-modeswitch
switches the device into modem mode
.SH OPTIONS
The following commandline switches are supported:
.TP
.BI \-\-vendor\ <vid>
the USB vendor ID of the mobile broadband device to switch
.TP
.BI \-\-product\ <pid>
the USB product ID of the mobile broadband device to switch
.TP
.BI \-\-type\ <type>
the type of switch to perform (one of: option-zerocd, mobile-action-8280p)
.TP
.BI \-\-log\ <file>
log verbose debugging information about the switching process
.TP
.BI \-\-debug
print verbose debugging information about the switching process
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Dan Williams <dcbw@redhat.com> based off code by Peter Henn
<p.henn@option.com>.

