# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|centos
Distribution=|fedora

[Content]
ExtraTrees=../../testsuite-13-container-template-init:/usr/lib/systemd/tests/testdata/testsuite-13-container-template/usr/sbin/init
Packages=
        bind-utils
        device-mapper-event
        device-mapper-multipath
        hostname
        iscsi-initiator-utils
        logger
        kernel-modules # for megasas2 raid modules
        tpm2-tools
        veritysetup
