/* SPDX-License-Identifier: LGPL-2.1+ */
#pragma once

#include "macro.h"
#include "sd-bus.h"

typedef enum mac_selinux_logind_permission {
        MAC_SELINUX_LOGIND_RAWSET,
        MAC_SELINUX_LOGIND_RAWSTATUS,
        MAC_SELINUX_LOGIND_GETSESSION,
        MAC_SELINUX_LOGIND_GETSESSIONBYPID = MAC_SELINUX_LOGIND_GETSESSION,
        MAC_SELINUX_LOGIND_GETUSER,
        MAC_SELINUX_LOGIND_GETUSERBYPID = MAC_SELINUX_LOGIND_GETUSER,
        MAC_SELINUX_LOGIND_GETSEAT,
        MAC_SELINUX_LOGIND_LISTSESSIONS,
        MAC_SELINUX_LOGIND_LISTUSERS,
        MAC_SELINUX_LOGIND_LISTSEATS,
        MAC_SELINUX_LOGIND_LISTINHIBITORS,
        MAC_SELINUX_LOGIND_CREATESESSION,
        MAC_SELINUX_LOGIND_RELEASESESSION,
        MAC_SELINUX_LOGIND_ACTIVATESESSION,
        MAC_SELINUX_LOGIND_ACTIVATESESSIONONSEAT = MAC_SELINUX_LOGIND_ACTIVATESESSION,
        MAC_SELINUX_LOGIND_LOCKSESSION,
        MAC_SELINUX_LOGIND_LOCKSESSIONS,
        MAC_SELINUX_LOGIND_TERMINATESESSION,
        MAC_SELINUX_LOGIND_KILLSESSION = MAC_SELINUX_LOGIND_TERMINATESESSION,
        MAC_SELINUX_LOGIND_TERMINATEUSER,
        MAC_SELINUX_LOGIND_KILLUSER = MAC_SELINUX_LOGIND_TERMINATEUSER,
        MAC_SELINUX_LOGIND_TERMINATESEAT,
        MAC_SELINUX_LOGIND_SETUSERLINGER,
        MAC_SELINUX_LOGIND_ATTACHDEVICE,
        MAC_SELINUX_LOGIND_FLUSHDEVICES,
        MAC_SELINUX_LOGIND_REBOOT,
        MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_POWEROFF = MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_SUSPEND = MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_HIBERNATE = MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_HYBRIDSLEEP = MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_SUSPENDTHENHIBERNATE = MAC_SELINUX_LOGIND_HALT,
        MAC_SELINUX_LOGIND_SCHEDULESHUTDOWN,
        MAC_SELINUX_LOGIND_CANCELSCHEDULEDSHUTDOWN,
        MAC_SELINUX_LOGIND_SETREBOOTPARAMETER,
        MAC_SELINUX_LOGIND_SETREBOOTTOFIRMWARESETUP,
        MAC_SELINUX_LOGIND_SETREBOOTTOBOOTLOADERMENU,
        MAC_SELINUX_LOGIND_SETREBOOTTOBOOTLOADERENTRY,
        MAC_SELINUX_LOGIND_SETWALLMESSAGE,
        MAC_SELINUX_LOGIND_INHIBIT,
        MAC_SELINUX_LOGIND_SWITCHSEATTO,
        MAC_SELINUX_LOGIND_SWITCHSEATTONEXT = MAC_SELINUX_LOGIND_SWITCHSEATTO,
        MAC_SELINUX_LOGIND_SWITCHSEATTOPREV = MAC_SELINUX_LOGIND_SWITCHSEATTO,
        MAC_SELINUX_LOGIND_SETIDLEHINT,
        MAC_SELINUX_LOGIND_SETLOCKEDHINT,
        MAC_SELINUX_LOGIND_TAKECONTROL,
        MAC_SELINUX_LOGIND_RELEASECONTROL,
        MAC_SELINUX_LOGIND_TAKEDEVICE,
        MAC_SELINUX_LOGIND_RELEASEDEVICE,
        MAC_SELINUX_LOGIND_PAUSEDEVICECOMPLETE,
        MAC_SELINUX_LOGIND_SETBRIGHTNESS,

        _MAC_SELINUX_LOGIND_PERMISSION_MAX
} mac_selinux_logind_permission;

#if HAVE_SELINUX

int _mac_selinux_logind_access_check_internal(
                sd_bus_message *message,
                mac_selinux_logind_permission permission,
                sd_bus_error *error,
                const char *func);

#define mac_selinux_logind_access_check(message, permission, error) \
        _mac_selinux_logind_access_check_internal((message), (permission), (error), __func__)

#else /* HAVE_SELINUX */

static inline int mac_selinux_logind_access_check(
                sd_bus_message *message,
                mac_selinux_logind_permission permission,
                sd_bus_error *error) {
        return 0;
}

#endif /* HAVE_SELINUX */
