/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma once

#include "forward.h"

/* Helpers for maintaining local measurement event logs (e.g. /run/log/systemd/tpm2-measure.log):
 * append-only files of JSON records in RFC 7464 application/json-seq format, protected against concurrent
 * writers via BSD file locks and against torn writes via a sticky bit marker. The records implement a
 * subset of the TCG Canonical Event Log Format, JSON flavour, see the comment in measurement_log_append()
 * for the deviations.
 *
 * Record construction is up to the callers. By convention they set the 'content_type' field to "systemd"
 * to make clear the data is generated by us, and include various interesting fields in the 'content'
 * subobject, including a CLOCK_BOOTTIME timestamp which can be used to order a measurement against
 * possibly other measurements independently done by other subsystems on the system.
 *
 * All functions are best-effort: they log at debug level and return a negative errno on failure, but
 * callers are expected to proceed with their measurement regardless. A broken log shall never fail a
 * measurement. The functions taking an fd silently do nothing if it is negative, so that a failed
 * measurement_log_open() doesn't cause complaints from every subsequent call.
 *
 * Expected sequence:
 *
 *     reset_marker = dirty() >= 0 → <update the measurement register> → append(record, reset_marker)
 *
 * after an open(). Callers capture reset_marker from dirty() and pass it on, so that a marker inherited
 * from an earlier, incomplete writer is preserved rather than cleared. If updating the register fails,
 * callers shall return without cleaning: the sticky bit then persists and marks the log as unable to
 * explain the register state. */

/* The type of a measurement event, encoded in the 'eventType' field of the records' 'content' subobject.
 * The corresponding strings are part of the on-disk log format (and accepted by systemd-pcrextend's
 * --event-type= switch), hence must remain stable. */
typedef enum UserspaceMeasurementEventType {
        USERSPACE_MEASUREMENT_EVENT_PHASE,
        USERSPACE_MEASUREMENT_EVENT_FILESYSTEM,
        USERSPACE_MEASUREMENT_EVENT_VOLUME_KEY,
        USERSPACE_MEASUREMENT_EVENT_MACHINE_ID,
        USERSPACE_MEASUREMENT_EVENT_PRODUCT_ID,
        USERSPACE_MEASUREMENT_EVENT_KEYSLOT,
        USERSPACE_MEASUREMENT_EVENT_NVPCR_INIT,
        USERSPACE_MEASUREMENT_EVENT_NVPCR_SEPARATOR,
        USERSPACE_MEASUREMENT_EVENT_DM_VERITY,
        USERSPACE_MEASUREMENT_EVENT_IMDS_USERDATA,
        USERSPACE_MEASUREMENT_EVENT_OS_SEPARATOR,
        USERSPACE_MEASUREMENT_EVENT_LOGIN,
        _USERSPACE_MEASUREMENT_EVENT_TYPE_MAX,
        _USERSPACE_MEASUREMENT_EVENT_TYPE_INVALID = -EINVAL,
} UserspaceMeasurementEventType;

DECLARE_STRING_TABLE_LOOKUP(userspace_measurement_event_type, UserspaceMeasurementEventType);

/* Opens the log file for appending, creating it (and its parent directories) if necessary, and takes an
 * exclusive BSD file lock on it. Open the log before updating a measurement register, so that no other
 * cooperating process can come between the update and the matching log record. */
int measurement_log_open(const char *path);

/* Marks the log as "register update in flight" by setting the sticky bit on it, to be cleared again once
 * the matching record has been written. Call this right before updating the register, and not earlier, so
 * that failures in fallible preparation work don't leave a stale marker behind. Returns -ESTALE if the
 * marker is already set, i.e. an earlier writer died mid-update and the log hence doesn't explain the
 * register state anymore. */
int measurement_log_dirty(int fd);

/* Syncs the log and clears the dirty marker again. Called implicitly by measurement_log_append();
 * call it directly only when an update is recorded by other means than a log record (see
 * tpm2_nvpcr_initialize(), which publishes an anchor file instead, as the extend value must stay
 * confidential). */
int measurement_log_clean(int fd, bool reset_marker);

/* Appends one record to the log and clears the dirty marker again. */
int measurement_log_append(int fd, sd_json_variant *record, bool reset_marker);
