/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma once

#include <sys/uio.h>

#include "forward.h"

/* SSH agent signature request flags, see PROTOCOL.agent. */
#define SSH_AGENT_RSA_SHA2_256 0x00000002u
#define SSH_AGENT_RSA_SHA2_512 0x00000004u

/* The ssh_wire_*() functions encode and decode the SSH wire format from RFC 4251 §5. The append
 * functions grow an iovec that owns its memory. The read functions advance the iovec past the bytes
 * that they read, so pass them a view into a buffer, never the owning iovec. */

int ssh_wire_append_u32(struct iovec *iovec, uint32_t v);
/* ssh_wire_append_string() appends the length of `s` as uint32, followed by the bytes of `s`. */
int ssh_wire_append_string(struct iovec *iovec, const struct iovec *s);
/* Appends a positive BIGNUM as SSH mpint. Only available under HAVE_OPENSSL. */
int ssh_wire_append_mpint(struct iovec *iovec, const BIGNUM *bn);

int ssh_wire_read_u32(struct iovec *iovec, uint32_t *ret);
/* The returned iovec points into the memory of `iovec`. */
int ssh_wire_read_string(struct iovec *iovec, struct iovec *ret);

typedef enum OpenSSHKeyType {
        OPENSSH_KEY_TYPE_ED25519,
        OPENSSH_KEY_TYPE_RSA,
        OPENSSH_KEY_TYPE_ECDSA_P256,
        _OPENSSH_KEY_TYPE_MAX,
        _OPENSSH_KEY_TYPE_INVALID = -EINVAL,
} OpenSSHKeyType;

/* SSH wire-format type tag — "ssh-ed25519", "ssh-rsa", "ecdsa-sha2-nistp256". */
DECLARE_STRING_TABLE_LOOKUP(openssh_key_type, OpenSSHKeyType);

/* Name accepted by `ssh-keygen -t` — "ed25519", "rsa", "ecdsa". */
DECLARE_STRING_TABLE_LOOKUP(openssh_key_keygen_type, OpenSSHKeyType);

typedef struct OpenSSHKey {
        OpenSSHKeyType type;
        EVP_PKEY *pkey;
        struct iovec pubkey_blob; /* pubkey_blob contains the public key in SSH wire format. */
        char *comment;
} OpenSSHKey;

/* Invokes `ssh-keygen` synchronously to generate an unencrypted key pair. The private key
 * is written to `priv_path` in PEM/PKCS#8 format (so OpenSSL can read it via
 * openssl_load_private_key_from_file()); the matching ".pub" file is written next to it in
 * the usual OpenSSH text format. */
int openssh_key_generate(const char *priv_path, OpenSSHKeyType type);

/* Parses an OpenSSH-format public key file ("ssh-ed25519 AAAA… comment") and returns
 * the key type, the SSH wire-format pubkey blob, and the comment. */
int openssh_pubkey_load(
                const char *pub_path,
                OpenSSHKeyType *ret_type,
                struct iovec *ret_blob,
                char **ret_comment);

/* Loads an SSH key pair: the private key from `priv_path` (must be PEM/PKCS#8, as
 * generated by openssh_key_generate()), and the SSH wire-format public-key blob plus
 * comment from `pub_path` (the regular OpenSSH "ssh-ed25519 AAAA… comment" format). */
int openssh_key_load(const char *priv_path, const char *pub_path, OpenSSHKey **ret);

/* Signs `data` with the loaded private key. `flags` is the agent SIGN_REQUEST flags
 * field (only RSA_SHA2_* bits are honored; ignored for ed25519/ecdsa). Returns the
 * inner SSH-format signature blob: string type-name || string sig. */
int openssh_key_sign(OpenSSHKey *k, uint32_t flags, const struct iovec *data, struct iovec *ret);

OpenSSHKey* openssh_key_free(OpenSSHKey *k);
DEFINE_TRIVIAL_CLEANUP_FUNC(OpenSSHKey*, openssh_key_free);
