/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma once

#include "shared-forward.h"

/* SSH agent signature request flags, see PROTOCOL.agent. */
#define SSH_AGENT_RSA_SHA2_256 0x00000002u
#define SSH_AGENT_RSA_SHA2_512 0x00000004u

/* --- SSH wire-format helpers (RFC 4251 §5).
 *
 * Both readers and writers operate on byte buffers. The writer (SshWireBuf) owns a heap
 * buffer and grows it via GREEDY_REALLOC; callers can append fixed primitives, raw bytes,
 * length-prefixed strings, or SSH mpints (positive BIGNUMs encoded big-endian with a
 * possible leading-zero pad). The reader (SshWireCursor) is a non-owning view over a
 * received buffer with a position. */

typedef struct SshWireBuf {
        uint8_t *data;
        size_t size;
} SshWireBuf;

/* Frees the internal storage; the SshWireBuf itself is owned by the caller. Use directly
 * as `_cleanup_(ssh_wire_buf_done) SshWireBuf b = {};`. */
void ssh_wire_buf_done(SshWireBuf *b);

int ssh_wire_buf_append_byte(SshWireBuf *b, uint8_t v);
int ssh_wire_buf_append_u32(SshWireBuf *b, uint32_t v);
/* Appends `n` raw bytes verbatim (no length prefix). */
int ssh_wire_buf_append_bytes(SshWireBuf *b, const void *p, size_t n);
/* Appends `uint32(n) || bytes`. If `n == SIZE_MAX`, `p` is treated as a NUL-terminated
 * string and its length is determined via strlen() — useful for string literals. */
int ssh_wire_buf_append_string(SshWireBuf *b, const void *p, size_t n);
/* Appends a positive BIGNUM as SSH mpint. Only available under HAVE_OPENSSL. */
int ssh_wire_buf_append_mpint(SshWireBuf *b, const BIGNUM *bn);

typedef struct SshWireCursor {
        const uint8_t *data;
        size_t size;
        size_t pos;
} SshWireCursor;

int ssh_wire_cursor_read_u32(SshWireCursor *c, uint32_t *ret);
int ssh_wire_cursor_read_string(SshWireCursor *c, const uint8_t **ret_data, size_t *ret_size);

/* --- OpenSSH key format. */

typedef enum OpenSSHKeyType {
        OPENSSH_KEY_TYPE_ED25519,
        OPENSSH_KEY_TYPE_RSA,
        OPENSSH_KEY_TYPE_ECDSA_P256,
        _OPENSSH_KEY_TYPE_MAX,
        _OPENSSH_KEY_TYPE_INVALID = -EINVAL,
} OpenSSHKeyType;

/* SSH wire-format type tag — "ssh-ed25519", "ssh-rsa", "ecdsa-sha2-nistp256". */
DECLARE_STRING_TABLE_LOOKUP(openssh_key_type, OpenSSHKeyType);

/* Name accepted by `ssh-keygen -t` — "ed25519", "rsa", "ecdsa". */
DECLARE_STRING_TABLE_LOOKUP(openssh_key_keygen_type, OpenSSHKeyType);

typedef struct OpenSSHKey {
        OpenSSHKeyType type;
        EVP_PKEY *pkey;
        void *pubkey_blob;       /* SSH wire-format public-key blob */
        size_t pubkey_blob_size;
        char *comment;
} OpenSSHKey;

/* Invokes `ssh-keygen` synchronously to generate an unencrypted key pair. The private key
 * is written to `priv_path` in PEM/PKCS#8 format (so OpenSSL can read it via
 * openssl_load_private_key_from_file()); the matching ".pub" file is written next to it in
 * the usual OpenSSH text format. */
int openssh_key_generate(const char *priv_path, OpenSSHKeyType type);

/* Parses an OpenSSH-format public key file ("ssh-ed25519 AAAA… comment") and returns
 * the key type, the SSH wire-format pubkey blob, and the comment. */
int openssh_pubkey_load(
                const char *pub_path,
                OpenSSHKeyType *ret_type,
                void **ret_blob,
                size_t *ret_blob_size,
                char **ret_comment);

/* Loads an SSH key pair: the private key from `priv_path` (must be PEM/PKCS#8, as
 * generated by openssh_key_generate()), and the SSH wire-format public-key blob plus
 * comment from `pub_path` (the regular OpenSSH "ssh-ed25519 AAAA… comment" format). */
int openssh_key_load(const char *priv_path, const char *pub_path, OpenSSHKey **ret);

/* Signs `data` with the loaded private key. `flags` is the agent SIGN_REQUEST flags
 * field (only RSA_SHA2_* bits are honored; ignored for ed25519/ecdsa). Returns the
 * inner SSH-format signature blob: string type-name || string sig. */
int openssh_key_sign(
                OpenSSHKey *k,
                uint32_t flags,
                const void *data,
                size_t size,
                void **ret_blob,
                size_t *ret_blob_size);

OpenSSHKey* openssh_key_free(OpenSSHKey *k);
DEFINE_TRIVIAL_CLEANUP_FUNC(OpenSSHKey*, openssh_key_free);
