/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include "varlink-io.systemd.Manager.h"

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                RateLimit,
                SD_VARLINK_FIELD_COMMENT("The ratelimit interval"),
                SD_VARLINK_DEFINE_FIELD(intervalUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The ratelimit burst"),
                SD_VARLINK_DEFINE_FIELD(burst, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ResourceLimit,
                SD_VARLINK_FIELD_COMMENT("The soft resource limit"),
                SD_VARLINK_DEFINE_FIELD(soft, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The hard resource limit burst"),
                SD_VARLINK_DEFINE_FIELD(hard, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Timestamp,
                SD_VARLINK_FIELD_COMMENT("Timestamp in µs in the CLOCK_REALTIME clock (wallclock)"),
                SD_VARLINK_DEFINE_FIELD(realtime, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp in µs in the CLOCK_MONOTONIC clock"),
                SD_VARLINK_DEFINE_FIELD(monotonic, SD_VARLINK_INT, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ManagerContext,
                SD_VARLINK_FIELD_COMMENT("The version string of the running systemd instance"),
                SD_VARLINK_DEFINE_FIELD(version, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The features that have been enabled and disabled for this build"),
                SD_VARLINK_DEFINE_FIELD(features, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the architecture the systemd instance is running on"),
                SD_VARLINK_DEFINE_FIELD(architecture, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the virtualization technology the system runs in"),
                SD_VARLINK_DEFINE_FIELD(virtualization, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the confidential virtualization technology the system runs in"),
                SD_VARLINK_DEFINE_FIELD(confidentialVirtualization, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("An array of strings describing the taints applied to the running system"),
                SD_VARLINK_DEFINE_FIELD(taints, SD_VARLINK_STRING, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The console on which systemd asks for confirmation when spawning processes"),
                SD_VARLINK_DEFINE_FIELD(confirmSpawn, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether systemd will show status messages on the system console"),
                SD_VARLINK_DEFINE_FIELD(showStatus, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The unit search path"),
                SD_VARLINK_DEFINE_FIELD(unitPath, SD_VARLINK_STRING, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The default standard output for units"),
                SD_VARLINK_DEFINE_FIELD(defaultStandardOutput, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default standard error for units"),
                SD_VARLINK_DEFINE_FIELD(defaultStandardError, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog pretimeout"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogPreUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog pretimeout governor"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogPreGovernor, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The reboot watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(rebootWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The kexec watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(kexecWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether service watchdogs are enabled"),
                SD_VARLINK_DEFINE_FIELD(serviceWatchdogs, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default timer accuracy"),
                SD_VARLINK_DEFINE_FIELD(defaultTimerAccuracyUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit start timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutStartUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit stop timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutStopUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit abort timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutAbortUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default device timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultDeviceTimeoutUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default interval between unit restarts"),
                SD_VARLINK_DEFINE_FIELD(defaultRestartUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default start rate limit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultStartLimit, RateLimit, 0),
                SD_VARLINK_FIELD_COMMENT("Whether CPU accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultCPUAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether block IO accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultBlockIOAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether IO accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultIOAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether IP accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultIPAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether memory accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether tasks accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultTasksAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum CPU time"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitCPU, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitFSIZE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum data segment size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitDATA, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum stack size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitSTACK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum core file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitCORE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum resident set size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRSS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of open files"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNOFILE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of address space"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitAS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of processes"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNPROC, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of locked memory"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitMEMLOCK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of file locks"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitLOCKS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of pending signals"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitSIGPENDING, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of messages"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitMSGQUEUE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum nice level"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNICE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum realtime priority"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRTPRIO, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum realtime deadline"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRTTIME, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of tasks"),
                SD_VARLINK_DEFINE_FIELD(defaultTasksMax, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default threshold for checking memory pressure"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryPressureThresholdUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default memory pressure watch"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryPressureWatch, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default timer slack"),
                SD_VARLINK_DEFINE_FIELD(timerSlackNSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default out-of-memory policy"),
                SD_VARLINK_DEFINE_FIELD(defaultOOMPolicy, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default out-of-memory score adjustment"),
                SD_VARLINK_DEFINE_FIELD(defaultOOMScoreAdjust, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The ctrl+alt+del burst action"),
                SD_VARLINK_DEFINE_FIELD(ctrlAltDelBurstAction, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ManagerRuntime,
                SD_VARLINK_FIELD_COMMENT("Timestamp when the firmware first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(firmwareTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the boot loader first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(loaderTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the kernel first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(kernelTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the initrd first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the initrd first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(userspaceTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the system finished booting up"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(finishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started uploading security policies to the kernel"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(securityStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished uploading security policies to the kernel"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(securityFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started executing generators"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(generatorsStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished executing generators"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(generatorsFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first started loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first finished loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager last started loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started uploading security policies to the kernel in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdSecurityStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished uploading security policies to the kernel in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdSecurityFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started executing generators in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdGeneratorsStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished executing generators in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdGeneratorsFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first started loading units in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdUnitsLoadStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first finished loading units in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdUnitsLoadFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The current log level of the manager"),
                SD_VARLINK_DEFINE_FIELD(logLevel, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The current log target of the manager"),
                SD_VARLINK_DEFINE_FIELD(logTarget, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of unique unit names currently loaded"),
                SD_VARLINK_DEFINE_FIELD(nNames, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of failed units"),
                SD_VARLINK_DEFINE_FIELD(nFailedUnits, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of currently queued jobs"),
                SD_VARLINK_DEFINE_FIELD(nJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The total amount of queued jobs"),
                SD_VARLINK_DEFINE_FIELD(nInstalledJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The total amount of failed jobs"),
                SD_VARLINK_DEFINE_FIELD(nFailedJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("Boot progress as a floating point value between 0.0 and 1.0"),
                SD_VARLINK_DEFINE_FIELD(progress, SD_VARLINK_FLOAT, 0),
                SD_VARLINK_FIELD_COMMENT("The manager environment variables"),
                SD_VARLINK_DEFINE_FIELD(environment, SD_VARLINK_STRING, SD_VARLINK_MAP),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog device currently in use"),
                SD_VARLINK_DEFINE_FIELD(watchdogDevice, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the hardware watchdog was last pinged"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(watchdogLastPingTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Root of the control group hierarchy that the manager is running in"),
                SD_VARLINK_DEFINE_FIELD(controlGroup, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Current state of the system"),
                SD_VARLINK_DEFINE_FIELD(systemState, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Exit code of the manager"),
                SD_VARLINK_DEFINE_FIELD(exitCode, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Manager,
                SD_VARLINK_FIELD_COMMENT("Configuration of the manager"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(context, ManagerContext, 0),
                SD_VARLINK_FIELD_COMMENT("Runtime information of the manager"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(runtime, ManagerRuntime, 0));

static SD_VARLINK_DEFINE_METHOD(
                Describe,
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(manager, Manager, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                JobUnit,
                SD_VARLINK_FIELD_COMMENT("The unit ID"),
                SD_VARLINK_DEFINE_FIELD(id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The unit path"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ActivationDetails,
                SD_VARLINK_DEFINE_FIELD(key, SD_VARLINK_STRING, 0),
                SD_VARLINK_DEFINE_FIELD(value, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Job,
                SD_VARLINK_FIELD_COMMENT("The job ID"),
                SD_VARLINK_DEFINE_FIELD(id, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The unit associated with the job"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unit, JobUnit, 0),
                SD_VARLINK_FIELD_COMMENT("The job type"),
                SD_VARLINK_DEFINE_FIELD(jobType, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The job state"),
                SD_VARLINK_DEFINE_FIELD(state, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The job activation details"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(activationDetails, ActivationDetails, SD_VARLINK_NULLABLE|SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_ERROR(NoSuchJob);

static SD_VARLINK_DEFINE_METHOD(
                DescribeJobs,
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(job, Job, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Condition,
                SD_VARLINK_FIELD_COMMENT("The condition type"),
                SD_VARLINK_DEFINE_FIELD(type, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the condition is a triggering condition"),
                SD_VARLINK_DEFINE_FIELD(trigger, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the result of the condition is negated"),
                SD_VARLINK_DEFINE_FIELD(negate, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The parameter passed to the condition"),
                SD_VARLINK_DEFINE_FIELD(parameter, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupIODeviceWeight,
                SD_VARLINK_FIELD_COMMENT("The device path"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The device IO weight"),
                SD_VARLINK_DEFINE_FIELD(weight, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupIODeviceLimit,
                SD_VARLINK_FIELD_COMMENT("The device path"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The device IO limit"),
                SD_VARLINK_DEFINE_FIELD(limit, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupIODeviceLatency,
                SD_VARLINK_FIELD_COMMENT("The device path"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The device target latency"),
                SD_VARLINK_DEFINE_FIELD(targetUSec, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupDeviceAllow,
                SD_VARLINK_FIELD_COMMENT("The device path"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The device permissions"),
                SD_VARLINK_DEFINE_FIELD(permissions, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupTasksMax,
                SD_VARLINK_FIELD_COMMENT("The maximum amount of tasks"),
                SD_VARLINK_DEFINE_FIELD(value, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The scaling factor"),
                SD_VARLINK_DEFINE_FIELD(scale, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupAddressPrefix,
                SD_VARLINK_FIELD_COMMENT("The address family"),
                SD_VARLINK_DEFINE_FIELD(family, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The address"),
                SD_VARLINK_DEFINE_FIELD(address, SD_VARLINK_INT, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The address prefix length"),
                SD_VARLINK_DEFINE_FIELD(prefixLen, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupBPFProgram,
                SD_VARLINK_FIELD_COMMENT("The BPF program attach type"),
                SD_VARLINK_DEFINE_FIELD(attachType, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The path to the BPF program"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupSocketBind,
                SD_VARLINK_FIELD_COMMENT("The address family"),
                SD_VARLINK_DEFINE_FIELD(family, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The address protocol"),
                SD_VARLINK_DEFINE_FIELD(protocol, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The number of ports"),
                SD_VARLINK_DEFINE_FIELD(numberOfPorts, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The minimum port"),
                SD_VARLINK_DEFINE_FIELD(minimumPort, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupRestrictNetworkInterfaces,
                SD_VARLINK_FIELD_COMMENT("Whether this is an allow list"),
                SD_VARLINK_DEFINE_FIELD(isAllowList, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The list of interfaces"),
                SD_VARLINK_DEFINE_FIELD(interfaces, SD_VARLINK_STRING, SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupNFTSet,
                SD_VARLINK_FIELD_COMMENT("The source of this NFT set"),
                SD_VARLINK_DEFINE_FIELD(source, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The NFT protocol for this NFT set"),
                SD_VARLINK_DEFINE_FIELD(protocol, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The NFT table associated with this NFT set"),
                SD_VARLINK_DEFINE_FIELD(table, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The name of the NFT set"),
                SD_VARLINK_DEFINE_FIELD(set, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                CGroupContext,
                SD_VARLINK_FIELD_COMMENT("The ID of the slice that the unit runs in"),
                SD_VARLINK_DEFINE_FIELD(slice, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether cgroup controller delegation is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(delegate, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Which cgroup controllers are delegated to this unit"),
                SD_VARLINK_DEFINE_FIELD(delegateControllers, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The subgroup in which the unit process should be spawned"),
                SD_VARLINK_DEFINE_FIELD(delegateSubgroup, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether CPU accounting is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The CPU time weight assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuWeight, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPU time weight assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupCPUWeight, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPU time quota assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuQuotaPerSecUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("the duration over which the CPU time quota assigned to this unit is measured"),
                SD_VARLINK_DEFINE_FIELD(cpuQuotaPeriodUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPUs to which execution of this unit's processes is restricted"),
                SD_VARLINK_DEFINE_FIELD(allowedCPUs, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPUs to which execution of this unit's processes is restricted during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupAllowedCPUs, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The memory NUMA nodes to which execution of this unit's processes is restricted"),
                SD_VARLINK_DEFINE_FIELD(allowedMemoryNodes, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The memory NUMA nodes to which execution of this unit's processes is restricted during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupAllowedMemoryNodes, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether I/O accounting is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(ioAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default overall block I/O weight assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(ioWeight, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The default overall block I/O weight assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupIOWeight, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device overall block I/O weights assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioDeviceWeight, CGroupIODeviceWeight, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device overall block I/O maximum read bandwidth limits assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioReadBandwidthMax, CGroupIODeviceLimit, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device overall block I/O maximum write bandwidth limits assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioWriteBandwidthMax, CGroupIODeviceLimit, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device overall block I/O IOs-Per-Second maximum read limits assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioReadIOPSMax, CGroupIODeviceLimit, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device overall block I/O IOs-Per-Second maximum write limits assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioWriteIOPSMax, CGroupIODeviceLimit, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The per-device average target I/O latencies assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ioDeviceLatencyTargetUSec, CGroupIODeviceLatency, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether memory accounting is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default weak memory protection for children of this unit"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryLow, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The default weak memory protection for children of this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupDefaultMemoryLow, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The default strong memory protection for children of this unit"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryMin, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The strong memory protection for this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryMin, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The weak memory protection for this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryLow, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The weak memory protection for this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupMemoryLow, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The throttling limit on memory usage assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryHigh, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The throttling limit on memory usage assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupMemoryHigh, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on memory usage assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on memory usage assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupMemoryMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on swap usage assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(memorySwapMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on swap usage assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupMemorySwapMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on zswap usage assigned to this unit"),
                SD_VARLINK_DEFINE_FIELD(memoryZSwapMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The absolute limit on zswap usage assigned to this unit during system startup/shutdown"),
                SD_VARLINK_DEFINE_FIELD(startupMemoryZSwapMax, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The device access policy of this unit"),
                SD_VARLINK_DEFINE_FIELD(devicePolicy, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The devices this unit is allowed to access"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(deviceAllow, CGroupDeviceAllow, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether tasks accounting is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(tasksAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of tasks that may be created in the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(tasksMax, CGroupTasksMax, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether IP accounting is enabled for this unit"),
                SD_VARLINK_DEFINE_FIELD(ipAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The IP address ranges this unit is allowed to access"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ipAddressAllow, CGroupAddressPrefix, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The IP address ranges this unit is not allowed to access"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(ipAddressDeny, CGroupAddressPrefix, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Custom network traffic filters for ingress traffic for this unit"),
                SD_VARLINK_DEFINE_FIELD(ipIngressFilterPath, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Custom network traffic filters for egress traffic for this unit"),
                SD_VARLINK_DEFINE_FIELD(ipEgressFilterPath, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("CGroup controllers to disable for this unit"),
                SD_VARLINK_DEFINE_FIELD(disableControllers, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The action to take by systemd-oomd when this unit's cgroup swap limit is hit"),
                SD_VARLINK_DEFINE_FIELD(managedOOMSwap, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The action to take by systemd-oomd when this unit's cgroup memory pressure limit is hit"),
                SD_VARLINK_DEFINE_FIELD(managedOOMMemoryPressure, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The cgroup memory pressure limit for this unit"),
                SD_VARLINK_DEFINE_FIELD(managedOOMMemoryPressureLimit, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("How this unit's cgroup should be prioritized by systemd-oomd"),
                SD_VARLINK_DEFINE_FIELD(managedOOMPreference, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The BPF programs attached to this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(bpfProgram, CGroupBPFProgram, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ports that the unit is allowed to bind to"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(socketBindAllow, CGroupSocketBind, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ports that the unit is not allowed to bind to"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(socketBindAllow, CGroupSocketBind, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The network interfaces that the unit is allowed to use"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(restrictNetworkInterfaces, CGroupRestrictNetworkInterfaces, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The memory pressure monitoring mode for the unit"),
                SD_VARLINK_DEFINE_FIELD(memoryPressureWatch, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The memory pressure threshold configured for the unit"),
                SD_VARLINK_DEFINE_FIELD(memoryPressureThresholdUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The NFT sets associated with this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(nftSet, CGroupNFTSet, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                EnvironmentFile,
                SD_VARLINK_FIELD_COMMENT("The path to the environment file"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether failure to read the environment file is fatal or not"),
                SD_VARLINK_DEFINE_FIELD(graceful, SD_VARLINK_BOOL, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                WorkingDirectory,
                SD_VARLINK_FIELD_COMMENT("The path to the working directory"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the path to the working directory is allowed to not exist"),
                SD_VARLINK_DEFINE_FIELD(missingOK, SD_VARLINK_BOOL, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                PartitionMountOptions,
                SD_VARLINK_FIELD_COMMENT("The partition designator to which the options apply"),
                SD_VARLINK_DEFINE_FIELD(partitionDesignator, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The mount options for this partition"),
                SD_VARLINK_DEFINE_FIELD(options, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ExtensionImage,
                SD_VARLINK_FIELD_COMMENT("The path to the extension image"),
                SD_VARLINK_DEFINE_FIELD(source, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether failure to find the extension image is considered fatal"),
                SD_VARLINK_DEFINE_FIELD(ignoreEnoent, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The mount options to use for the partitions of the extension image"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(mountOptions, PartitionMountOptions, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                MountImage,
                SD_VARLINK_FIELD_COMMENT("The path to the image to mount"),
                SD_VARLINK_DEFINE_FIELD(source, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The destination path where to mount the image"),
                SD_VARLINK_DEFINE_FIELD(destination, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether failure to find the image is considered fatal"),
                SD_VARLINK_DEFINE_FIELD(ignoreEnoent, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The mount options to use for the partitions of the image"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(mountOptions, PartitionMountOptions, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                LogFilterPattern,
                SD_VARLINK_FIELD_COMMENT("Whether this pattern is an allow pattern"),
                SD_VARLINK_DEFINE_FIELD(isAllowList, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The filtering pattern"),
                SD_VARLINK_DEFINE_FIELD(pattern, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SetCredential,
                SD_VARLINK_FIELD_COMMENT("The credential ID"),
                SD_VARLINK_DEFINE_FIELD(id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The credential value encoded in base64"),
                SD_VARLINK_DEFINE_FIELD(value, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                LoadCredential,
                SD_VARLINK_FIELD_COMMENT("The credential ID"),
                SD_VARLINK_DEFINE_FIELD(id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The credential path"),
                SD_VARLINK_DEFINE_FIELD(value, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ImportCredential,
                SD_VARLINK_FIELD_COMMENT("The glob pattern to find credentials"),
                SD_VARLINK_DEFINE_FIELD(glob, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The rename pattern to which matching credentials should be renamed"),
                SD_VARLINK_DEFINE_FIELD(rename, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SELinuxContext,
                SD_VARLINK_FIELD_COMMENT("Whether failure to set the SELinux context is ignored"),
                SD_VARLINK_DEFINE_FIELD(ignore, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The SELinux context"),
                SD_VARLINK_DEFINE_FIELD(context, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                AppArmorProfile,
                SD_VARLINK_FIELD_COMMENT("Whether failure to configure the apparmor profile will be ignored"),
                SD_VARLINK_DEFINE_FIELD(ignore, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The AppArmor profile"),
                SD_VARLINK_DEFINE_FIELD(profile, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SmackProcessLabel,
                SD_VARLINK_FIELD_COMMENT("Whether failure to configure the smack process label will be ignored"),
                SD_VARLINK_DEFINE_FIELD(ignore, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The smack process label"),
                SD_VARLINK_DEFINE_FIELD(label, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SystemCallList,
                SD_VARLINK_FIELD_COMMENT("Whether the list of system calls is an allow list"),
                SD_VARLINK_DEFINE_FIELD(isAllowList, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The list of system calls"),
                SD_VARLINK_DEFINE_FIELD(systemCalls, SD_VARLINK_STRING, SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                AddressFamilyList,
                SD_VARLINK_FIELD_COMMENT("Whether the list of address families is an allow list"),
                SD_VARLINK_DEFINE_FIELD(isAllowList, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The list of address families"),
                SD_VARLINK_DEFINE_FIELD(addressFamilies, SD_VARLINK_STRING, SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ExecDirectory,
                SD_VARLINK_FIELD_COMMENT("The path to the directory"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The access mode of the directory"),
                SD_VARLINK_DEFINE_FIELD(mode, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("A list of symlinks pointing to the directory"),
                SD_VARLINK_DEFINE_FIELD(symlinks, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                FilesystemList,
                SD_VARLINK_FIELD_COMMENT("Whether the list of filesystems is an allow list"),
                SD_VARLINK_DEFINE_FIELD(isAllowList, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The list of filesystems"),
                SD_VARLINK_DEFINE_FIELD(filesystems, SD_VARLINK_STRING, SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                BindPath,
                SD_VARLINK_FIELD_COMMENT("The mount source path"),
                SD_VARLINK_DEFINE_FIELD(source, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The mount destination path"),
                SD_VARLINK_DEFINE_FIELD(destination, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether a missing source path should be ignored"),
                SD_VARLINK_DEFINE_FIELD(ignoreEnoent, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Mount options"),
                SD_VARLINK_DEFINE_FIELD(options, SD_VARLINK_STRING, SD_VARLINK_ARRAY));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                TemporaryFilesystem,
                SD_VARLINK_FIELD_COMMENT("The destination path where the temporary filesystem should be mounted"),
                SD_VARLINK_DEFINE_FIELD(path, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The mount options for the temporary filesystem"),
                SD_VARLINK_DEFINE_FIELD(options, SD_VARLINK_STRING, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ExecContext,
                SD_VARLINK_FIELD_COMMENT("The environment variables of the unit"),
                SD_VARLINK_DEFINE_FIELD(environment, SD_VARLINK_STRING, SD_VARLINK_MAP|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The environment files of the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(environmentFiles, EnvironmentFile, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The environment variables to pass from the manager to the unit"),
                SD_VARLINK_DEFINE_FIELD(passEnvironment, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The environment variables from the manager to unset for the unit"),
                SD_VARLINK_DEFINE_FIELD(unsetEnvironment, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The umask for the unit"),
                SD_VARLINK_DEFINE_FIELD(umask, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The maximum CPU time"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitCPU, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitFSIZE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum data segment size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitDATA, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum stack size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitSTACK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum core file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitCORE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum resident set size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitRSS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of open files"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitNOFILE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of address space"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitAS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of processes"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitNPROC, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of locked memory"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitMEMLOCK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of file locks"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitLOCKS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of pending signals"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitSIGPENDING, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum number of messages"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitMSGQUEUE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum nice level"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitNICE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum realtime priority"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitRTPRIO, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The maximum realtime deadline"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(limitRTTIME, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The working directory for the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(workingDirectory, WorkingDirectory, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root directory for the unit"),
                SD_VARLINK_DEFINE_FIELD(rootDirectory, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root image for the unit"),
                SD_VARLINK_DEFINE_FIELD(rootImage, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The mount options to use for the partitions of the unit's root image"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(rootImageOptions, PartitionMountOptions, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root hash for the unit's root image encoded in base64"),
                SD_VARLINK_DEFINE_FIELD(rootHash, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root hash path for the unit's root image"),
                SD_VARLINK_DEFINE_FIELD(rootHashPath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root hash signature for the unit's root image encoded in base64"),
                SD_VARLINK_DEFINE_FIELD(rootHashSignature, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The root hash signature path for the unit's root image"),
                SD_VARLINK_DEFINE_FIELD(rootHashSignaturePath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The verity data for the unit's root image"),
                SD_VARLINK_DEFINE_FIELD(rootVerity, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether to run the unit in an ephemeral copy of the unit's root directory or image"),
                SD_VARLINK_DEFINE_FIELD(rootEphemeral, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The extension directories for this unit's root directory or image"),
                SD_VARLINK_DEFINE_FIELD(extensionDirectories, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The extension images for this unit's root directory or image"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(extensionImages, ExtensionImage, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The images to mount into this unit's root directory or image"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(mountImages, MountImage, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("How much the oom score is adjusted for this unit"),
                SD_VARLINK_DEFINE_FIELD(oomScoreAdjust, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The coredump filter for this unit"),
                SD_VARLINK_DEFINE_FIELD(coredumpFilter, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The nice value for this unit"),
                SD_VARLINK_DEFINE_FIELD(nice, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The I/O scheduling class for this unit"),
                SD_VARLINK_DEFINE_FIELD(ioSchedulingClass, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The I/O scheduling priority for this unit"),
                SD_VARLINK_DEFINE_FIELD(ioSchedulingPriority, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPU scheduling policy for this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuSchedulingPolicy, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPU scheduling priority for this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuSchedulingPriority, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The CPU affinity for this unit"),
                SD_VARLINK_DEFINE_FIELD(cpuAffinity, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether the CPU affinity for this unit comes from NUMA"),
                SD_VARLINK_DEFINE_FIELD(cpuAffinityFromNUMA, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The NUMA policy for this unit"),
                SD_VARLINK_DEFINE_FIELD(numaPolicy, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The NUMA mask for this unit"),
                SD_VARLINK_DEFINE_FIELD(numaMask, SD_VARLINK_INT, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The timer slack for this unit"),
                SD_VARLINK_DEFINE_FIELD(timerSlackNSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether the CPU scheduling policy should be reset on fork"),
                SD_VARLINK_DEFINE_FIELD(cpuSchedulingResetOnFork, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to make all file descriptors passed via socket activation nonblocking"),
                SD_VARLINK_DEFINE_FIELD(nonBlocking, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The standard input mode for the unit"),
                SD_VARLINK_DEFINE_FIELD(standardInput, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The file descriptor name to connect standard input to"),
                SD_VARLINK_DEFINE_FIELD(standardInputFileDescriptorName, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The data to pass on standard input"),
                SD_VARLINK_DEFINE_FIELD(standardInputData, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The standard output mode for the unit"),
                SD_VARLINK_DEFINE_FIELD(standardOutput, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The file descriptor name to connect standard output to"),
                SD_VARLINK_DEFINE_FIELD(standardOutputFileDescriptorName, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The standard error mode for the unit"),
                SD_VARLINK_DEFINE_FIELD(standardError, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The file descriptor name to connect standard error to"),
                SD_VARLINK_DEFINE_FIELD(standardErrorFileDescriptorName, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The tty path to connect stdio to"),
                SD_VARLINK_DEFINE_FIELD(ttyPath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether to reset the tty"),
                SD_VARLINK_DEFINE_FIELD(ttyReset, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to disconnect all other clients on the tty"),
                SD_VARLINK_DEFINE_FIELD(ttyVHangup, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to try to deallocate a virtual tty before and after execution"),
                SD_VARLINK_DEFINE_FIELD(ttyVTDisallocate, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The vertical size to use for the tty"),
                SD_VARLINK_DEFINE_FIELD(ttyRows, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The horizontal size to use for the tty"),
                SD_VARLINK_DEFINE_FIELD(ttyColumns, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The syslog identifier to use for messages generated by the unit"),
                SD_VARLINK_DEFINE_FIELD(syslogIdentifier, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether to parse log level prefixes in the unit's log messages"),
                SD_VARLINK_DEFINE_FIELD(syslogLevelPrefix, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The rate limiting to apply to this unit's log messages"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(logRateLimit, RateLimit, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Extra journal fields to attach to this unit's log messages"),
                SD_VARLINK_DEFINE_FIELD(logExtraFields, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Log filtering patterns to apply to this unit's log messages"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(logFilterPatterns, LogFilterPattern, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The log namespace the unit's log messages should be written to"),
                SD_VARLINK_DEFINE_FIELD(logNamespace, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The secure bits to set for the unit"),
                SD_VARLINK_DEFINE_FIELD(secureBits, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The bounding set of capabilities for this unit"),
                SD_VARLINK_DEFINE_FIELD(capabilityBoundingSet, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ambient set of capabilities for this unit"),
                SD_VARLINK_DEFINE_FIELD(ambientCapabilities, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The user to run the unit under"),
                SD_VARLINK_DEFINE_FIELD(user, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The group to run the unit under"),
                SD_VARLINK_DEFINE_FIELD(group, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether to dynamically allocate a user to run this unit under"),
                SD_VARLINK_DEFINE_FIELD(dynamicUser, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to remove all System V and POSIX IPC objects owned by the user and group this unit runs under"),
                SD_VARLINK_DEFINE_FIELD(removeIPC, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SetCredential=ID:VALUE"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(setCredential, SetCredential, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SetCredential=ID:VALUE"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(setCredentialEncrypted, SetCredential, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LoadCredential=ID:PATH"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(loadCredential, LoadCredential, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LoadCredential=ID:PATH"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(loadCredentialEncrypted, LoadCredential, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ImportCredential=GLOB"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(importCredential, ImportCredential, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SupplementaryGroups="),
                SD_VARLINK_DEFINE_FIELD(supplementaryGroups, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PAMName="),
                SD_VARLINK_DEFINE_FIELD(pamName, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ReadWritePaths="),
                SD_VARLINK_DEFINE_FIELD(readWritePaths, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ReadWritePaths="),
                SD_VARLINK_DEFINE_FIELD(inaccessiblePaths, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ReadWritePaths="),
                SD_VARLINK_DEFINE_FIELD(execPaths, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ReadWritePaths="),
                SD_VARLINK_DEFINE_FIELD(noExecPaths, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ExecSearchPath="),
                SD_VARLINK_DEFINE_FIELD(execSearchPath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#MountFlags="),
                SD_VARLINK_DEFINE_FIELD(mountFlags, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateTmp="),
                SD_VARLINK_DEFINE_FIELD(privateTmp, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateDevices="),
                SD_VARLINK_DEFINE_FIELD(privateDevices, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectClock="),
                SD_VARLINK_DEFINE_FIELD(protectClock, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectKernelTunables="),
                SD_VARLINK_DEFINE_FIELD(protectKernelTunables, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectKernelModules="),
                SD_VARLINK_DEFINE_FIELD(protectKernelModules, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectKernelLogs="),
                SD_VARLINK_DEFINE_FIELD(protectKernelLogs, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectControlGroups="),
                SD_VARLINK_DEFINE_FIELD(ProtectControlGroups, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateNetwork="),
                SD_VARLINK_DEFINE_FIELD(PrivateNetwork, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateUsers="),
                SD_VARLINK_DEFINE_FIELD(PrivateUsers, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateMounts="),
                SD_VARLINK_DEFINE_FIELD(privateMounts, SD_VARLINK_BOOL, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#PrivateIPC="),
                SD_VARLINK_DEFINE_FIELD(privateIPC, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectHome="),
                SD_VARLINK_DEFINE_FIELD(protectHome, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectSystem="),
                SD_VARLINK_DEFINE_FIELD(protectSystem, SD_VARLINK_STRING, 0),
                /* sameProcessGroup can't be configured in unit files. */
                SD_VARLINK_DEFINE_FIELD(sameProcessGroup, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#UtmpIdentifier="),
                SD_VARLINK_DEFINE_FIELD(utmpIdentifier, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#UtmpMode="),
                SD_VARLINK_DEFINE_FIELD(utmpMode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SELinuxContext="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(selinuxContext, SELinuxContext, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#AppArmorProfile="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(appArmorProfile, AppArmorProfile, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SmackProcessLabel="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(smackProcessLabel, SmackProcessLabel, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#IgnoreSIGPIPE="),
                SD_VARLINK_DEFINE_FIELD(ignoreSIGPIPE, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#NoNewPrivileges="),
                SD_VARLINK_DEFINE_FIELD(noNewPrivileges, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SystemCallFilter="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(systemCallFilter, SystemCallList, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SystemCallArchitectures="),
                SD_VARLINK_DEFINE_FIELD(systemCallArchitectures, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SystemCallErrorNumber="),
                SD_VARLINK_DEFINE_FIELD(systemCallErrorNumber, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#SystemCallLog="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(systemCallLog, SystemCallList, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#Personality="),
                SD_VARLINK_DEFINE_FIELD(personality, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#LockPersonality="),
                SD_VARLINK_DEFINE_FIELD(lockPersonality, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RestrictAddressFamilies="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(restrictAddressFamilies, AddressFamilyList, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(runtimeDirectory, ExecDirectory, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectoryPreserve="),
                SD_VARLINK_DEFINE_FIELD(runtimeDirectoryPreserve, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(stateDirectory, ExecDirectory, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(cacheDirectory, ExecDirectory, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(logsDirectory, ExecDirectory, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(configurationDirectory, ExecDirectory, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#TimeoutCleanSec="),
                SD_VARLINK_DEFINE_FIELD(timeoutCleanUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#MemoryDenyWriteExecute="),
                SD_VARLINK_DEFINE_FIELD(memoryDenyWriteExecute, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RestrictRealtime="),
                SD_VARLINK_DEFINE_FIELD(restrictRealtime, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RestrictSUIDSGID="),
                SD_VARLINK_DEFINE_FIELD(restrictSUIDSGID, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RestrictFileSystems="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(restrictFilesystems, FilesystemList, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#BindPaths="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(bindPaths, BindPath, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#BindPaths="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(bindReadOnlyPaths, BindPath, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#TemporaryFileSystem="),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(temporaryFileSystem, TemporaryFilesystem, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#MountAPIVFS="),
                SD_VARLINK_DEFINE_FIELD(mountAPIVFS, SD_VARLINK_BOOL, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#KeyringMode="),
                SD_VARLINK_DEFINE_FIELD(keyringMode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectProc="),
                SD_VARLINK_DEFINE_FIELD(protectProc, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProcSubset="),
                SD_VARLINK_DEFINE_FIELD(procSubset, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#ProtectHostname="),
                SD_VARLINK_DEFINE_FIELD(protectHostname, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#MemoryKSM="),
                SD_VARLINK_DEFINE_FIELD(memoryKSM, SD_VARLINK_BOOL, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#NetworkNamespacePath="),
                SD_VARLINK_DEFINE_FIELD(networkNamespacePath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#IPCNamespacePath="),
                SD_VARLINK_DEFINE_FIELD(ipcNamespacePath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RootImagePolicy="),
                SD_VARLINK_DEFINE_FIELD(rootImagePolicy, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RootImagePolicy="),
                SD_VARLINK_DEFINE_FIELD(mountImagePolicy, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RootImagePolicy="),
                SD_VARLINK_DEFINE_FIELD(extensionImagePolicy, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                UnitContext,
                SD_VARLINK_FIELD_COMMENT("The unit type"),
                SD_VARLINK_DEFINE_FIELD(type, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The unit ID"),
                SD_VARLINK_DEFINE_FIELD(id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The aliases of this unit"),
                SD_VARLINK_DEFINE_FIELD(names, SD_VARLINK_STRING, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The Requires= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(requires, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Requisite= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(requisite, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Wants= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(wants, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The BindsTo= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(bindsTo, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Upholds= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(upholds, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The PartOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(partOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Conflicts= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(conflicts, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The RequiredBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(requiredBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The RequisiteOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(requisiteOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The WantedBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(wantedBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The BoundBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(boundBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The UpheldBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(upheldBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ConsistsOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(consistsOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ConflictedBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(conflictedBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Before= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(before, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The After= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(after, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The OnSuccess= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(onSuccess, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The OnSuccessOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(onSuccessOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The OnFailure= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(onFailure, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The OnFailureOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(onFailureOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The Triggers= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(triggers, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The TriggeredBy= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(triggeredBy, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The PropagatesReloadTo= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(propagatesReloadTo, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The ReloadPropagatedFrom= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(reloadPropagatedFrom, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The PropagatesStopTo= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(propagatesStopTo, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The StopPropagatedFrom= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(stopPropagatedFrom, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The JoinsNamespaceOf= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(joinsNamespaceOf, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The RequiresMountsFor= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(requiresMountsFor, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The WantsMountsFor= dependencies of this unit"),
                SD_VARLINK_DEFINE_FIELD(wantsMountsFor, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The unit's Documentation= strings as an array"),
                SD_VARLINK_DEFINE_FIELD(documentation, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The unit's description"),
                SD_VARLINK_DEFINE_FIELD(description, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The SELinux context that is used to control access to the unit"),
                SD_VARLINK_DEFINE_FIELD(accessSELinuxContext, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The unit file path this unit was read from"),
                SD_VARLINK_DEFINE_FIELD(fragmentPath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The path to a configuration file this unit is automatically generated from"),
                SD_VARLINK_DEFINE_FIELD(sourcePath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The paths from which drop-in files were read for this unit"),
                SD_VARLINK_DEFINE_FIELD(dropInPaths, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The unit file preset for this unit"),
                SD_VARLINK_DEFINE_FIELD(unitFilePreset, SD_VARLINK_STRING, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether to stop this unit when it's not depended on anymore by other units"),
                SD_VARLINK_DEFINE_FIELD(stopWhenUnneeded, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to refuse manual starts of this unit"),
                SD_VARLINK_DEFINE_FIELD(refuseManualStart, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to refuse manual stops of this unit"),
                SD_VARLINK_DEFINE_FIELD(refuseManualStop, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether isolating this unit is allowed"),
                SD_VARLINK_DEFINE_FIELD(allowIsolate, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether default dependencies should be generated for this unit"),
                SD_VARLINK_DEFINE_FIELD(defaultDependencies, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The job mode for units triggered on success of this unit"),
                SD_VARLINK_DEFINE_FIELD(onSuccessJobMode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The job mode for units triggered on failure of this unit"),
                SD_VARLINK_DEFINE_FIELD(onFailureJobMode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether to ignore this unit when another unit is isolated"),
                SD_VARLINK_DEFINE_FIELD(ignoreOnIsolate, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Timeout for jobs associated with this unit that starts running when a job is queued"),
                SD_VARLINK_DEFINE_FIELD(jobTimeoutUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timeout for jobs associated with this unit that starts running when a job starts running"),
                SD_VARLINK_DEFINE_FIELD(jobRunningTimeoutUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Action to take when a job associated with this unit times out"),
                SD_VARLINK_DEFINE_FIELD(jobTimeoutAction, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Reboot argument to use when the job timeout action is \"reboot\""),
                SD_VARLINK_DEFINE_FIELD(jobTimeoutRebootArgument, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The conditions of this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(conditions, Condition, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The asserts of this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(asserts, Condition, SD_VARLINK_ARRAY|SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether this unit is transient"),
                SD_VARLINK_DEFINE_FIELD(transient, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether this unit is perpetual"),
                SD_VARLINK_DEFINE_FIELD(perpetual, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The start ratelimit for this unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(startLimit, RateLimit, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Action to take when the start ratelimit of this unit is hit"),
                SD_VARLINK_DEFINE_FIELD(startLimitAction, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Action to take when this unit fails"),
                SD_VARLINK_DEFINE_FIELD(failureAction, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Exit status to use when the unit failure action is \"exit\""),
                SD_VARLINK_DEFINE_FIELD(failureActionExitStatus, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Action to take when this unit succeeds"),
                SD_VARLINK_DEFINE_FIELD(failureAction, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Exit status to use when the unit success action is \"exit\""),
                SD_VARLINK_DEFINE_FIELD(failureActionExitStatus, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Reboot argument to use when the success or failure action is \"reboot\""),
                SD_VARLINK_DEFINE_FIELD(rebootArgument, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The garbage collection logic to use for this unit"),
                SD_VARLINK_DEFINE_FIELD(collectMode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The cgroup context of the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(cgroup, CGroupContext, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The exec context of the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(exec, ExecContext, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The kill context of the unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(kill, KillContext, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Unit,
                SD_VARLINK_FIELD_COMMENT("Configuration of unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(context, UnitContext, 0),
                SD_VARLINK_FIELD_COMMENT("Runtime information of unit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(runtime, UnitRuntime, 0));

SD_VARLINK_DEFINE_INTERFACE(
                io_systemd_Manager,
                "io.systemd.Manager",
                &vl_method_Describe,
                &vl_method_DescribeJobs,
                &vl_type_Manager,
                &vl_type_ManagerContext,
                &vl_type_ManagerRuntime,
                &vl_type_Timestamp,
                &vl_type_ResourceLimit,
                &vl_type_RateLimit,
                &vl_type_Job,
                &vl_type_JobUnit,
                &vl_type_ActivationDetails,
                &vl_error_NoSuchJob);
