/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include "varlink-idl-common.h"
#include "varlink-io.systemd.Login.h"

static SD_VARLINK_DEFINE_ENUM_TYPE(
                SessionType,
                SD_VARLINK_DEFINE_ENUM_VALUE(unspecified),
                SD_VARLINK_DEFINE_ENUM_VALUE(tty),
                SD_VARLINK_DEFINE_ENUM_VALUE(x11),
                SD_VARLINK_DEFINE_ENUM_VALUE(wayland),
                SD_VARLINK_DEFINE_ENUM_VALUE(mir),
                SD_VARLINK_DEFINE_ENUM_VALUE(web));

static SD_VARLINK_DEFINE_ENUM_TYPE(
                SessionClass,
                SD_VARLINK_FIELD_COMMENT("Regular user sessions"),
                SD_VARLINK_DEFINE_ENUM_VALUE(user),
                SD_VARLINK_FIELD_COMMENT("Session of the root user that shall be open for login from earliest moment on, and not be delayed for /run/nologin"),
                SD_VARLINK_DEFINE_ENUM_VALUE(user_early),
                SD_VARLINK_FIELD_COMMENT("Regular user session whose home directory is not available right now, but will be later, at which point the session class can be upgraded to 'user'"),
                SD_VARLINK_DEFINE_ENUM_VALUE(user_incomplete),
                SD_VARLINK_FIELD_COMMENT("A user session that doesn't pull in the per-user service manager"),
                SD_VARLINK_DEFINE_ENUM_VALUE(user_light),
                SD_VARLINK_FIELD_COMMENT("The combination of user_early and user_light"),
                SD_VARLINK_DEFINE_ENUM_VALUE(user_early_light),
                SD_VARLINK_FIELD_COMMENT("Display manager greeter screen used for login"),
                SD_VARLINK_DEFINE_ENUM_VALUE(greeter),
                SD_VARLINK_FIELD_COMMENT("Similar, but a a lock screen"),
                SD_VARLINK_DEFINE_ENUM_VALUE(lock_screen),
                SD_VARLINK_FIELD_COMMENT("Background session (that has no TTY, VT, Seat)"),
                SD_VARLINK_DEFINE_ENUM_VALUE(background),
                SD_VARLINK_FIELD_COMMENT("Similar, but for which no service manager is invoked"),
                SD_VARLINK_DEFINE_ENUM_VALUE(background_light),
                SD_VARLINK_FIELD_COMMENT("The special session of the service manager"),
                SD_VARLINK_DEFINE_ENUM_VALUE(manager),
                SD_VARLINK_FIELD_COMMENT("The special session of the service manager for the root user"),
                SD_VARLINK_DEFINE_ENUM_VALUE(manager_early));

static SD_VARLINK_DEFINE_METHOD(
                CreateSession,
                SD_VARLINK_FIELD_COMMENT("Numeric UNIX UID of the user this session shall be owned by"),
                SD_VARLINK_DEFINE_INPUT(UID, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("Process that shall become the leader of the session. If null defaults to the IPC client."),
                SD_VARLINK_DEFINE_INPUT_BY_TYPE(PID, ProcessId, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("PAM service name of the program requesting the session"),
                SD_VARLINK_DEFINE_INPUT(Service, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The type of the session"),
                SD_VARLINK_DEFINE_INPUT_BY_TYPE(Type, SessionType, 0),
                SD_VARLINK_FIELD_COMMENT("The class of the session"),
                SD_VARLINK_DEFINE_INPUT_BY_TYPE(Class, SessionClass, 0),
                SD_VARLINK_FIELD_COMMENT("An identifier for the chosen desktop"),
                SD_VARLINK_DEFINE_INPUT(Desktop, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The name of the seat to assign this session to"),
                SD_VARLINK_DEFINE_INPUT(Seat, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The virtual terminal number to assign this session to"),
                SD_VARLINK_DEFINE_INPUT(VTNr, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The TTY device to assign this session to, if applicable"),
                SD_VARLINK_DEFINE_INPUT(TTY, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The X11 display for this session"),
                SD_VARLINK_DEFINE_INPUT(Display, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("If true this is a remote session"),
                SD_VARLINK_DEFINE_INPUT(Remote, SD_VARLINK_BOOL, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("User name on the remote site, if known"),
                SD_VARLINK_DEFINE_INPUT(RemoteUser, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Host name of the remote host"),
                SD_VARLINK_DEFINE_INPUT(RemoteHost, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("List of additional hardware devices that this session is granted access to."
                                         "For every $ID in the list, this adds access for all devices tagged with \"xaccess-$ID\" in udev."),
                SD_VARLINK_DEFINE_INPUT(ExtraDeviceAccess, SD_VARLINK_STRING, SD_VARLINK_NULLABLE|SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The identifier string of the session of the user."),
                SD_VARLINK_DEFINE_OUTPUT(Id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The runtime path ($XDG_RUNTIME_DIR) of the user."),
                SD_VARLINK_DEFINE_OUTPUT(RuntimePath, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The original UID of this session."),
                SD_VARLINK_DEFINE_OUTPUT(UID, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The seat this session has been assigned to"),
                SD_VARLINK_DEFINE_OUTPUT(Seat, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The virtual terminal number the session has been assigned to"),
                SD_VARLINK_DEFINE_OUTPUT(VTNr, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The assigned session type"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Type, SessionType, 0),
                SD_VARLINK_FIELD_COMMENT("The assigned session class"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Class, SessionClass, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SessionInfo,
                SD_VARLINK_FIELD_COMMENT("The session identifier"),
                SD_VARLINK_DEFINE_FIELD(Id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The user owning this session"),
                SD_VARLINK_DEFINE_FIELD(User, SD_VARLINK_OBJECT, 0),
                SD_VARLINK_FIELD_COMMENT("The session timestamps"),
                SD_VARLINK_DEFINE_FIELD(Timestamp, SD_VARLINK_OBJECT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Virtual terminal number of the session, if applicable"),
                SD_VARLINK_DEFINE_FIELD(VTNr, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Seat this session is assigned to"),
                SD_VARLINK_DEFINE_FIELD(Seat, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("TTY device of the session"),
                SD_VARLINK_DEFINE_FIELD(TTY, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("X11 display of the session"),
                SD_VARLINK_DEFINE_FIELD(Display, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether this is a remote session"),
                SD_VARLINK_DEFINE_FIELD(Remote, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Remote host, if this is a remote session"),
                SD_VARLINK_DEFINE_FIELD(RemoteHost, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Remote user, if this is a remote session"),
                SD_VARLINK_DEFINE_FIELD(RemoteUser, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("PAM service name"),
                SD_VARLINK_DEFINE_FIELD(Service, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Desktop identifier"),
                SD_VARLINK_DEFINE_FIELD(Desktop, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("systemd scope unit name"),
                SD_VARLINK_DEFINE_FIELD(Scope, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("PID of the session leader"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(Leader, ProcessId, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Audit session ID"),
                SD_VARLINK_DEFINE_FIELD(Audit, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The type of the session"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(Type, SessionType, 0),
                SD_VARLINK_FIELD_COMMENT("The class of the session"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(Class, SessionClass, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the session is active (i.e. in the foreground)"),
                SD_VARLINK_DEFINE_FIELD(Active, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Current state of the session"),
                SD_VARLINK_DEFINE_FIELD(State, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the session is idle"),
                SD_VARLINK_DEFINE_FIELD(IdleHint, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Realtime timestamp when the session went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHint, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Monotonic timestamp when the session went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHintMonotonic, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether this session class supports idle tracking"),
                SD_VARLINK_DEFINE_FIELD(CanIdle, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether this session class supports locking"),
                SD_VARLINK_DEFINE_FIELD(CanLock, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the session is currently locked"),
                SD_VARLINK_DEFINE_FIELD(LockedHint, SD_VARLINK_BOOL, 0));

static SD_VARLINK_DEFINE_METHOD(
                DescribeSession,
                SD_VARLINK_FIELD_COMMENT("The identifier string of the session. If unspecified or 'self'/'auto', returns the caller's session."),
                SD_VARLINK_DEFINE_INPUT(Id, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The session information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Session, SessionInfo, 0));

static SD_VARLINK_DEFINE_METHOD_FULL(
                ListSessions,
                SD_VARLINK_SUPPORTS_MORE,
                SD_VARLINK_FIELD_COMMENT("The session information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Session, SessionInfo, 0));

static SD_VARLINK_DEFINE_METHOD(
                ReleaseSession,
                SD_VARLINK_FIELD_COMMENT("The identifier string of the session to release. If unspecified or 'self', will return the callers session."),
                SD_VARLINK_DEFINE_INPUT(Id, SD_VARLINK_STRING, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                UserInfo,
                SD_VARLINK_FIELD_COMMENT("Numeric UNIX UID"),
                SD_VARLINK_DEFINE_FIELD(UID, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("Numeric UNIX GID"),
                SD_VARLINK_DEFINE_FIELD(GID, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("User name"),
                SD_VARLINK_DEFINE_FIELD(Name, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The user timestamps"),
                SD_VARLINK_DEFINE_FIELD(Timestamp, SD_VARLINK_OBJECT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Path to the user's runtime directory"),
                SD_VARLINK_DEFINE_FIELD(RuntimePath, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Service manager unit name"),
                SD_VARLINK_DEFINE_FIELD(Service, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("User slice unit name"),
                SD_VARLINK_DEFINE_FIELD(Slice, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Display session identifier"),
                SD_VARLINK_DEFINE_FIELD(Display, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Current state of the user"),
                SD_VARLINK_DEFINE_FIELD(State, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("List of session identifiers belonging to this user"),
                SD_VARLINK_DEFINE_FIELD(Sessions, SD_VARLINK_OBJECT, SD_VARLINK_NULLABLE|SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("Whether the user is idle"),
                SD_VARLINK_DEFINE_FIELD(IdleHint, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Realtime timestamp when the user went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHint, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Monotonic timestamp when the user went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHintMonotonic, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether lingering is enabled for this user"),
                SD_VARLINK_DEFINE_FIELD(Linger, SD_VARLINK_BOOL, 0));

static SD_VARLINK_DEFINE_METHOD(
                DescribeUser,
                SD_VARLINK_FIELD_COMMENT("Numeric UNIX UID of the user. If unspecified, returns the caller's user."),
                SD_VARLINK_DEFINE_INPUT(UID, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The user information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(User, UserInfo, 0));

static SD_VARLINK_DEFINE_METHOD_FULL(
                ListUsers,
                SD_VARLINK_SUPPORTS_MORE,
                SD_VARLINK_FIELD_COMMENT("The user information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(User, UserInfo, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                SeatInfo,
                SD_VARLINK_FIELD_COMMENT("The seat identifier"),
                SD_VARLINK_DEFINE_FIELD(Id, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The currently active session on this seat, if any"),
                SD_VARLINK_DEFINE_FIELD(ActiveSession, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("List of sessions assigned to this seat"),
                SD_VARLINK_DEFINE_FIELD(Sessions, SD_VARLINK_OBJECT, SD_VARLINK_NULLABLE|SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("Whether this seat supports text terminal sessions"),
                SD_VARLINK_DEFINE_FIELD(CanTTY, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether this seat supports graphical sessions"),
                SD_VARLINK_DEFINE_FIELD(CanGraphical, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether the seat is idle"),
                SD_VARLINK_DEFINE_FIELD(IdleHint, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Realtime timestamp when the seat went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHint, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Monotonic timestamp when the seat went idle"),
                SD_VARLINK_DEFINE_FIELD(IdleSinceHintMonotonic, SD_VARLINK_INT, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_METHOD(
                DescribeSeat,
                SD_VARLINK_FIELD_COMMENT("The identifier string of the seat. If unspecified or 'self'/'auto', returns the caller's seat."),
                SD_VARLINK_DEFINE_INPUT(Id, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The seat information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Seat, SeatInfo, 0));

static SD_VARLINK_DEFINE_METHOD_FULL(
                ListSeats,
                SD_VARLINK_SUPPORTS_MORE,
                SD_VARLINK_FIELD_COMMENT("The seat information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Seat, SeatInfo, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                InhibitorInfo,
                SD_VARLINK_FIELD_COMMENT("The inhibitor identifier"),
                SD_VARLINK_DEFINE_FIELD(Id, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("What is being inhibited, a colon-separated list of shutdown, sleep, idle, handle-power-key, handle-suspend-key, handle-hibernate-key, handle-lid-switch, handle-reboot-key"),
                SD_VARLINK_DEFINE_FIELD(What, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A human-readable descriptive string of who is taking the inhibition"),
                SD_VARLINK_DEFINE_FIELD(Who, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("A human-readable descriptive string of why the inhibition is taken"),
                SD_VARLINK_DEFINE_FIELD(Why, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The inhibition mode, one of block, block-weak, or delay"),
                SD_VARLINK_DEFINE_FIELD(Mode, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The UID of the user taking the inhibition"),
                SD_VARLINK_DEFINE_FIELD(UID, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The PID of the process taking the inhibition"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(PID, ProcessId, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The inhibitor timestamps"),
                SD_VARLINK_DEFINE_FIELD(Since, SD_VARLINK_OBJECT, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_METHOD_FULL(
                ListInhibitors,
                SD_VARLINK_SUPPORTS_MORE,
                SD_VARLINK_FIELD_COMMENT("The inhibitor information"),
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(Inhibitor, InhibitorInfo, 0));

static SD_VARLINK_DEFINE_ERROR(NoSuchSession);
static SD_VARLINK_DEFINE_ERROR(NoSuchUser);
static SD_VARLINK_DEFINE_ERROR(NoSuchSeat);
static SD_VARLINK_DEFINE_ERROR(NoSuchInhibitor);
static SD_VARLINK_DEFINE_ERROR(AlreadySessionMember);
static SD_VARLINK_DEFINE_ERROR(VirtualTerminalAlreadyTaken);
static SD_VARLINK_DEFINE_ERROR(TooManySessions);
static SD_VARLINK_DEFINE_ERROR(UnitAllocationFailed);
static SD_VARLINK_DEFINE_ERROR(NoSessionPIDFD);

SD_VARLINK_DEFINE_INTERFACE(
                io_systemd_Login,
                "io.systemd.Login",
                SD_VARLINK_INTERFACE_COMMENT("APIs for managing login sessions."),
                SD_VARLINK_SYMBOL_COMMENT("Process identifier"),
                &vl_type_ProcessId,
                SD_VARLINK_SYMBOL_COMMENT("Various types of sessions"),
                &vl_type_SessionType,
                SD_VARLINK_SYMBOL_COMMENT("Various classes of sessions"),
                &vl_type_SessionClass,
                SD_VARLINK_SYMBOL_COMMENT("Information about a session"),
                &vl_type_SessionInfo,
                SD_VARLINK_SYMBOL_COMMENT("Allocates a new session."),
                &vl_method_CreateSession,
                SD_VARLINK_SYMBOL_COMMENT("Releases an existing session. Currently, will be refused unless originating from the session to release itself."),
                &vl_method_ReleaseSession,
                SD_VARLINK_SYMBOL_COMMENT("Describes a specific session."),
                &vl_method_DescribeSession,
                SD_VARLINK_SYMBOL_COMMENT("Lists all current sessions."),
                &vl_method_ListSessions,
                SD_VARLINK_SYMBOL_COMMENT("Information about a user"),
                &vl_type_UserInfo,
                SD_VARLINK_SYMBOL_COMMENT("Describes a specific user."),
                &vl_method_DescribeUser,
                SD_VARLINK_SYMBOL_COMMENT("Lists all current users."),
                &vl_method_ListUsers,
                SD_VARLINK_SYMBOL_COMMENT("Information about a seat"),
                &vl_type_SeatInfo,
                SD_VARLINK_SYMBOL_COMMENT("Describes a specific seat."),
                &vl_method_DescribeSeat,
                SD_VARLINK_SYMBOL_COMMENT("Lists all current seats."),
                &vl_method_ListSeats,
                SD_VARLINK_SYMBOL_COMMENT("Information about an inhibitor"),
                &vl_type_InhibitorInfo,
                SD_VARLINK_SYMBOL_COMMENT("Lists all current inhibitors."),
                &vl_method_ListInhibitors,
                SD_VARLINK_SYMBOL_COMMENT("No session by this name found"),
                &vl_error_NoSuchSession,
                SD_VARLINK_SYMBOL_COMMENT("No seat by this name found"),
                &vl_error_NoSuchSeat,
                SD_VARLINK_SYMBOL_COMMENT("No user by this UID found"),
                &vl_error_NoSuchUser,
                SD_VARLINK_SYMBOL_COMMENT("No inhibitor found"),
                &vl_error_NoSuchInhibitor,
                SD_VARLINK_SYMBOL_COMMENT("Process already member of a session"),
                &vl_error_AlreadySessionMember,
                SD_VARLINK_SYMBOL_COMMENT("The specified virtual terminal (VT) is already taken by another session"),
                &vl_error_VirtualTerminalAlreadyTaken,
                SD_VARLINK_SYMBOL_COMMENT("Maximum number of sessions reached"),
                &vl_error_TooManySessions,
                SD_VARLINK_SYMBOL_COMMENT("Failed to allocate a unit for the session"),
                &vl_error_UnitAllocationFailed,
                SD_VARLINK_SYMBOL_COMMENT("The session leader process does not have a pidfd"),
                &vl_error_NoSessionPIDFD);
