/* SPDX-License-Identifier: LGPL-2.1-or-later */

#include "varlink-io.systemd.Manager.h"

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                RateLimit,
                SD_VARLINK_FIELD_COMMENT("The ratelimit interval"),
                SD_VARLINK_DEFINE_FIELD(intervalUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The ratelimit burst"),
                SD_VARLINK_DEFINE_FIELD(burst, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ResourceLimit,
                SD_VARLINK_FIELD_COMMENT("The soft resource limit"),
                SD_VARLINK_DEFINE_FIELD(soft, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The hard resource limit burst"),
                SD_VARLINK_DEFINE_FIELD(hard, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Timestamp,
                SD_VARLINK_FIELD_COMMENT("Timestamp in µs in the CLOCK_REALTIME clock (wallclock)"),
                SD_VARLINK_DEFINE_FIELD(realtime, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp in µs in the CLOCK_MONOTONIC clock"),
                SD_VARLINK_DEFINE_FIELD(monotonic, SD_VARLINK_INT, SD_VARLINK_NULLABLE));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ManagerContext,
                SD_VARLINK_FIELD_COMMENT("The version string of the running systemd instance"),
                SD_VARLINK_DEFINE_FIELD(version, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The features that have been enabled and disabled for this build"),
                SD_VARLINK_DEFINE_FIELD(features, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the architecture the systemd instance is running on"),
                SD_VARLINK_DEFINE_FIELD(architecture, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the virtualization technology the system runs in"),
                SD_VARLINK_DEFINE_FIELD(virtualization, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("A short ID string describing the confidential virtualization technology the system runs in"),
                SD_VARLINK_DEFINE_FIELD(confidentialVirtualization, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("An array of strings describing the taints applied to the running system"),
                SD_VARLINK_DEFINE_FIELD(taints, SD_VARLINK_STRING, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The console on which systemd asks for confirmation when spawning processes"),
                SD_VARLINK_DEFINE_FIELD(confirmSpawn, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether systemd will show status messages on the system console"),
                SD_VARLINK_DEFINE_FIELD(showStatus, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The unit search path"),
                SD_VARLINK_DEFINE_FIELD(unitPath, SD_VARLINK_STRING, SD_VARLINK_ARRAY),
                SD_VARLINK_FIELD_COMMENT("The default standard output for units"),
                SD_VARLINK_DEFINE_FIELD(defaultStandardOutput, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default standard error for units"),
                SD_VARLINK_DEFINE_FIELD(defaultStandardError, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog pretimeout"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogPreUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog pretimeout governor"),
                SD_VARLINK_DEFINE_FIELD(runtimeWatchdogPreGovernor, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The reboot watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(rebootWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The kexec watchdog timeout"),
                SD_VARLINK_DEFINE_FIELD(kexecWatchdogUSec, SD_VARLINK_INT, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Whether service watchdogs are enabled"),
                SD_VARLINK_DEFINE_FIELD(serviceWatchdogs, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default timer accuracy"),
                SD_VARLINK_DEFINE_FIELD(defaultTimerAccuracyUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit start timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutStartUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit stop timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutStopUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default unit abort timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultTimeoutAbortUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default device timeout"),
                SD_VARLINK_DEFINE_FIELD(defaultDeviceTimeoutUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default interval between unit restarts"),
                SD_VARLINK_DEFINE_FIELD(defaultRestartUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default start rate limit"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultStartLimit, RateLimit, 0),
                SD_VARLINK_FIELD_COMMENT("Whether CPU accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultCPUAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether block IO accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultBlockIOAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether IO accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultIOAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether IP accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultIPAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether memory accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("Whether tasks accounting is enabled"),
                SD_VARLINK_DEFINE_FIELD(defaultTasksAccounting, SD_VARLINK_BOOL, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum CPU time"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitCPU, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitFSIZE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum data segment size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitDATA, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum stack size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitSTACK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum core file size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitCORE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum resident set size"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRSS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of open files"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNOFILE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of address space"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitAS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of processes"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNPROC, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of locked memory"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitMEMLOCK, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of file locks"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitLOCKS, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of pending signals"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitSIGPENDING, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of messages"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitMSGQUEUE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum nice level"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitNICE, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum realtime priority"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRTPRIO, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum realtime deadline"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(defaultLimitRTTIME, ResourceLimit, 0),
                SD_VARLINK_FIELD_COMMENT("The default maximum number of tasks"),
                SD_VARLINK_DEFINE_FIELD(defaultTasksMax, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default threshold for checking memory pressure"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryPressureThresholdUSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default memory pressure watch"),
                SD_VARLINK_DEFINE_FIELD(defaultMemoryPressureWatch, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default timer slack"),
                SD_VARLINK_DEFINE_FIELD(timerSlackNSec, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The default out-of-memory policy"),
                SD_VARLINK_DEFINE_FIELD(defaultOOMPolicy, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The default out-of-memory score adjustment"),
                SD_VARLINK_DEFINE_FIELD(defaultOOMScoreAdjust, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The ctrl+alt+del burst action"),
                SD_VARLINK_DEFINE_FIELD(ctrlAltDelBurstAction, SD_VARLINK_STRING, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                ManagerRuntime,
                SD_VARLINK_FIELD_COMMENT("Timestamp when the firmware first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(firmwareTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the boot loader first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(loaderTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the kernel first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(kernelTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the initrd first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the initrd first began execution"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(userspaceTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the system finished booting up"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(finishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started uploading security policies to the kernel"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(securityStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished uploading security policies to the kernel"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(securityFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started executing generators"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(generatorsStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished executing generators"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(generatorsFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first started loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first finished loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager last started loading units"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(unitsLoadTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started uploading security policies to the kernel in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdSecurityStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished uploading security policies to the kernel in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdSecurityFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager started executing generators in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdGeneratorsStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager finished executing generators in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdGeneratorsFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first started loading units in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdUnitsLoadStartTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the manager first finished loading units in the initrd"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(initrdUnitsLoadFinishTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("The current log level of the manager"),
                SD_VARLINK_DEFINE_FIELD(logLevel, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The current log target of the manager"),
                SD_VARLINK_DEFINE_FIELD(logTarget, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of unique unit names currently loaded"),
                SD_VARLINK_DEFINE_FIELD(nNames, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of failed units"),
                SD_VARLINK_DEFINE_FIELD(nFailedUnits, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The amount of currently queued jobs"),
                SD_VARLINK_DEFINE_FIELD(nJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The total amount of queued jobs"),
                SD_VARLINK_DEFINE_FIELD(nInstalledJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("The total amount of failed jobs"),
                SD_VARLINK_DEFINE_FIELD(nFailedJobs, SD_VARLINK_INT, 0),
                SD_VARLINK_FIELD_COMMENT("Boot progress as a floating point value between 0.0 and 1.0"),
                SD_VARLINK_DEFINE_FIELD(progress, SD_VARLINK_FLOAT, 0),
                SD_VARLINK_FIELD_COMMENT("The manager environment variables"),
                SD_VARLINK_DEFINE_FIELD(environment, SD_VARLINK_STRING, SD_VARLINK_MAP),
                SD_VARLINK_FIELD_COMMENT("The hardware watchdog device currently in use"),
                SD_VARLINK_DEFINE_FIELD(watchdogDevice, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Timestamp when the hardware watchdog was last pinged"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(watchdogLastPingTimestamp, Timestamp, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Root of the control group hierarchy that the manager is running in"),
                SD_VARLINK_DEFINE_FIELD(controlGroup, SD_VARLINK_STRING, SD_VARLINK_NULLABLE),
                SD_VARLINK_FIELD_COMMENT("Current state of the system"),
                SD_VARLINK_DEFINE_FIELD(systemState, SD_VARLINK_STRING, 0),
                SD_VARLINK_FIELD_COMMENT("Exit code of the manager"),
                SD_VARLINK_DEFINE_FIELD(exitCode, SD_VARLINK_INT, 0));

static SD_VARLINK_DEFINE_STRUCT_TYPE(
                Manager,
                SD_VARLINK_FIELD_COMMENT("Configuration of the manager"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(context, ManagerContext, 0),
                SD_VARLINK_FIELD_COMMENT("Runtime information of the manager"),
                SD_VARLINK_DEFINE_FIELD_BY_TYPE(runtime, ManagerRuntime, 0));

static SD_VARLINK_DEFINE_METHOD(
                Describe,
                SD_VARLINK_DEFINE_OUTPUT_BY_TYPE(manager, Manager, 0));

SD_VARLINK_DEFINE_INTERFACE(
                io_systemd_Manager,
                "io.systemd.Manager",
                &vl_method_Describe,
                &vl_type_Manager,
                &vl_type_ManagerContext,
                &vl_type_ManagerRuntime,
                &vl_type_Timestamp,
                &vl_type_ResourceLimit,
                &vl_type_RateLimit);
