.TH DEVMAP_NAME 8 "February 2004" "" "Linux Administrator's Manual"
.SH NAME
devmap_name \- Query device-mapper name
.SH SYNOPSIS
.BI devmap_name " major minor"
.SH DESCRIPTION
.B devmap_name
queries the device-mapper for the name for the device
specified by
.I major
and
.I minor
number.
.br
.B devmap_name
can be called from
.B udev
by the following rule in
.IR /etc/udev/udev.rules :
.sp
.nf
KERNEL="dm-[0-9]*", PROGRAM="/sbin/devmap_name %M %m", \\
	NAME="%k", SYMLINK="%c"
.fi
.SH "SEE ALSO"
.BR udev (8),
.BR dmsetup (8)
.SH AUTHORS
.B devmap_name
was developed by Christophe Varoqui, <christophe.varoqui@free.fr> and others.
