// SPDX-License-Identifier: LGPL-2.1-or-later

//! Raw FFI bindings for everything libsystemd-shared exports, generated by bindgen at build time from
//! `bindings.h`. Nothing here is safe to call; programs use the `systemd_shared` crate and add wrappers there.

include!("systemd_shared_sys_generated.rs");

// Object-like macros with casts, see the const helpers at the end of bindings.h. The 64-bit ones bindgen
// does not evaluate are written out.
pub const UID_INVALID: uid_t = RUST_CONST_HELPER_UID_INVALID;
pub const GID_INVALID: gid_t = RUST_CONST_HELPER_GID_INVALID;
pub const UID_NOBODY: uid_t = RUST_CONST_HELPER_UID_NOBODY;
pub const GID_NOBODY: gid_t = RUST_CONST_HELPER_GID_NOBODY;
pub const MODE_INVALID: mode_t = RUST_CONST_HELPER_MODE_INVALID;
pub const PID_AUTOMATIC: pid_t = RUST_CONST_HELPER_PID_AUTOMATIC;
pub const USEC_PER_MSEC: usec_t = RUST_CONST_HELPER_USEC_PER_MSEC;
pub const USEC_PER_SEC: usec_t = RUST_CONST_HELPER_USEC_PER_SEC;
pub const USEC_PER_MINUTE: usec_t = RUST_CONST_HELPER_USEC_PER_MINUTE;
pub const USEC_PER_HOUR: usec_t = RUST_CONST_HELPER_USEC_PER_HOUR;
pub const USEC_PER_DAY: usec_t = RUST_CONST_HELPER_USEC_PER_DAY;
pub const USEC_PER_WEEK: usec_t = RUST_CONST_HELPER_USEC_PER_WEEK;
pub const NSEC_PER_USEC: nsec_t = RUST_CONST_HELPER_NSEC_PER_USEC;
pub const NSEC_PER_MSEC: nsec_t = RUST_CONST_HELPER_NSEC_PER_MSEC;
pub const NSEC_PER_SEC: nsec_t = RUST_CONST_HELPER_NSEC_PER_SEC;
pub const VERB_ANY: core::ffi::c_uint = RUST_CONST_HELPER_VERB_ANY;
pub const USEC_INFINITY: usec_t = u64::MAX;
pub const NSEC_INFINITY: nsec_t = u64::MAX;
