#!/usr/bin/env bash
set -e

# We don't use mkosi.extra because /usr/sbin could be a symlink and cp doesn't handle that properly until
# coreutils 9.5 or newer.
cat >"$BUILDROOT/sbin/init" <<EOF
#!/usr/bin/env bash
echo "Hello from dummy init, beautiful day, innit?"
ip link
EOF
chmod +x "$BUILDROOT/sbin/init"

# Arch relies on tmpfiles.d/etc.conf but this image isn't booted
if [ ! -e "$BUILDROOT/etc/os-release" ]; then
    ln -s ../usr/lib/os-release "$BUILDROOT/etc/os-release"
fi
