# SPDX-License-Identifier: LGPL-2.1-or-later

[Output]
Format=directory

[Build]
Environment=SYSTEMD_REQUIRED_DEPS_ONLY=1

[Content]
Bootable=no
Locale=C.UTF-8
WithDocs=no
CleanPackageMetadata=yes
# We provide a custom dummy init for this container so drop the systemd binary, otherwise
# nspawn prefers it over our /sbin/init
RemoveFiles=/usr/lib/systemd/systemd

Packages=
        bash
        grep
        socat
        util-linux

[Include]
Include=%D/mkosi/mkosi.sanitizers
