.TH DASD_ID 8 "November 2005" "" "Linux Administrator's Manual"
.SH NAME
dasd_id \- udev callout to read label from s390 block device
.SH SYNOPSIS
.BI dasd_id
[\fI--export\fP] \fIblockdevice\fP
.SH "DESCRIPTION"
.B dasd_id
is normally called from a udev rule, to provide udev with a unique string and
additional information (type, serial) for an S390 drive. Udev can use this
information to create symlinks in /dev/disk/by-id and /dev/disk/by-label
to the real device node.
.SH USAGE
.B dasd_id
opens the blockdevice node specified at the commandline and prints the
information chosen by the options.
.SH OPTIONS
The following commandline switches are supported to specify what dasd_id
should print:
.TP
.BI --export
print all values (instead of only the serial)
.RE
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Arnd Bergmann <arnd@arndb.de> and Kay Sievers <kay.sievers@vrfy.org>.

