.TH CREATE_FLOPPY_DEVICES 8 "January 2009" "" "Linux Administrator's Manual"
.SH NAME
create_floppy_devices \- udev callout to create all possible floppy devices
based on the CMOS type.
.SH SYNOPSIS
create_floppy_devices [\fIoptions\fP] \fIdevice\fP
.SH OPTIONS
Note that no output will be produced unless the \fB-t\fP option is set.
.TP
.B -c
Create nodes.
.TP
.B -d
Print nodes to stdout.
.TP
.BI "-t " type
Set CMOS floppy type. Type numbers are based on the six floppy types specified
in the kernel's drivers/block/floppy.c, as follows.
.TS
lb lb
l l.
Type	Device
0	Unknown. (Produces no output.)
1	5 1/4" 360KB PC
2	5 1/4" HD AT
3	3 1/2" DD
4	3 1/2" HD
5	3 1/2" ED
6	Same as 5.
.TE
.TP
.BI "-m " number
Set major number.
.TP
.BI "-U " user
Set user ownership.
.TP
.BI "-G " group
Set group ownership.
.TP
.BI "-M " mode
Set device node mode.
.SH SEE ALSO
.BR udev (7)
.SH AUTHORS
Developed by Hannes Reinecke <hare@suse.de>.
