# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Distribution]
Release=edge

[Content]
VolatilePackages=
        systemd
        systemd-journald
        systemd-libs
        systemd-logind
        systemd-networkd
        systemd-resolved
        systemd-tests
        systemd-timesyncd
        systemd-udevd

Packages=
        agetty
        bind-tools
        bpftool
        coreutils
        erofs-utils
        execline
        gnutls-utils
        iproute2
        iputils
        knot
        knot-utils
        libcap-ng-utils
        libcap-utils
        libmicrohttpd
        libsoup3
        linux-firmware-none
        linux-stable
        lvm2
        man-db
        musl-locales
        net-tools
        nmap-ncat
        openssh-client
        openssh-server
        openssl
        perf
        postmarketos-base
        procps-ng
        psmisc
        py3-elftools
        py3-pexpect
        py3-psutil
        py3-pytest
        py3-zstd
        quota-tools
        sfdisk
        shadow
        softhsm
        squashfs-tools
        stress-ng
        tpm2-tools
        uutils-coreutils-groups
        vim-common
