# SPDX-License-Identifier: LGPL-2.1-or-later

[Config]
Dependencies=
        base
        minimal-base
        minimal_0
        minimal_1
        app0
        app1
        app-nodistro
        app-reload
        service-scoped-test
        conf0
        testsuite-04-journal-interactive-debug
        testsuite-55-oomd
        testsuite-58-repart
        testsuite-69-shutdown

[Distribution]
CacheOnly=metadata

[Output]
@Format=directory

[Content]
BaseTrees=%O/base
Initrds=%O/base.initrd
ExtraTrees=
        %O/minimal_0.root-%a.raw:/usr/share/minimal_0.raw
        %O/minimal_0.root-%a-verity.raw:/usr/share/minimal_0.verity
        %O/minimal_0.root-%a-verity-sig.raw:/usr/share/minimal_0.verity.sig
        %O/minimal_1.root-%a.raw:/usr/share/minimal_1.raw
        %O/minimal_1.root-%a-verity.raw:/usr/share/minimal_1.verity
        %O/minimal_1.root-%a-verity-sig.raw:/usr/share/minimal_1.verity.sig
        %O/app0.root-%a.raw:/usr/share/app0.raw
        %O/app0.root-%a-verity.raw:/usr/share/app0.verity
        %O/app0.root-%a-verity-sig.raw:/usr/share/app0.verity.sig
        %O/app1.root-%a.raw:/usr/share/app1.raw
        %O/app1.root-%a-verity.raw:/usr/share/app1.verity
        %O/app1.root-%a-verity-sig.raw:/usr/share/app1.verity.sig
        %O/conf0.root-%a.raw:/usr/share/conf0.raw
        %O/conf0.root-%a-verity.raw:/usr/share/conf0.verity
        %O/conf0.root-%a-verity-sig.raw:/usr/share/conf0.verity.sig
        %O/app-nodistro.root-%a.raw:/usr/share/app-nodistro.raw
        %O/app-nodistro.root-%a-verity.raw:/usr/share/app-nodistro.verity
        %O/app-nodistro.root-%a-verity-sig.raw:/usr/share/app-nodistro.verity.sig
        %O/app-reload.root-%a.raw:/usr/share/app-reload.raw
        %O/app-reload.root-%a-verity.raw:/usr/share/app-reload.verity
        %O/app-reload.root-%a-verity-sig.raw:/usr/share/app-reload.verity.sig
        %O/service-scoped-test.root-%a.raw:/etc/service-scoped-test.raw
        %O/service-scoped-test.root-%a-verity.raw:/etc/service-scoped-test.verity
        %O/service-scoped-test.root-%a-verity-sig.raw:/etc/service-scoped-test.verity.sig
        ../../test/test-journals:/usr/test-journals
        ../../test/knot-data/zones:/var/lib/knot/zones
        ../../test/knot-data/knot.conf:/etc/knot/knot.conf
        ../../mkosi.crt:/usr/lib/verity.d/mkosi.crt
        %O/testsuite-04-journal-interactive-debug.raw:/usr/share/testsuite-04-journal-interactive-debug.raw
        %O/minimal-base:/usr/lib/systemd/tests/testdata/testsuite-13-container-template
        %O/testsuite-55-oomd.raw:/usr/share/testsuite-55-oomd.raw
        %O/testsuite-58-repart.raw:/usr/share/testsuite-58-repart.raw
        %O/testsuite-69-shutdown.raw:/usr/share/testsuite-69-shutdown.raw

Packages=
        knot
        lvm2
        mdadm
        nvme-cli
        screen

[Host]
@QemuSmp=2
KernelCommandLineExtra=
        systemd.crash_shell
        systemd.log_level=debug
        systemd.log_ratelimit_kmsg=0
        systemd.journald.forward_to_console
        systemd.journald.max_level_console=warning
        # Disable the kernel's ratelimiting on userspace logging to kmsg.
        printk.devkmsg=on
        # Make sure /sysroot is mounted rw in the initrd.
        rw
        # Lower the default device timeout so we get a shell earlier if the root device does
        # not appear for some reason.
        systemd.default_device_timeout_sec=200
        # Make sure no LSMs are enabled by default.
        apparmor=0
        selinux=0
        enforcing=0
        systemd.early_core_pattern=/core
        systemd.firstboot=no
        noresume
        oops=panic
        panic=1

[Validation]
@SecureBoot=yes
@SignExpectedPcr=yes
