# SPDX-License-Identifier: LGPL-2.1-or-later

# The mixed case ID checks that entry IDs are matched case insensitively.
[UKIProfile]
Profile=
        ID=Profile2
        TITLE=Profile Two
Cmdline=testprofile2=1
