.TH MULTIPATH 8 "February 2004" "" "Linux Administrator's Manual"
.SH NAME
multipath \- Device mapper target autoconfig
.SH SYNOPSIS
.B multipath
.RB [\| \-v | \-q \|]
.RB [\| \-d \|]
.RB [\| \-m\ \c
.IR max_devs \|]
.RB [\| \-p\ \c
.BR failover | multibus | group_by_serial \|]
.RB [\| device \|]
.SH DESCRIPTION
.B multipath
is used to detect multiple paths to devices for fail-over or performance reasons and coalesces them.
.SH OPTIONS
.TP
.B \-v
verbose, print all paths and multipaths
.TP
.B \-q
quiet, no output at all
.TP
.B \-d
dry run, do not create or update devmaps
.TP
.BI \-m " max_devs"
scan
.I max_devs
devices at most
.TP
.BI \-p " policy"
force maps to specified policy:
.RS 1.2i
.TP 1.2i
.B failover
1 path per priority group
.TP
.B multibus
all paths in 1 priority group
.TP
.B group_by_serial
1 priority group per serial
.RE
.TP
.B device
limit the [re]configuration to the specified device's multipath scope. device is given in its hotplug $DEVPATH form like /devices/pci0000:03/0000:03:01.0/host0/0:0:5:1
.SH "SEE ALSO"
.BR udev (8),
.BR dmsetup (8)
.SH AUTHORS
.B multipath
was developed by Christophe Varoqui, <christophe.varoqui@free.fr> and others.
