# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=arch

[Build]
Environment=
        GIT_URL=https://gitlab.archlinux.org/archlinux/packaging/packages/systemd.git
        GIT_BRANCH=main
        GIT_COMMIT=f884cb080300eeb273fb7549fd0aa19bb6142c21
        PKG_SUBDIR=arch
