# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|fedora
Distribution=|centos
Profiles=!hyperscale

[Build]
Environment=
        GIT_URL=https://src.fedoraproject.org/rpms/systemd.git
        GIT_BRANCH=rawhide
        GIT_COMMIT=57cbcf979ce2dd872a871c59e87d2c65dfa996e6
        PKG_SUBDIR=fedora
