# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|fedora
Distribution=|centos
Profiles=!hyperscale

[Build]
Environment=
        GIT_URL=https://src.fedoraproject.org/rpms/systemd.git
        GIT_BRANCH=rawhide
        GIT_COMMIT=034fa693f2da8a0f9ea261128cc81654a8be905f
        PKG_SUBDIR=fedora
