# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|fedora
Distribution=|centos
Profiles=!hyperscale

[Build]
Environment=
        GIT_URL=https://src.fedoraproject.org/rpms/systemd.git
        GIT_BRANCH=rawhide
        GIT_COMMIT=207e2d004468bf79a8bd78182d9b10956edf45c7
        PKG_SUBDIR=fedora
