# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|debian
Distribution=|ubuntu

[Build]
Environment=
        GIT_URL=https://salsa.debian.org/systemd-team/systemd.git
        GIT_SUBDIR=debian
        GIT_BRANCH=ci/v261-stable
        GIT_COMMIT=8e947316488c163321665a60766dbc972e9edf7a
        PKG_SUBDIR=debian
