# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|debian
Distribution=|ubuntu

[Build]
Environment=
        GIT_URL=https://salsa.debian.org/systemd-team/systemd.git
        GIT_SUBDIR=debian
        GIT_BRANCH=debian/master
        GIT_COMMIT=56402b2bde258999a8f01a8b04465fde9242d6a1
        PKG_SUBDIR=debian
