# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=|debian
Distribution=|ubuntu

[Build]
Environment=
        GIT_URL=https://salsa.debian.org/systemd-team/systemd.git
        GIT_SUBDIR=debian
        GIT_BRANCH=debian/master
        GIT_COMMIT=3e1930512d1efee7e11b619a5f493b3229594a51
        PKG_SUBDIR=debian
