# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=nura

[Build]
Environment=
        GIT_URL=https://gitlab.postmarketos.org/postmarketOS/pmaports
        GIT_SUBDIR=extra-repos/systemd/systemd
        GIT_BRANCH=main
        GIT_COMMIT=7a6b81a4f1a7a510d088a5874bebcf2b200b69b3
        PKG_SUBDIR=nura
