# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=opensuse

[Build]
Environment=
        GIT_URL=https://github.com/bmwiedemann/openSUSE
        GIT_SUBDIR=packages/s/systemd
        GIT_BRANCH=master
        GIT_COMMIT=462bd9f5eae8d113d0e477455278f64d0284afe8
        PKG_SUBDIR=opensuse
