# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Build]
Environment=
        GIT_URL=https://gitlab.postmarketos.org/postmarketOS/pmaports
        GIT_SUBDIR=extra-repos/systemd/systemd
        GIT_BRANCH=main
        GIT_COMMIT=f908244ec2a0f85a84f44927183711160a798705
        PKG_SUBDIR=postmarketos
