# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=postmarketos

[Build]
Environment=
        GIT_URL=https://gitlab.postmarketos.org/postmarketOS/pmaports
        GIT_SUBDIR=extra-repos/systemd/systemd
        GIT_BRANCH=main
        GIT_COMMIT=07ea0bed8fbbafe06b2bf68b6bfabcf86c2e4449
        PKG_SUBDIR=postmarketos
