# SPDX-License-Identifier: LGPL-2.1-or-later

[Match]
Distribution=fedora

[Distribution]
Release=rawhide

[Content]
Packages=
        btrfs-progs
        dhcp-server
        dnf5
        # Required by test-resolved-doh-server; only a weak dependency of libsoup3 on older Fedora releases.
        glib-networking
        # Required for systemd-networkd-tests.py (netdevsim and sch_xxx modules)
        kernel-modules-extra
        kernel-modules-internal
        libsoup3
        rpmautospec
        scsi-target-utils
        util-linux-script
