# SPDX-License-Identifier: LGPL-2.1-or-later
#
# This file is part of systemd.
#
# Entries in this file show the compile time defaults. Local configuration
# should be created by either modifying this file (or a copy of it placed in
# /etc/ if the original file is shipped in /usr/), or by creating "drop-ins" in
# the timestampd.conf.d/ directory. The latter is generally recommended.
# Defaults can be restored by simply deleting the main configuration file and
# all drop-ins located in /etc/.
#
# Use 'systemd-analyze cat-config systemd/timestampd.conf' to display the full config.
#
# See timestampd.conf(5) for details.

[Timestamp]
# The default Time-Stamp Authority to contact. Must be a tcp:// URL, or an
# http:// or https:// one if this build has libcurl support. The scheme selects
# the RFC 3161 transport. A Varlink caller may override this per request.
#Authority=
#ConnectionTimeoutSec=90
#DataSizeMax=1G
