---

name: Gather Pull Request Metadata

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  gather-metadata:
    if: github.repository == 'systemd/systemd'
    runs-on: ubuntu-24.04

    steps:
      - name: Repository checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          persist-credentials: false

      - id: metadata
        name: Gather Pull Request Metadata
        uses: redhat-plumbers-in-action/gather-pull-request-metadata@ecc2e46fe4f0b2e9a7b236d6012bc9f74af318d0

      - name: Upload Pull Request Metadata artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: Pull Request Metadata
          path: ${{ steps.metadata.outputs.metadata-file }}
          retention-days: 1
