# SPDX-License-Identifier: LGPL-2.1-or-later

name: Make a Github release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  release:
    if: github.repository == 'systemd/systemd' || github.repository == 'systemd/systemd-stable'
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64
        with:
          prerelease: ${{ contains(github.ref_name, '-rc') }}
          draft: ${{ github.repository == 'systemd/systemd' }}
